"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),core=require("../phase26-31-manual-post-registration-post-correction-verification-decision-core.js");
const clock={now:()=>new Date("2026-08-04T04:00:00Z")},op=reason=>({performedBy:"human-decider",reason,explicitConfirmation:true});
const checks={targetIdentityVerified:true,targetKeyVerified:true,registrationReferenceVerified:true,planReferenceVerified:true,approvalReferenceVerified:true,executionReferenceVerified:true,beforeSnapshotVerified:true,afterSnapshotVerified:true,expectedChangeVerified:true,unchangedFieldVerified:true,unexpectedChangeChecked:true,requiredFieldChecked:true,typeChecked:true,formatChecked:true,rangeChecked:true,consistencyChecked:true,relationIntegrityChecked:true,duplicateChecked:true,auditTrailChecked:true,evidenceChecked:true,safetyFlagsChecked:true};
const verification=(o={})=>({postCorrectionVerificationId:"verification-30",correctionExecutionId:"execution-29",correctionExecutionApprovalId:"approval-28",correctionPlanApprovalId:"approval-27",correctionPlanId:"plan-26",correctionRequestId:"request-25",correctionImpactReviewId:"impact-24",correctionTargetIdentificationId:"target-23",registrationRecordId:"registration-1",acceptanceRecordId:"acceptance-1",importRecordId:"import-1",sourceRecordId:"source-1",raceId:"race-1",targetRecordType:"race_result",targetRecordKey:"race-1",verificationStatus:"ready_for_manual_post_correction_verification_decision",verificationResult:"verified",abnormalityDetected:false,criticalIssueDetected:false,unresolvedIssueCount:0,rollbackStatus:"not_required",hashMatchResult:"match",versionMatchResult:"match",missingExpectedChanges:[],unexpectedChangedFields:[],invalidFields:[],missingFields:[],duplicateFields:[],typeMismatchFields:[],formatMismatchFields:[],rangeViolationFields:[],relationMismatchFields:[],currentDataHash:"current-hash",currentVersion:"v2",recordVersion:3,auditTrail:[{event:"completed",performedBy:"Verifier",performedAt:"2026-08-04T03:00:00Z"}],warningDetected:false,protectedMode:true,planOnly:true,privateLocalOnly:true,automaticCorrectionAllowed:false,automaticExecutionAllowed:false,automaticVerificationAllowed:false,automaticDecisionAllowed:false,automaticApprovalAllowed:false,automaticAcceptanceAllowed:false,automaticApplicationAllowed:false,automaticLearningAllowed:false,publicReleaseAllowed:false,externalTransmissionAllowed:false,appliedToPrediction:false,appliedToLearning:false,sentExternally:false,...checks,...o});
const context=(o={})=>({postCorrectionVerificationId:"verification-30",registrationRecordId:"registration-1",targetRecordKey:"race-1",verificationSnapshotHash:"verification-hash",verificationVersion:"3",...o});
const input=(o={})=>({recordedBy:"recorder",decisionEnvironment:"Private Local",decisionDevice:"local-pc",decisionLocation:"local",decisionMethod:"manual review",decisionReference:"decision-sheet",verificationSnapshot:{verificationResult:"verified"},executionSnapshot:{correctionExecutionId:"execution-29"},approvalSnapshot:{correctionExecutionApprovalId:"approval-28"},planSnapshot:{correctionPlanId:"plan-26"},registrationSnapshot:{registrationRecordId:"registration-1"},currentTargetSnapshot:{finishTime:"1:34.8"},verificationSnapshotHash:"verification-hash",executionSnapshotHash:"execution-hash",approvalSnapshotHash:"approval-hash",planSnapshotHash:"plan-hash",currentTargetHash:"current-hash",verificationVersion:"3",executionVersion:"2",currentTargetVersion:"v2",...o});
function create(){core.resetRegistry();const x=core.createManualVerificationDecision(verification(),context(),input(),op("create"),clock);assert(x.created,x.reasons);return x.record}
function inProgress(){let r=create(),x=core.startManualDecision(r,{manualStartConfirmation:true,decidedBy:"Decider"},op("start"),clock);assert(x.transitioned,x.reasons);x=core.recordManualDecisionProgress(x.record,{decisionNote:"reviewing"},op("progress"),clock);assert(x.transitioned,x.reasons);return x.record}
const decisionInput=(o={})=>({decisionReason:"all checks confirmed",decisionSummary:"manual decision",nextAction:"prepare manual acceptance candidate",warningsReviewed:true,registrationRecordId:"registration-1",targetRecordKey:"race-1",existingDecisionRecords:[],...o});
let v=verification(),gate=core.validateDecisionEligibility(v,context(),[]);assert(gate.eligible,gate.reasons);assert.strictEqual(core.extractEligibleDecisionCandidates([v],[context()],[]).length,1);
for(const bad of[verification({verificationStatus:"manual_verification_completed"}),verification({abnormalityDetected:true}),verification({criticalIssueDetected:true}),verification({unresolvedIssueCount:1}),verification({hashMatchResult:"mismatch"}),verification({versionMatchResult:"mismatch"}),verification({unexpectedChangedFields:["horseName"]}),verification({automaticDecisionAllowed:true}),verification({automaticApprovalAllowed:true}),verification({automaticAcceptanceAllowed:true}),verification({automaticApplicationAllowed:true}),verification({automaticLearningAllowed:true}),verification({publicReleaseAllowed:true}),verification({externalTransmissionAllowed:true})])assert(!core.validateDecisionEligibility(bad,context(),[]).eligible);
assert(!core.validateDecisionEligibility(v,context({targetRecordKey:"other"}),[]).eligible);assert(!core.validateDecisionEligibility(v,context(),[{postCorrectionVerificationId:"verification-30",invalidatedAt:""}]).eligible);
let r=create();assert.strictEqual(r.decisionStatus,"awaiting_manual_decision");assert(r.auditTrail.length===1);let x=core.startManualDecision(r,{manualStartConfirmation:true,decidedBy:"Decider"},op("start"),clock);assert(x.transitioned);x=core.recordManualDecisionProgress(x.record,{},op("progress"),clock);assert(x.transitioned);let paused=core.pauseManualDecision(x.record,"pause",op("pause"),clock);assert(paused.transitioned);let resumed=core.resumeManualDecision(paused.record,{manualResumeConfirmation:true},op("resume"),clock);assert(resumed.transitioned);
r=resumed.record;x=core.approveDecision(r,v,decisionInput(),op("approve"),clock);assert(x.completed,x.reasons);assert.strictEqual(x.record.decisionStatus,"decision_approved");assert(x.record.approvedForManualPostCorrectionAcceptance);let candidate=core.createAcceptanceCandidate(x.record,op("handoff"),clock);assert(candidate.created,candidate.reasons);assert(candidate.candidate.readyForManualPostCorrectionAcceptance);assert.strictEqual(candidate.record.decisionStatus,"ready_for_manual_post_correction_acceptance");assert(!core.transition(candidate.record,"manual_decision_in_progress",op("overwrite"),clock).transitioned);
for(const [fn,result,state] of[["rejectDecision","reject","decision_rejected"],["returnForReverification","return_for_reverification","decision_returned_for_reverification"],["returnForCorrection","return_for_correction","decision_returned_for_correction"],["holdDecision","hold","decision_on_hold"],["requireRollback","rollback_required","rollback_required"],["requireAdditionalEvidence","additional_evidence_required","additional_evidence_required"],["requireAdditionalReview","additional_review_required","additional_review_required"]]){r=inProgress();x=core[fn](r,v,decisionInput({nextAction:result}),op(result),clock);assert(x.completed,x.reasons);assert.strictEqual(x.record.decisionStatus,state);assert.strictEqual(x.record.decisionResult,result);assert(!core.createAcceptanceCandidate(x.record,op("blocked"),clock).created)}
r=inProgress();assert(!core.approveDecision(r,v,decisionInput({decisionReason:""}),op("missing reason"),clock).completed);assert(!core.approveDecision(r,verification({hashMatchResult:"mismatch"}),decisionInput(),op("bad hash"),clock).completed);assert(!core.approveDecision(r,v,decisionInput({warningsReviewed:false}),op("warning not reviewed"),clock).completed);
const integrity=core.verifyVerificationIntegrity(v,{registrationRecordId:"registration-1",targetRecordKey:"race-1"});assert(integrity.allValid);assert(core.confirmHash(v,input()).valid);assert(core.confirmVersion(v,input()).valid);
const memory={value:null,setItem(k,val){this.value=val},getItem(){return this.value}};r=create();assert(core.saveRecords(memory,[r]).saved);assert(core.loadRecords(memory).loaded);memory.value=JSON.stringify({schemaVersion:"old",records:[]});assert(!core.loadRecords(memory).loaded);
assert(core.SAFETY.privateLocalOnly&&core.SAFETY.planOnly&&core.SAFETY.protectedMode);for(const k of["automaticCorrectionAllowed","automaticExecutionAllowed","automaticVerificationAllowed","automaticDecisionAllowed","automaticApprovalAllowed","automaticAcceptanceAllowed","automaticApplicationAllowed","automaticLearningAllowed","publicReleaseAllowed","externalTransmissionAllowed","sourceDataMutated","registeredDataMutated","appliedToPrediction","appliedToLearning","sentExternally","githubPagesEnabled","nextPhaseAutomaticallyStarted"])assert.strictEqual(core.SAFETY[k],false,k);
const root=path.join(__dirname,".."),html=fs.readFileSync(path.join(root,"private-local.html"),"utf8"),css=fs.readFileSync(path.join(root,"dashboard.css"),"utf8"),readme=fs.readFileSync(path.join(root,"README.md"),"utf8"),source=fs.readFileSync(path.join(root,"phase26-31-manual-post-registration-post-correction-verification-decision-core.js"),"utf8");for(const text of["phase26-31-manual-post-registration-post-correction-verification-decision","対象修正後検証記録","対象修正実行記録","対象正式登録記録","判定状態","判定者","判定日時","検証結果","hash結果","version結果","差分結果","整合性結果","証跡","監査証跡","ロールバック状態","異常","警告","判定結果","判定理由","次アクション","次工程移行可否","Private Local only","PLAN_ONLY","protectedMode","自動判定なし","自動承認なし","自動受入なし","自動適用なし","自動学習更新なし","Public公開なし","外部送信なし"])assert(html.includes(text),text);assert(css.includes(".phase2631-panel")&&readme.includes("Phase26-31 Manual Post-Correction Verification Decision Core"));for(const p of[/fetch\s*\(/,/XMLHttpRequest/,/WebSocket\s*\(/,/automaticDecisionAllowed:\s*true/,/automaticApprovalAllowed:\s*true/,/automaticAcceptanceAllowed:\s*true/,/registeredDataMutated:\s*true/])assert(!p.test(source));
console.log("phase26ManualPostRegistrationPostCorrectionVerificationDecisionCore.test.js: PASS");
