"use strict";
const assert=require("assert"),fs=require("fs"),vm=require("vm"),core=require("../phase30-10-phase30-post-start-stabilization-followup-core.js"),p309=core.PHASE309_REFERENCE,NOW="2027-01-05T00:00:00Z",options={now:()=>new Date(NOW)},human={performedBy:"human",reason:"manual stabilization followup",explicitConfirmation:true,performedAt:NOW};
function build(api){
 const version=api.SCHEMA_VERSION,terminal=version.startsWith("29."),ref=Object.keys(api).find(k=>/^PHASE\d+_REFERENCE$/.test(k));
 const up=terminal?null:build(api[ref]);
 const parentValidator=terminal?core.PHASE309_REFERENCE.PHASE308_REFERENCE.PHASE307_REFERENCE.PHASE306_REFERENCE.PHASE305_REFERENCE.PHASE304_REFERENCE.PHASE303_REFERENCE.PHASE302_REFERENCE.PHASE301_REFERENCE.validatePhase2919Eligibility:null;
 const files=fs.readdirSync(require("path").join(__dirname,"..")).filter(f=>f.startsWith("phase30-")&&f.endsWith("core.js"));
 let validator=parentValidator;
 if(!terminal){for(const file of files){const a=require("../"+file);const key="validatePhase"+version.split(".").slice(0,2).join("")+"Eligibility";if(a[key]){validator=a[key];break}}}
 const text=validator.toString(),status=text.match(/s\.([A-Za-z0-9]+Status)!=="([^"]+)"/),result=text.match(/s\.([A-Za-z0-9]+Result)!=="([^"]+)"/),name=status[1].slice(0,-6);
 const b={...api.SAFETY,[name+"Id"]:name+"-1",[status[1]]:status[2],[result[1]]:result[2],errors:[],unresolvedIssues:[],criticalIssues:[],blockingConditions:[],recordVersion:1,auditTrail:[{action:"manual",from:"",to:status[2],performedBy:"human",reason:"confirmed",performedAt:NOW}]};
 for(const k of api.REFERENCE_IDS.concat(api.UPSTREAM_FIELDS))b[k]=up?up[k]:k+"-1";
 if(up)b[ref.toLowerCase().replace("_reference","SourceSnapshot")]=up;
 if(!terminal&&Number(version.split(".")[1])>=4)b.phase30Started=b.manualPhase30StartCompleted=true;const snap={...b};if(name==="phase30Definition")delete snap.phase2919SourceSnapshot;
 return {...b,[name+"Snapshot"]:snap,[name+"SnapshotHash"]:api.computeSnapshotHash(snap),[name+"Version"]:version};
}
const decisionInput={};p309.DECISION_FIELDS.forEach(k=>decisionInput[k]=k);p309.ARRAY_FIELDS.forEach(k=>decisionInput[k]=[]);p309.REQUIRED_TRUE.forEach(k=>decisionInput[k]=true);
let decision=p309.createStabilizationDecisionRecord(build(p309.PHASE308_REFERENCE),decisionInput,human,options,[]);assert(decision.created,decision.reasons.join());decision=p309.beginStabilizationDecision(decision.record,human,options);decision=p309.submitStabilizationDecisionReview(decision.record,human,options);decision=p309.decideStabilization(decision.record,{result:p309.RESULTS[0],decisionSummary:"stable",decisionAfterSnapshot:{stable:true},approvedBy:"human",approvedAt:NOW},human,options);assert(decision.decided);const handed=p309.handoffToStabilizationFollowup(decision.record,human,options);assert(handed.handedOff);const VALID_SOURCE=handed.record;function source(p={}){return {...JSON.parse(JSON.stringify(VALID_SOURCE)),...p}}
function input(p={}){const r={};core.FOLLOWUP_FIELDS.forEach(k=>r[k]=k.endsWith("Evidence")||k.endsWith("Snapshot")||["confirmationResults","actionsPerformed","additionalActions","residualRisks"].includes(k)?{confirmed:true}:k);Object.assign(r,{observationStartedAt:"2027-01-03T00:00:00Z",observationEndedAt:"2027-01-04T00:00:00Z"});core.ARRAY_FIELDS.forEach(k=>r[k]=[]);core.REQUIRED_TRUE.forEach(k=>r[k]=true);return{...r,...p}}
let cachedCreated,cachedSubmitted;function create(){if(cachedCreated)return cachedCreated;const x=core.createStabilizationFollowupRecord(source(),input(),human,options,[]);assert(x.created,x.reasons.join());return cachedCreated=x.record}function submitted(){if(cachedSubmitted)return cachedSubmitted;let r=create();r=core.beginStabilizationFollowup(r,human,options).record;return cachedSubmitted=core.submitStabilizationFollowupReview(r,human,options).record}
assert.strictEqual(p309.NEXT_STAGE,"manual_phase30_post_start_stabilization_followup");assert(p309.STATES.includes("ready_for_manual_phase30_post_start_stabilization_followup"));assert(p309.RESULTS.includes("approve_phase30_post_start_stabilization_stable"));assert.strictEqual(core.NEXT_STAGE,"manual_phase30_post_start_stabilization_closure_review");assert.strictEqual(core.extractStabilizationFollowupCandidates([source()],[]).length,1);
for(const p of [{phase30PostStartStabilizationDecisionStatus:"phase30_post_start_stabilization_conditionally_approved"},{phase30PostStartStabilizationDecisionStatus:"phase30_post_start_stabilization_unstable_decided"},{phase30PostStartStabilizationDecisionStatus:"phase30_post_start_stabilization_decision_incomplete"},{phase30PostStartStabilizationDecisionStatus:"phase30_post_start_stabilization_decision_blocked"},{phase30PostStartStabilizationDecisionResult:"conditionally_approve_phase30_post_start_stabilization"},{invalidatedAt:NOW},{expiredAt:NOW},{recordVersion:0},{auditTrail:[]},{phase30PostStartStabilizationDecisionSnapshotHash:"bad"},{phase30PostStartStabilizationDecisionVersion:"bad"},{phase308SourceSnapshot:null},{unresolvedIssues:["x"]},{criticalIssues:["x"]},{blockingConditions:["x"]},{privateLocalOnly:false},{planOnly:false},{protectedMode:false}])assert.strictEqual(core.validatePhase309Eligibility(source(p)).valid,false,JSON.stringify(p));
assert.strictEqual(core.createStabilizationFollowupRecord(source(),input(),{},options,[]).created,false);for(const p of [{followupTarget:""},{followupScope:""},{responsiblePerson:""},{errors:"bad"},{privateLocalOnly:false}])assert.strictEqual(core.createStabilizationFollowupRecord(source(),input(p),human,options,[]).created,false,JSON.stringify(p));
const src=source(),before=JSON.stringify(src),first=core.createStabilizationFollowupRecord(src,input(),human,options,[]);assert(first.created);assert.strictEqual(JSON.stringify(src),before);assert(Object.isFrozen(first.record));assert.strictEqual(core.createStabilizationFollowupRecord(src,input(),human,options,[first.record]).created,false);assert.strictEqual(core.extractStabilizationFollowupCandidates([src],[first.record]).length,0);assert.deepStrictEqual(first.record.phase309SourceSnapshot,src);
assert.strictEqual(core.submitStabilizationFollowupReview(first.record,human,options).transitioned,false);let r=core.beginStabilizationFollowup(first.record,human,options).record;for(const p of [{phase309SourceSnapshot:{}},{phase30PostStartStabilizationDecisionId:"changed"},{auditTrail:[]},{protectedMode:false}])assert.strictEqual(core.updateStabilizationFollowup(r,p,human,options).updated,false);r=core.updateStabilizationFollowup(r,{notes:"updated"},human,options).record;r=core.submitStabilizationFollowupReview(r,human,options).record;
const complete={result:"phase30_post_start_stabilization_followup_completed",followupSummary:"completed",followupAfterSnapshot:{stable:true},completedBy:"operator",completedAt:NOW};for(const p of [{followupSummary:""},{followupAfterSnapshot:null},{completedBy:""},{completedAt:"bad"},{errors:["x"]},{unresolvedIssues:["x"]},{criticalIssues:["x"]},{blockingConditions:["x"]},{runtimeStateConfirmed:false}])assert.strictEqual(core.completeStabilizationFollowup(r,{...complete,...p},human,options).completed,false,JSON.stringify(p));const ok=core.completeStabilizationFollowup(r,complete,human,options);assert(ok.completed,ok.reasons.join());assert.strictEqual(ok.record.phase30PostStartStabilizationFollowupStatus,"phase30_post_start_stabilization_followup_completed");assert(core.integrityIntact(ok.record));assert(core.safetyIntact(ok.record));
assert.strictEqual(core.completeStabilizationFollowup(submitted(),{result:"phase30_post_start_stabilization_followup_conditionally_completed"},human,options).completed,false);assert(core.completeStabilizationFollowup(submitted(),{result:"phase30_post_start_stabilization_followup_conditionally_completed",conditions:"c",conditionReason:"r",conditionOwner:"o",conditionDeadline:"2027-02-01",conditionVerificationMethod:"manual",conditionReleaseCriteria:"verified"},human,options).completed);assert.strictEqual(core.completeStabilizationFollowup(submitted(),{result:"phase30_post_start_stabilization_followup_incomplete",incompleteReason:"r"},human,options).completed,false);assert(core.completeStabilizationFollowup(submitted(),{result:"phase30_post_start_stabilization_followup_incomplete",incompleteReason:"r",requiredActions:"a"},human,options).completed);assert.strictEqual(core.completeStabilizationFollowup(submitted(),{result:"phase30_post_start_stabilization_followup_blocked",blockedReason:"r",blockedImpact:"i"},human,options).completed,false);assert(core.completeStabilizationFollowup(submitted(),{result:"phase30_post_start_stabilization_followup_blocked",blockedReason:"r",blockedImpact:"i",unblockingConditions:"c"},human,options).completed);
assert.strictEqual(core.handoffToStabilizationClosureReview(ok.record,{},options).handedOff,false);const hand=core.handoffToStabilizationClosureReview(ok.record,human,options);assert(hand.handedOff);assert.strictEqual(hand.record.phase30PostStartStabilizationFollowupStatus,"ready_for_manual_phase30_post_start_stabilization_closure_review");assert.strictEqual(hand.record.nextPhaseAutomaticallyStarted,false);assert(core.invalidateStabilizationFollowup(ok.record,human,options).transitioned);
const mem={v:null,setItem(_k,v){this.v=v},getItem(){return this.v}};assert(core.saveStabilizationFollowupRecords(mem,[ok.record]).saved);assert(core.loadStabilizationFollowupRecords(mem).loaded);mem.v="{";assert.strictEqual(core.loadStabilizationFollowupRecords(mem).loaded,false);const view=core.render(ok.record);assert(view.phase309Dependency&&view.privateLocalOnly&&view.planOnly&&view.protectedMode&&view.automaticFollowupDisabled&&view.automaticCompletionDisabled&&view.automaticHandoffDisabled&&view.externalCommunicationDisabled&&view.automationDisabled);
for(const k of ["automaticallyExecute","automaticallyComplete","automaticallyReview","automaticallyFix","automaticallyRollback","automaticallyRecover","automaticallyRestartPhase30","advancePhase30","startNextPhase"])assert.strictEqual(core[k],undefined,k);const code=fs.readFileSync(require.resolve("../phase30-10-phase30-post-start-stabilization-followup-core.js"),"utf8"),browser={HashimotoPhase309PostStartStabilizationDecision:p309};vm.runInNewContext(code,browser);assert(browser.HashimotoPhase3010PostStartStabilizationFollowup);assert(code.includes('require("./phase30-9-phase30-post-start-stabilization-decision-core.js")'));assert.throws(()=>vm.runInNewContext(code,{}),/Phase30-9/);assert(!/fetch\s*\(|XMLHttpRequest|WebSocket|EventSource|sendBeacon\s*\(|http\.request|https\.request|child_process|execSync|spawnSync|setInterval\s*\(|setTimeout\s*\(|(?:new\s+)?(?:Shared)?Worker\s*\(|fs\.writeFile|fs\.mkdir|mkdirSync|writeFileSync|eval\s*\(|new\s+Function\s*\(|Authorization\s*:|Bearer\s+[A-Za-z0-9._~-]+/.test(code));

// Rehashing a modified record must not bypass audit, reference, issue or chain checks.
function restamp(r,name="phase30PostStartStabilizationDecision"){delete r[name+"Snapshot"];delete r[name+"SnapshotHash"];r[name+"Snapshot"]=JSON.parse(JSON.stringify(r));r[name+"SnapshotHash"]=core.computeSnapshotHash(r[name+"Snapshot"]);return r}
for(const patch of [{errors:["error"]},{errors:"bad"},{auditTrail:[{}]},{recordVersion:2},{phase30PostStartStabilizationReviewId:"other"},{phase30PostStartStabilizationReviewVersion:"other"},{expiresAt:"2000-01-01"}])assert.strictEqual(core.validatePhase309Eligibility(restamp(source(patch))).valid,false);
const tampered=source();tampered.phase30PostStartStabilizationDecisionSnapshot.reviewer="tampered";assert.strictEqual(core.validatePhase309Eligibility(tampered).valid,false);
for(const field of ["performedBy","reason","performedAt","explicitConfirmation"]){const h={...human};delete h[field];assert.strictEqual(core.createStabilizationFollowupRecord(source(),input(),h,options,[]).created,false);assert.strictEqual(core.beginStabilizationFollowup(first.record,h,options).transitioned,false);assert.strictEqual(core.updateStabilizationFollowup(r,{followupNotes:"x"},h,options).updated,false);assert.strictEqual(core.submitStabilizationFollowupReview(r,h,options).transitioned,false);assert.strictEqual(core.completeStabilizationFollowup(r,complete,h,options).completed,false);assert.strictEqual(core.handoffToStabilizationClosureReview(ok.record,h,options).handedOff,false);assert.strictEqual(core.invalidateStabilizationFollowup(ok.record,h,options).transitioned,false)}
const failed=core.completeStabilizationFollowup(submitted(),{result:core.RESULTS[4],failedReason:"failed",failedImpact:"review needed",requiredActions:["manual investigation"]},human,options);assert(failed.completed);assert.strictEqual(core.handoffToStabilizationClosureReview(failed.record,human,options).handedOff,false);
const invalid=core.invalidateStabilizationFollowup(first.record,human,options).record;assert.strictEqual(core.beginStabilizationFollowup(invalid,human,options).transitioned,false);assert(core.createStabilizationFollowupRecord(source(),input(),human,options,[invalid]).created);
assert.strictEqual(core.beginStabilizationFollowup({...first.record,followupNotes:"tampered"},human,options).transitioned,false);
for(const [key,value] of Object.entries(core.SAFETY))assert.strictEqual(hand.record[key],value,key);
console.log("phase30PostStartStabilizationFollowupCore.test.js: PASS");
