"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),core=require("../phase26-32-manual-post-registration-post-correction-acceptance-core.js");
const clock={now:()=>new Date("2026-08-04T05:00:00Z")},op=reason=>({performedBy:"human-acceptor",reason,explicitConfirmation:true});
const confirmed={verificationRecordValid:true,verificationStatusValid:true,verificationResultValid:true,targetIdentityConfirmed:true,targetKeyConfirmed:true,registrationReferenceConfirmed:true,executionReferenceConfirmed:true,approvalReferenceConfirmed:true,planReferenceConfirmed:true,hashResultConfirmed:true,versionResultConfirmed:true,expectedChangesConfirmed:true,unexpectedChangesAbsent:true,requiredFieldsConfirmed:true,typeCheckConfirmed:true,formatCheckConfirmed:true,rangeCheckConfirmed:true,consistencyConfirmed:true,relationIntegrityConfirmed:true,duplicateAbsenceConfirmed:true,evidenceConfirmed:true,auditTrailConfirmed:true,rollbackStatusConfirmed:true,abnormalitiesResolved:true,criticalIssuesAbsent:true,safetyFlagsConfirmed:true};
const decision=(o={})=>({postCorrectionVerificationDecisionId:"decision-31",postCorrectionVerificationId:"verification-30",correctionExecutionId:"execution-29",correctionExecutionApprovalId:"approval-28",correctionPlanApprovalId:"approval-27",correctionPlanId:"plan-26",correctionRequestId:"request-25",correctionImpactReviewId:"impact-24",correctionTargetIdentificationId:"target-23",registrationRecordId:"registration-1",acceptanceRecordId:"acceptance-old",importRecordId:"import-1",sourceRecordId:"source-1",raceId:"race-1",targetRecordType:"race_result",targetRecordKey:"race-1",decisionStatus:"ready_for_manual_post_correction_acceptance",decisionResult:"approve_for_manual_post_correction_acceptance",approvedForManualPostCorrectionAcceptance:true,rejectedForManualPostCorrectionAcceptance:false,returnedForReverification:false,returnedForCorrection:false,rollbackRequired:false,additionalEvidenceRequired:false,additionalReviewRequired:false,holdRequired:false,abnormalityDetected:false,criticalIssueDetected:false,unresolvedIssueCount:0,currentTargetHash:"current-hash",currentTargetVersion:"v2",recordVersion:4,rollbackStatus:"not_required",auditTrail:[{event:"approved",performedBy:"Decider",performedAt:"2026-08-04T04:00:00Z"}],warningDetected:false,protectedMode:true,planOnly:true,privateLocalOnly:true,automaticCorrectionAllowed:false,automaticExecutionAllowed:false,automaticVerificationAllowed:false,automaticDecisionAllowed:false,automaticApprovalAllowed:false,automaticAcceptanceAllowed:false,automaticApplicationAllowed:false,automaticLearningAllowed:false,publicReleaseAllowed:false,externalTransmissionAllowed:false,sourceDataMutated:false,registeredDataMutated:false,appliedToPrediction:false,appliedToLearning:false,sentExternally:false,...confirmed,...o});
const refs=(o={})=>({postCorrectionVerificationDecisionId:"decision-31",phase2630VerificationValid:true,phase2629ExecutionValid:true,phase2628ApprovalValid:true,phase2627PlanApprovalValid:true,phase2626PlanExists:true,registrationRecordId:"registration-1",targetRecordKey:"race-1",decisionSnapshotHash:"decision-hash",decisionVersion:"4",...o});
const input=(o={})=>({recordedBy:"recorder",acceptanceEnvironment:"Private Local",acceptanceDevice:"local-pc",acceptanceLocation:"local",acceptanceMethod:"manual final review",acceptanceReference:"acceptance-sheet",decisionSnapshot:{decisionResult:"approve_for_manual_post_correction_acceptance"},verificationSnapshot:{verificationResult:"verified"},executionSnapshot:{executionResult:"completed"},approvalSnapshot:{approvalStatus:"approved"},planSnapshot:{correctionPlanId:"plan-26"},registrationSnapshot:{registrationRecordId:"registration-1"},currentTargetSnapshot:{finishTime:"1:34.8"},decisionSnapshotHash:"decision-hash",verificationSnapshotHash:"verification-hash",executionSnapshotHash:"execution-hash",approvalSnapshotHash:"approval-hash",planSnapshotHash:"plan-hash",registrationSnapshotHash:"registration-hash",currentTargetHash:"current-hash",decisionVersion:"4",verificationVersion:"3",executionVersion:"2",registrationVersion:"1",currentTargetVersion:"v2",...o});
function create(){core.resetRegistry();const x=core.createManualPostCorrectionAcceptance(decision(),refs(),input(),op("create"),clock);assert(x.created,x.reasons);return x.record}
function inProgress(){let r=create(),x=core.startManualAcceptance(r,{manualStartConfirmation:true,acceptedBy:"Acceptor"},op("start"),clock);assert(x.transitioned,x.reasons);x=core.recordManualAcceptanceProgress(x.record,{acceptanceNote:"reviewing"},op("progress"),clock);assert(x.transitioned,x.reasons);return x.record}
const resultInput=(o={})=>({acceptanceReason:"all records confirmed",acceptanceSummary:"manual acceptance",nextAction:"manage accepted correction",warningsReviewed:true,existingAcceptanceRecords:[],references:{phase2630VerificationValid:true,phase2629ExecutionValid:true,phase2628ApprovalValid:true,phase2627PlanApprovalValid:true,phase2626PlanExists:true,registrationRecordId:"registration-1",targetRecordKey:"race-1"},...o});
let d=decision(),gate=core.validateAcceptanceEligibility(d,refs(),[]);assert(gate.eligible,gate.reasons);assert.strictEqual(core.extractEligibleAcceptanceCandidates([d],[refs()],[]).length,1);
for(const bad of[decision({decisionStatus:"decision_approved"}),decision({decisionResult:"reject"}),decision({approvedForManualPostCorrectionAcceptance:false}),decision({abnormalityDetected:true}),decision({criticalIssueDetected:true}),decision({unresolvedIssueCount:1}),decision({hashResultConfirmed:false}),decision({versionResultConfirmed:false}),decision({automaticAcceptanceAllowed:true}),decision({automaticApplicationAllowed:true}),decision({automaticLearningAllowed:true}),decision({publicReleaseAllowed:true}),decision({externalTransmissionAllowed:true})])assert(!core.validateAcceptanceEligibility(bad,refs(),[]).eligible);
assert(!core.validateAcceptanceEligibility(d,refs({targetRecordKey:"other"}),[]).eligible);assert(!core.validateAcceptanceEligibility(d,refs(),[{postCorrectionVerificationDecisionId:"decision-31",invalidatedAt:""}]).eligible);
let r=create();assert.strictEqual(r.acceptanceStatus,"awaiting_manual_acceptance");let x=core.startManualAcceptance(r,{manualStartConfirmation:true,acceptedBy:"Acceptor"},op("start"),clock);assert(x.transitioned);x=core.recordManualAcceptanceProgress(x.record,{},op("progress"),clock);assert(x.transitioned);let paused=core.pauseManualAcceptance(x.record,"pause",op("pause"),clock);assert(paused.transitioned);let resumed=core.resumeManualAcceptance(paused.record,{manualResumeConfirmation:true},op("resume"),clock);assert(resumed.transitioned);
r=resumed.record;x=core.acceptAcceptance(r,d,resultInput(),op("accept"),clock);assert(x.completed,x.reasons);assert.strictEqual(x.record.acceptanceStatus,"acceptance_accepted");assert(x.record.accepted);let candidate=core.createAcceptanceManagementCandidate(x.record,op("handoff"),clock);assert(candidate.created,candidate.reasons);assert(candidate.candidate.readyForManualPostCorrectionAcceptanceManagement);assert.strictEqual(candidate.record.acceptanceStatus,"ready_for_manual_post_correction_acceptance_management");assert(!core.transition(candidate.record,"manual_acceptance_in_progress",op("overwrite"),clock).transitioned);
r=inProgress();const conditional=resultInput({acceptanceConditions:["confirm archive"],outstandingItems:["archive evidence"],followUpRequired:true,nextAction:"track conditions",nextActionReason:"condition management",conditionConfirmationDueAt:"2026-08-10T00:00:00Z",conditionOwner:"Owner",outstandingItemSeverity:"low",rollbackRequired:false,reverificationRequired:false,redecisionRequired:false});x=core.conditionallyAccept(r,d,conditional,op("conditional"),clock);assert(x.completed,x.reasons);assert.strictEqual(x.record.acceptanceStatus,"acceptance_conditionally_accepted");assert(core.createAcceptanceManagementCandidate(x.record,op("conditional handoff"),clock).created);
r=inProgress();assert(!core.conditionallyAccept(r,d,resultInput(),op("invalid conditional"),clock).completed);
for(const [fn,result,state] of[["rejectAcceptance","reject","acceptance_rejected"],["returnForReverification","return_for_reverification","acceptance_returned_for_reverification"],["returnForCorrection","return_for_correction","acceptance_returned_for_correction"],["returnForRedecision","return_for_redecision","acceptance_returned_for_redecision"],["holdAcceptance","hold","acceptance_on_hold"],["requireRollback","rollback_required","rollback_required"],["requireAdditionalEvidence","additional_evidence_required","additional_evidence_required"],["requireAdditionalReview","additional_review_required","additional_review_required"]]){r=inProgress();x=core[fn](r,d,resultInput({nextAction:result}),op(result),clock);assert(x.completed,x.reasons);assert.strictEqual(x.record.acceptanceStatus,state);assert.strictEqual(x.record.acceptanceResult,result);assert(!core.createAcceptanceManagementCandidate(x.record,op("blocked"),clock).created)}
r=inProgress();assert(!core.acceptAcceptance(r,d,resultInput({acceptanceReason:""}),op("missing reason"),clock).completed);assert(!core.acceptAcceptance(r,d,resultInput({warningsReviewed:false}),op("warning not reviewed"),clock).completed);assert(!core.acceptAcceptance(r,decision({currentTargetHash:"wrong"}),resultInput(),op("bad hash"),clock).completed);
assert(core.verifyDecisionIntegrity(d,resultInput().references).allValid);assert(core.confirmHashes(d,input()).valid);assert(core.confirmVersions(d,input()).valid);
const memory={value:null,setItem(k,val){this.value=val},getItem(){return this.value}};r=create();assert(core.saveRecords(memory,[r]).saved);assert(core.loadRecords(memory).loaded);memory.value=JSON.stringify({schemaVersion:"old",records:[]});assert(!core.loadRecords(memory).loaded);
assert(core.SAFETY.privateLocalOnly&&core.SAFETY.planOnly&&core.SAFETY.protectedMode);for(const k of["automaticCorrectionAllowed","automaticExecutionAllowed","automaticVerificationAllowed","automaticDecisionAllowed","automaticApprovalAllowed","automaticAcceptanceAllowed","automaticApplicationAllowed","automaticLearningAllowed","publicReleaseAllowed","externalTransmissionAllowed","sourceDataMutated","registeredDataMutated","appliedToPrediction","appliedToLearning","sentExternally","githubPagesEnabled","nextPhaseAutomaticallyStarted"])assert.strictEqual(core.SAFETY[k],false,k);
const root=path.join(__dirname,".."),html=fs.readFileSync(path.join(root,"private-local.html"),"utf8"),css=fs.readFileSync(path.join(root,"dashboard.css"),"utf8"),readme=fs.readFileSync(path.join(root,"README.md"),"utf8"),source=fs.readFileSync(path.join(root,"phase26-32-manual-post-registration-post-correction-acceptance-core.js"),"utf8");for(const text of["phase26-32-manual-post-registration-post-correction-acceptance","対象判定記録","対象修正後検証記録","対象修正実行記録","対象正式登録記録","受入状態","受入者","受入日時","判定結果","検証結果","hash結果","version結果","差分結果","整合性結果","証跡","監査証跡","ロールバック状態","異常・警告","受入結果","受入理由","受入条件","未完了項目","次アクション","次工程移行可否","Private Local only","PLAN_ONLY","protectedMode","自動受入なし","自動反映なし","自動適用なし","自動学習更新なし","Public公開なし","外部送信なし"])assert(html.includes(text),text);assert(css.includes(".phase2632-panel")&&readme.includes("Phase26-32 Manual Post-Correction Acceptance Core"));for(const p of[/fetch\s*\(/,/XMLHttpRequest/,/WebSocket\s*\(/,/automaticAcceptanceAllowed:\s*true/,/automaticApplicationAllowed:\s*true/,/automaticLearningAllowed:\s*true/,/registeredDataMutated:\s*true/])assert(!p.test(source));
console.log("phase26ManualPostRegistrationPostCorrectionAcceptanceCore.test.js: PASS");
