const assert = require("assert");
const fs = require("fs");
const path = require("path");
const core = require("../phase22-25-manual-operation-start-execution-record-core.js");
function memoryStorage(initial = {}) { const data = { ...initial }; return { getItem(key) { return Object.prototype.hasOwnProperty.call(data, key) ? data[key] : null; }, setItem(key, value) { data[key] = String(value); } }; }
function source(overrides = {}) { return { approvalRecordId: "approval-1", sourceReadinessRecordId: "ready-1", sourceDecisionRecordId: "decision-1", registeredTrialId: "trial-1", targetName: "Limited Trial", targetScope: "local scope", status: "manual_start_approved", finalApproval: "manual_start_approved", details: { approver: "Approver", approvalConditions: "manual only", approvalExpiresAt: "2026-07-20T12:00:00" }, updatedAt: "2026-07-19T09:00:00", ...overrides }; }
const sourceStore = { schemaVersion: 1, savedAt: "2026-07-19T09:00:00Z", records: [source(), source({ approvalRecordId: "pending", status: "approval_reviewing", finalApproval: "" }), source({ approvalRecordId: "rejected", status: "approval_rejected", finalApproval: "approval_rejected" })] };
const audit = (reason = "manual record", historyId) => ({ operator: "Operator", occurredAt: "2026-07-19T10:00:00", reason, notes: "human external action", now: "2026-07-19T12:00:00", historyId });
const started = () => ({ executor: "Operator", startedAt: "2026-07-19T10:00:00", startTarget: "Limited Trial", methodSummary: "external manual operation", confirmer: "Reviewer", confirmedAt: "2026-07-19T10:01:00", startResult: "success", finalCheckMemo: "conditions checked", evidence: "screen memo", manualExternalOperationConfirmed: true });
assert.strictEqual(core.STORAGE_KEY, "hashimotoKeibaAi.phase22.manualOperationStartExecutionRecord.v1"); assert.strictEqual(core.eligibleSources(sourceStore).length, 1); assert.strictEqual(core.normalizeStore({}, { ...sourceStore, records: [source(), source()] }).records.length, 1, "duplicate source prevented");
let record = core.normalizeStore({}, sourceStore).records[0]; assert.strictEqual(record.status, "awaiting_manual_execution"); assert.strictEqual(record.statusLabel, "手動実施待ち"); assert.ok(core.isSafetyValid(record.safety));
assert.strictEqual(core.transition(record, "manually_started", { ...started(), executor: "" }, audit()).reason, "required_fields_incomplete"); assert.strictEqual(core.transition(record, "manually_started", { ...started(), startedAt: "" }, audit()).reason, "required_fields_incomplete"); assert.strictEqual(core.transition(record, "manually_started", { ...started(), manualExternalOperationConfirmed: false }, audit()).reason, "required_fields_incomplete"); assert.strictEqual(core.transition(record, "manually_started", started(), { ...audit(), occurredAt: "2026-07-20T10:00:00", now: "2026-07-19T12:00:00" }).reason, "future_datetime");
let result = core.transition(record, "execution_recording", {}, audit("human began recording", "history-1")); assert.ok(result.transitioned); record = result.record; assert.strictEqual(record.history.length, 1);
result = core.transition(record, "start_failed", { executor: "Operator", failedAt: "2026-07-19T10:05:00", failureReason: "device error", errorDetails: "E1", retryAllowed: true, responsePlan: "manual retry", confirmer: "Reviewer", confirmedAt: "2026-07-19T10:06:00", notes: "failed" }, { ...audit("device error"), occurredAt: "2026-07-19T10:05:00", historyId: "history-2" }); assert.ok(result.transitioned); record = result.record; assert.strictEqual(record.failureInfo.failureReason, "device error");
assert.strictEqual(core.transition(record, "execution_recording", {}, { ...audit("retry"), historyId: "history-2" }).reason, "duplicate_history"); result = core.transition(record, "execution_recording", {}, { ...audit("human retry"), occurredAt: "2026-07-19T10:10:00", historyId: "history-3" }); assert.ok(result.transitioned); record = result.record;
result = core.transition(record, "manually_started", started(), { ...audit("manual start success"), historyId: "history-4" }); assert.ok(result.transitioned); record = result.record; assert.strictEqual(record.startInfo.executor, "Operator"); assert.strictEqual(record.status, "manually_started");
result = core.transition(record, "paused", { executor: "Operator", pausedAt: "2026-07-19T10:20:00", pauseReason: "human safety check", confirmer: "Reviewer", confirmedAt: "2026-07-19T10:21:00", resumeConditions: "recheck safe", notes: "paused" }, { ...audit("human safety check"), occurredAt: "2026-07-19T10:20:00", historyId: "history-5" }); assert.ok(result.transitioned); record = result.record;
assert.strictEqual(core.transition(record, "manually_started", { executor: "Operator", resumedAt: "x", resumeReason: "resume", confirmer: "Reviewer", confirmedAt: "x", manualExternalOperationConfirmed: true }, audit()).reason, "required_fields_incomplete"); result = core.transition(record, "manually_started", { executor: "Operator", resumedAt: "2026-07-19T10:30:00", resumeReason: "human resumed", confirmer: "Reviewer", confirmedAt: "2026-07-19T10:31:00", preResumeCheckMemo: "safe", startResult: "resumed", manualExternalOperationConfirmed: true }, { ...audit("human resumed"), occurredAt: "2026-07-19T10:30:00", historyId: "history-6" }); assert.ok(result.transitioned); record = result.record; assert.strictEqual(record.resumeInfo.resumeReason, "human resumed");
assert.strictEqual(core.transition(record, "start_failed", {}, audit()).reason, "invalid_transition"); result = core.transition(record, "stopped", { executor: "Operator", stoppedAt: "2026-07-19T11:00:00", stopReason: "human stop", confirmer: "Reviewer", confirmedAt: "2026-07-19T11:01:00", stopResult: "safe stop", notes: "done" }, { ...audit("human stop"), occurredAt: "2026-07-19T11:00:00", historyId: "history-7" }); assert.ok(result.transitioned); record = result.record; assert.strictEqual(core.transition(record, "manually_started", started(), audit()).reason, "terminal_locked");
for (const terminal of ["cancelled", "expired"]) { let candidate = core.normalizeStore({}, sourceStore).records[0]; const payload = terminal === "cancelled" ? { executor: "Operator", cancelledAt: "2026-07-19T10:00:00", cancelReason: "human cancel", confirmer: "Reviewer", confirmedAt: "2026-07-19T10:01:00" } : { decider: "Operator", expiredAt: "2026-07-20T12:00:00", expiryReason: "approval expired", decisionMethod: "human review" }; const terminalResult = core.transition(candidate, terminal, payload, { ...audit(terminal), occurredAt: payload.cancelledAt || payload.expiredAt, now: "2026-07-21T00:00:00" }); assert.ok(terminalResult.transitioned, terminal); assert.strictEqual(core.transition(terminalResult.record, "execution_recording", {}, audit()).reason, "terminal_locked"); }
const storage = memoryStorage({ [core.SOURCE_STORAGE_KEY]: JSON.stringify(sourceStore) }), sourceBefore = storage.getItem(core.SOURCE_STORAGE_KEY); assert.ok(core.saveStore({ records: [record] }, storage, "2026-07-19T12:00:00Z").saved); assert.strictEqual(storage.getItem(core.SOURCE_STORAGE_KEY), sourceBefore); const restored = core.loadStore(storage, sourceStore).store.records[0]; assert.strictEqual(restored.history.length, 7); assert.strictEqual(restored.status, "stopped"); assert.ok(core.loadSource(memoryStorage({ [core.SOURCE_STORAGE_KEY]: "{bad" })).parseError); assert.strictEqual(core.loadSource(memoryStorage({ [core.SOURCE_STORAGE_KEY]: "{bad" })).sourceStore.records.length, 0); assert.ok(core.loadStore(memoryStorage({ [core.STORAGE_KEY]: "{bad" }), sourceStore).rejected); const auditText = core.buildAuditText(record); assert.ok(auditText.includes("automaticStart=false")); assert.ok(auditText.includes("history-7"));
const root = path.join(__dirname, ".."); const read = (file) => fs.readFileSync(path.join(root, file), "utf8"); const index = read("index.html"), local = read("private-local.html"), css = read("dashboard.css"), readme = read("README.md"); assert.ok(index.includes('id="phase22-manual-operation-start-execution-core"')); assert.ok(index.indexOf('id="phase22-manual-operation-start-approval-core"') < index.indexOf('id="phase22-manual-operation-start-execution-core"')); assert.ok(local.indexOf('href="index.html#phase22-manual-operation-start-approval-core"') < local.indexOf('href="index.html#phase22-manual-operation-start-execution-core"')); assert.ok(index.indexOf("phase22-24-manual-operation-start-approval-record-core.js") < index.indexOf("phase22-25-manual-operation-start-execution-record-core.js")); assert.ok(css.includes(".phase2225-execution-panel")); assert.ok(readme.includes(core.STORAGE_KEY));
for (const htmlFile of ["index.html", "private-local.html", "phase22-22-private-local.html"]) { const html = read(htmlFile); const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map((match) => match[1]); assert.strictEqual(new Set(ids).size, ids.length); for (const match of html.matchAll(/<script[^>]+src="([^"]+)"/g)) if (!/^(?:https?:)?\/\//.test(match[1])) assert.ok(fs.existsSync(path.join(root, match[1]))); }
const safe = core.safety(); ["privateLocal", "planOnly", "protectedMode", "humanExternalOperationRecordOnly"].forEach((key) => assert.strictEqual(safe[key], true)); ["automaticStart", "automaticRecovery", "automaticTransition", "automaticApply", "automaticPurchase", "automaticStop", "automaticCancel", "automaticResume", "automaticRelease", "automaticLearning", "externalApi", "productionMutation", "sourceMutation", "publicUrl", "githubPages"].forEach((key) => assert.strictEqual(safe[key], false));
console.log("Phase22-25 manual operation start execution record core tests passed");
