"use strict";
const assert=require("assert"),fs=require("fs"),vm=require("vm"),core=require("../phase28-3-external-data-category-definition-core.js"),p282=core.PHASE282_REFERENCE,p281=p282.PHASE281_REFERENCE,NOW="2027-01-01T00:00:00Z",options={now:()=>new Date(NOW)},human={performedBy:"human",reason:"manual",explicitConfirmation:true,performedAt:NOW};
function source(p={}){const base={phase28Phase27CompletionAcceptanceId:"phase28-acceptance-1",phase28Phase27CompletionAcceptanceStatus:"ready_for_manual_phase28_external_data_category_definition",phase28Phase27CompletionAcceptanceResult:"accept_phase27_completion_for_phase28",expiresAt:"2027-12-01T00:00:00Z",recordVersion:4,auditTrail:[{action:"handoff"}],correctionRequired:false,rollbackRequired:false,recoveryRequired:false,criticalIssues:[],blockingConditions:[],...p282.SAFETY};p282.REFERENCE_IDS.forEach(k=>base[k]=`${k}-1`);p282.ZERO_COUNTS.forEach(k=>base[k]=0);const snapshot={...base};return{...base,phase28Phase27CompletionAcceptanceSnapshot:snapshot,phase28Phase27CompletionAcceptanceSnapshotHash:p282.computeSnapshotHash(snapshot),phase28Phase27CompletionAcceptanceVersion:p282.SCHEMA_VERSION,...p}}
function input(p={}){return{definedBy:"definer",responsiblePerson:"owner",confirmedBy:"confirmer",definitionReason:"classify",definitionScope:"Phase28",definitionTarget:"external categories",rollbackPoint:"before",recoveryPoint:"snapshot",gitEvidence:{safe:true},testEvidence:{pass:true},stateEvidence:{stable:true},safetyEvidence:{intact:true},expiresAt:"2027-11-01T00:00:00Z",...p}}
function category(code,i){const c={};for(const key of core.CATEGORY_FIELDS)c[key]=key.endsWith("Required")||key.endsWith("Candidate")?true:["dataFields","requiredFields","optionalFields","identifierFields","timeFields","sourceCandidateTypes"].includes(key)?[`${code}_${key}`]:`${code}_${key}`;return{...c,categoryId:`category-${i}`,categoryCode:code,categoryName:code}}
const categories=core.REQUIRED_CATEGORIES.map(category);function create(){const x=core.createExternalDataCategoryDefinitionRecord(source(),input(),human,options,[]);assert(x.created,x.reasons.join());return x.record}function progress(){let r=create();r=core.startExternalDataCategoryDefinition(r,human,options).record;return core.progressExternalDataCategoryDefinition(r,human,options).record}function defined(p={}){return{result:"external_data_categories_defined",categories,definitionAfterSnapshot:{defined:true},correctionRequired:false,rollbackRequired:false,recoveryRequired:false,criticalIssues:[],blockingConditions:[],...p}}
assert(core.PHASE282_REFERENCE);assert.strictEqual(core.CURRENT_STAGE,"external_data_category_definition");assert.strictEqual(core.NEXT_STAGE,"source_candidate_registration");assert(p281.PHASE28_STAGES.includes(core.CURRENT_STAGE)&&p281.PHASE28_STAGES.includes(core.NEXT_STAGE));assert.strictEqual(core.extractExternalDataCategoryDefinitionCandidates([source()],[]).length,1);
for(const p of [{phase28Phase27CompletionAcceptanceStatus:"bad"},{phase28Phase27CompletionAcceptanceResult:"bad"},{invalidatedAt:NOW},{expiredAt:NOW},{phase28Phase27CompletionAcceptanceSnapshot:null},{phase28Phase27CompletionAcceptanceSnapshotHash:"bad"},{phase28Phase27CompletionAcceptanceVersion:"bad"},{auditTrail:[]},{recordVersion:0},{protectedMode:false},{criticalIssues:["x"]},{blockingConditions:["x"]},{correctionRequired:true},{rollbackRequired:true},{recoveryRequired:true}])assert.strictEqual(core.validatePhase282Eligibility(source(p)).valid,false,JSON.stringify(p));
assert.strictEqual(core.createExternalDataCategoryDefinitionRecord(source(),input(),{},options,[]).created,false);const src=source(),text=JSON.stringify(src);assert(core.createExternalDataCategoryDefinitionRecord(src,input(),human,options,[]).created);assert.strictEqual(JSON.stringify(src),text);const first=create();assert.strictEqual(core.extractExternalDataCategoryDefinitionCandidates([source()],[first]).length,0);assert.strictEqual(core.createExternalDataCategoryDefinitionRecord(source(),input(),human,options,[first]).created,false);
let r=core.startExternalDataCategoryDefinition(first,human,options).record;r=core.progressExternalDataCategoryDefinition(r,human,options).record;assert(core.pauseExternalDataCategoryDefinition(r,human,options).transitioned);assert(core.resumeExternalDataCategoryDefinition(core.pauseExternalDataCategoryDefinition(r,human,options).record,human,options).transitioned);assert(core.stopExternalDataCategoryDefinition(r,human,options).transitioned);assert(core.cancelExternalDataCategoryDefinition(r,human,options).transitioned);assert(core.failExternalDataCategoryDefinition(r,human,options).transitioned);assert.strictEqual(core.updateExternalDataCategoryDefinition(first,{},human,options).updated,false);assert(core.updateExternalDataCategoryDefinition(r,{definitionReason:"updated"},human,options).updated);
assert.strictEqual(core.completeExternalDataCategoryDefinition(r,defined({categories:categories.slice(1)}),human,options).completed,false);assert.strictEqual(core.completeExternalDataCategoryDefinition(r,defined({categories:[...categories,{...categories[0],categoryId:"other"}]}),human,options).completed,false);assert.strictEqual(core.completeExternalDataCategoryDefinition(r,defined({categories:categories.map((c,i)=>i?c:{...c,purpose:""})}),human,options).completed,false);
for(const p of [{criticalIssues:["x"]},{blockingConditions:["x"]},{correctionRequired:true},{rollbackRequired:true},{recoveryRequired:true},{gitEvidence:null}])assert.strictEqual(core.completeExternalDataCategoryDefinition(r,defined(p),human,options).completed,false,JSON.stringify(p));
const ok=core.completeExternalDataCategoryDefinition(r,defined(),human,options);assert(ok.completed,ok.reasons.join());assert.strictEqual(ok.record.phase28ExternalDataCategoryDefinitionStatus,"external_data_categories_defined");
const routes=[["external_data_categories_conditionally_defined",{conditions:"c",conditionReason:"r",conditionOwner:"o",conditionDeadline:"2027-03-01",conditionVerificationMethod:"m",conditionReleaseCriteria:"c"}],...["external_data_category_definition_rejected","external_data_category_definition_incomplete","additional_category_review_required","source_scope_review_required","terms_review_required","safety_review_required","correction_plan_required","rollback_plan_required","recovery_plan_required","manual_investigation_required","hold","blocked"].map(x=>[x,{}])];for(const[result,p]of routes)assert(core.completeExternalDataCategoryDefinition(progress(),{result,...p},human,options).completed,result);
assert.strictEqual(core.advanceToSourceCandidateRegistration(ok.record,{},options).advanced,false);const hand=core.advanceToSourceCandidateRegistration(ok.record,human,options);assert(hand.advanced);assert.strictEqual(hand.record.phase28ExternalDataCategoryDefinitionStatus,"ready_for_manual_phase28_source_candidate_registration");for(const k of ["externalDataAcquired","oddsAcquired","resultDataAcquired","raceDataAcquired","networkCommunicationPerformed","automaticExternalAcquisitionPerformed","bettingExecuted","purchaseExecuted","appliedToPrediction","appliedToLearning","phase28AutomaticallyAdvanced"])assert.strictEqual(hand.record[k],false,k);
assert(core.integrityIntact(first));for(const p of [{phase28ExternalDataCategoryDefinitionSnapshot:{tampered:true}},{phase28ExternalDataCategoryDefinitionSnapshotHash:"bad"},{phase28ExternalDataCategoryDefinitionVersion:"bad"}])assert.strictEqual(core.integrityIntact({...first,...p}),false);Object.entries(core.SAFETY).forEach(([k,v])=>assert.strictEqual(first[k],v,k));assert(core.invalidateExternalDataCategoryDefinition(ok.record,human,options).transitioned);assert.strictEqual(core.expireExternalDataCategoryDefinition({...first,expiresAt:"2026-01-01"},{},options).expired,false);assert(core.expireExternalDataCategoryDefinition({...first,expiresAt:"2026-01-01"},human,options).expired);
const mem={v:null,setItem(_k,v){this.v=v},getItem(){return this.v}};assert(core.saveExternalDataCategoryDefinitionRecords(mem,[ok.record]).saved);assert(core.loadExternalDataCategoryDefinitionRecords(mem).loaded);mem.v="{";assert.strictEqual(core.loadExternalDataCategoryDefinitionRecords(mem).loaded,false);
const code=fs.readFileSync(require.resolve("../phase28-3-external-data-category-definition-core.js"),"utf8"),browser={HashimotoPhase282Phase27CompletionAcceptance:p282};vm.runInNewContext(code,browser);assert(browser.HashimotoPhase283ExternalDataCategoryDefinition);assert(code.includes('require("./phase28-2-phase27-completion-acceptance-core.js")'));assert.throws(()=>vm.runInNewContext(code,{}),/Phase28-2/);assert(!/fetch\s*\(|XMLHttpRequest|WebSocket|EventSource|sendBeacon\s*\(|http\.request|https\.request|child_process|execSync|spawnSync|setInterval\s*\(/.test(code));console.log("phase28ExternalDataCategoryDefinitionCore.test.js: PASS");
