"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),p2610=require("../phase26-10-manual-result-data-parse-preview-generation-core.js"),core=require("../phase26-11-manual-result-preview-validation-intake-decision-core.js");
const root=path.resolve(__dirname,".."),clock={now:()=>new Date("2026-08-12T02:00:00Z")},op={performedBy:"owner",reason:"manual confirmation",explicitConfirmation:true};
const originalGetPreview=p2610.getPreview;p2610.getPreview=()=>({headerMetadata:[{columnNumber:1,displayName:"id"}],previewRows:[{rowNumber:1,cells:[{displayValue:"1"}]}]});
const target={parseConfigurationId:"c1",status:"ready_for_manual_result_preview_review",parseExecution:{parseExecutionRecordId:"pe1",success:true},preview:{previewDataId:"pv1",previewStatus:"held"},parseResult:{parsedRowCount:2,dataRowCount:1,parsedColumnCount:1},resultDataRead:true,fileContentAccessed:true,temporaryDataHeld:true,resultDataParsed:true,fileContentParsed:true,resultPreviewCreated:true,temporaryPreviewHeld:true,resultDataStored:false,resultDataImported:false,resultDataApplied:false,resultDataLearned:false,resultPreviewReady:false,intakeReady:false,fileContentStored:false,fileUploaded:false,fileExternallyTransmitted:false,unresolvedIssues:[]};
const accepted={completed:true,humanResult:"accepted",reviewedBy:"owner",reviewedAt:"2026-08-12T01:20:00Z",reason:"manually confirmed",details:{}};
const checks=core.CHECK_DEFINITIONS.map(x=>({...x,status:"passed",checkedBy:"owner",checkedAt:"2026-08-12T01:30:00Z",note:"confirmed"}));
const decision={intakeDecisionId:"d1",decidedBy:"owner",decisionDate:"2026-08-12",decisionTime:"11:00",result:"accepted",reason:"all reviews accepted",conditions:"",expiresAt:"2026-08-13",unresolvedIssues:[],excludedScope:"none",recheckRequired:false,handoffDecision:"approved",note:"manual"};
const input={validationRecordId:"v1",validator:"owner",validationDate:"2026-08-12",validationStartTime:"10:00",validationEndTime:"10:50",validationPurpose:"manual intake validation",validationScope:"all preview metadata",previewRowRange:"1-1",columnRange:"1-1",referencedWarnings:["none"],referencedAnomalies:["none"],validationSummary:"accepted after human review",unresolvedIssues:[],note:"no data changes",requiredColumnDefinitions:[{requiredColumnDefinitionId:"rc1",logicalName:"identifier",expectedName:"id",aliases:[],required:true,uniqueRequired:true,blankAllowed:false,expectedType:"text",expectedFormat:"declared",purpose:"identity",note:""}],requiredStructureReview:accepted,identifierReview:accepted,dateTimeReview:accepted,targetReview:accepted,countReview:{...accepted,result:"exact_match",candidateCount:1,tolerance:"none"},missingReview:accepted,duplicateReview:accepted,anomalyReview:accepted,formulaReview:accepted,provenanceReview:accepted,correctionInstructions:[],returnRecord:{returnTarget:"",reason:"",requiredWork:"",confirmedBy:"",confirmedAt:""},intakeDecision:decision,reviewerSeparation:{samePersonAllowed:true,samePersonUsed:true,separationRequired:false,separationReason:"private local single user",secondReviewer:"",secondReviewResult:"",secondReviewedAt:""},checklist:checks};
assert.strictEqual(core.PHASE2610_REFERENCE,p2610);assert(core.CHECK_DEFINITIONS.length>=60);assert(core.validateTarget(target).valid);
for(const status of["preview_generated","preview_review_preparation","preview_discarded"])assert(!core.validateTarget({...target,status}).valid,status);
assert(!core.validateTarget({...target,preview:{previewDataId:"",previewStatus:"held"}}).valid);assert(!core.validateTarget({...target,preview:{previewDataId:"pv1",previewStatus:"discarded"}}).valid);
for(const k of["validator"])assert(!core.createValidation(target,{...input,[k]:""},op,clock).created,k);
assert(!core.createValidation(target,{...input,requiredColumnDefinitions:[]},op,clock).created);
for(const [name,change]of[["structure",{requiredStructureReview:{...accepted,completed:false}}],["identifier",{identifierReview:{...accepted,completed:false}}],["datetime",{dateTimeReview:{...accepted,completed:false}}],["target",{targetReview:{...accepted,completed:false}}],["count",{countReview:{...accepted,completed:false,result:"exact_match"}}],["missing",{missingReview:{...accepted,completed:false}}],["duplicate",{duplicateReview:{...accepted,completed:false}}],["anomaly",{anomalyReview:{...accepted,completed:false}}],["formula",{formulaReview:{...accepted,completed:false}}],["provenance",{provenanceReview:{...accepted,completed:false}}]])assert(!core.createValidation(target,{...input,...change},op,clock).created,name);
assert(!core.createValidation(target,input,{...op,explicitConfirmation:false},clock).created);
const created=core.createValidation(target,input,op,clock);assert(created.created);assert.equal(created.record.status,"preview_validation_recorded");
const structure=core.transition(created.record,"validating_required_structure",op,target,clock);assert(structure.transitioned);
const consistency=core.transition(structure.record,"validating_content_consistency",op,target,clock);assert(consistency.transitioned);
const recorded=core.transition(consistency.record,"intake_decision_recorded",op,target,clock);assert(recorded.transitioned);
const acceptedState=core.transition(recorded.record,"intake_accepted",op,target,clock);assert(acceptedState.transitioned);
const ready=core.transition(acceptedState.record,"ready_for_manual_formal_import_candidate_creation",op,target,clock);assert(ready.transitioned);assert(ready.record.resultPreviewReady&&ready.record.formalImportCandidatePreparationReady&&ready.record.previewValidationCompleted);
for(const[k,v]of Object.entries(core.ALWAYS_FALSE_FLAGS))assert.strictEqual(ready.record[k],v,k);
for(const status of["failed","unchecked","needs_review"]){const bad=checks.map((x,i)=>i?x:{...x,status});const r=core.normalize({...acceptedState.record,checklist:bad});assert(!core.transition(r,"ready_for_manual_formal_import_candidate_creation",op,target,clock).transitioned,status)}
function decisionRejected(change){const r=core.normalize({...acceptedState.record,intakeDecision:{...decision,...change}});return core.transition(r,"ready_for_manual_formal_import_candidate_creation",op,target,clock)}
for(const [name,change]of[["maker",{decidedBy:""}],["date",{decisionDate:""}],["reason",{reason:""}],["hold",{result:"on_hold"}],["returned",{result:"returned_for_reparse"}],["rejected",{result:"rejected"}],["cancelled",{result:"cancelled"}],["handoff",{handoffDecision:"needs_review"}]])assert(!decisionRejected(change).transitioned,name);
const conditionalRecord=core.normalize({...recorded.record,intakeDecision:{...decision,result:"accepted_with_conditions",conditions:"manual exclusion list"}});const conditional=core.transition(conditionalRecord,"intake_accepted_with_conditions",op,target,clock);assert(conditional.transitioned);assert(core.transition(conditional.record,"ready_for_manual_formal_import_candidate_creation",op,target,clock).transitioned);
assert(!core.transition(core.normalize({...recorded.record,intakeDecision:{...decision,result:"accepted_with_conditions",conditions:""}}),"intake_accepted_with_conditions",op,target,clock).transitioned);
const returnedRecord=core.normalize({...consistency.record,intakeDecision:{...decision,result:"returned_for_reparse"},returnRecord:{returnTarget:"phase26-10",reason:"delimiter review",requiredWork:"manual reparse",confirmedBy:"owner",confirmedAt:"2026-08-12T01:40:00Z"}});assert(core.transition(returnedRecord,"validation_returned_for_reparse",op,target,clock).transitioned);
assert(!core.transition(core.normalize({...returnedRecord,returnRecord:{}}),"validation_returned_for_reparse",op,target,clock).transitioned);
for(const next of["validation_on_hold","validation_rejected","intake_cancelled"]){const base=next==="intake_cancelled"?consistency.record:consistency.record;const result=core.transition(base,next,op,target,clock);assert(result.transitioned,next);assert(!result.record.resultPreviewReady&&!result.record.formalImportCandidatePreparationReady)}
assert(!core.transition(created.record,"ready_for_manual_formal_import_candidate_creation",op,target,clock).transitioned);
const tampered=core.updateRecord(created.record,{resultDataStored:true,automaticAcceptanceEnabled:true},op,clock).record;assert(!tampered.resultDataStored&&!tampered.automaticAcceptanceEnabled);
const source=fs.readFileSync(path.join(root,"phase26-11-manual-result-preview-validation-intake-decision-core.js"),"utf8"),html=fs.readFileSync(path.join(root,"private-local.html"),"utf8"),css=fs.readFileSync(path.join(root,"dashboard.css"),"utf8"),readme=fs.readFileSync(path.join(root,"README.md"),"utf8");
for(const pattern of[/localStorage\s*\.\s*setItem/,/indexedDB\s*\.\s*open/,/fetch\s*\(/,/XMLHttpRequest/,/WebSocket\s*\(/,/innerHTML\s*=/,/eval\s*\(/,/createObjectURL/])assert(!pattern.test(source),pattern);
for(const name of["autoAccept","autoReturn","autoReject","autoTransition","fixData","fillMissing","deleteDuplicates","excludeAnomalies","saveFormal","importFormal","applyData","updateLearning"])assert.strictEqual(core[name],undefined,name);
for(const marker of['id="phase26-11-manual-result-preview-validation-intake-decision"',"対象となるPhase26-10記録","現在状態","previewDataId・プレビュー状態","元ファイル情報","解析設定概要・解析結果概要","ヘッダー一覧・プレビュー表","必須列定義・確認結果","識別子確認結果","日付・時点確認結果","対象整合性確認結果","件数比較結果","欠損候補確認結果","重複候補確認結果","異常行確認結果","Formula Injection候補確認結果","出所・信頼区分確認結果","修正指示欄","差戻し先選択","受入可否判定欄","条件付き受入条件","未解決事項","プレビュー検証チェックリスト","次工程引渡し確認欄","状態遷移履歴","監査履歴","安全フラグ一覧","禁止処理一覧","Private Local only","PLAN_ONLY","protectedMode","正式保存なし","正式取込なし","適用・学習なし"])assert(html.includes(marker),marker);
assert(css.includes(".phase2611-panel"));assert(readme.includes("Phase26-11 Manual Result Preview Validation and Intake Decision Core"));
p2610.getPreview=originalGetPreview;console.log("phase26ManualResultPreviewValidationIntakeDecisionCore.test.js: PASS");
