"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),p2612=require("../phase26-12-formal-import-candidate-pre-import-approval-core.js"),core=require("../phase26-13-manual-formal-import-execution-core.js");
const root=path.resolve(__dirname,".."),clock={now:()=>new Date("2026-08-14T02:03:04Z")},op={performedBy:"owner",reason:"manual explicit import",explicitConfirmation:true};
const target={status:"ready_for_manual_formal_import_execution",candidate:{formalImportCandidateId:"fc1",targetCount:2,excludedCount:1,hasExclusions:true,excludedRowRange:"3",exclusionReason:"human exclusion"},approval:{preImportApprovalId:"pa1",approvedBy:"owner",approvalDate:"2026-08-14",approvalTime:"10:00",decision:"approved",conditions:"",recheckRequired:false},executionPlan:{destination:"formal_results",plannedExecutor:"owner"},formalImportExecutionReady:true,formalImportCompleted:false,resultDataImported:false};
const input={executorId:"u1",executorName:"owner",sourceDataId:"source1",sourceDataName:"results.csv",sourceDataHash:"hash1",destinationType:"private_local_store",confirmationText:core.REQUIRED_CONFIRMATION,executionConfirmed:true,noAutomaticApplicationConfirmed:true,noAutomaticLearningConfirmed:true,noAutomaticRetryConfirmed:true};
const rows=[{sourceRecordId:"s1",sourceRowNumber:1,sourceHash:"rh1",recordKey:"race1-horse1",payload:{id:1}},{sourceRecordId:"s2",sourceRowNumber:2,sourceHash:"rh2",recordKey:"race1-horse2",payload:{id:2}}];
function adapter(failAt=-1,badCount=false){const store=[];return{store,count:async()=>badCount?99:store.length,hasRecord:async(d,key)=>store.some(x=>x.key===key),insert:async(d,p,m)=>{if(store.length===failAt)throw Object.assign(new Error("write failed"),{code:"WRITE_FAILED"});store.push({payload:p,key:m.recordKey});return{destinationRecordId:`dest-${store.length}`}}}}
async function run(){
 core.resetRegistry();assert.strictEqual(core.PHASE2612_REFERENCE,p2612);assert(core.validateTarget(target).valid);assert(!core.validateTarget({...target,status:"pre_import_approval_recorded"}).valid);assert(!core.validateTarget({...target,approval:{}}).valid);
 for(const [name,changed]of[["executor",{executorName:""}],["confirm",{executionConfirmed:false}],["phrase",{confirmationText:"wrong"}],["apply",{noAutomaticApplicationConfirmed:false}],["learn",{noAutomaticLearningConfirmed:false}],["retry",{noAutomaticRetryConfirmed:false}],["source",{sourceDataHash:""}]]){core.resetRegistry();const x=await core.executeManualImport(target,{...input,...changed},rows,adapter(),op,clock);assert(!x.started,name)}
 core.resetRegistry();const a=adapter(),ok=await core.executeManualImport(target,input,rows,a,op,clock);assert(ok.started&&ok.succeeded);assert(/^manual-formal-import-batch-20260814020304-\d{5}$/.test(ok.record.importBatchId));assert.equal(ok.record.importTargetCountBeforeExecution,0);assert.equal(ok.record.plannedImportCount,2);assert.equal(ok.record.attemptedImportCount,2);assert.equal(ok.record.successfullyImportedCount,2);assert.equal(ok.record.failedImportCount,0);assert.equal(ok.record.skippedImportCount,0);assert.equal(ok.record.importTargetCountAfterExecution,2);assert.equal(ok.record.status,"ready_for_manual_post_import_verification");assert.equal(ok.record.recordMappings.length,2);assert(ok.record.recordMappings.every(x=>x.destinationRecordId&&x.verificationStatus==="pending"));for(const[k,v]of Object.entries(core.SAFETY))assert.strictEqual(ok.record[k],v,k);
 const duplicateCandidate=await core.executeManualImport(target,{...input,sourceDataHash:"hash2"},rows,adapter(),op,clock);assert(!duplicateCandidate.started);assert(duplicateCandidate.reasons.some(x=>x.includes("candidateId")));
 core.resetRegistry();await core.executeManualImport(target,input,rows,adapter(),op,clock);const duplicateHash=await core.executeManualImport({...target,candidate:{...target.candidate,formalImportCandidateId:"fc2"}},input,rows.map((x,i)=>({...x,recordKey:`other${i}`})),adapter(),op,clock);assert(!duplicateHash.started);assert(duplicateHash.reasons.some(x=>x.includes("ハッシュ")));
 core.resetRegistry();await core.executeManualImport(target,input,rows,adapter(),op,clock);const duplicateKey=await core.executeManualImport({...target,candidate:{...target.candidate,formalImportCandidateId:"fc2"}},{...input,sourceDataId:"source2",sourceDataHash:"hash2"},rows,adapter(),op,clock);assert(!duplicateKey.started);assert(duplicateKey.reasons.some(x=>x.includes("レコード識別子")));
 core.resetRegistry();const part=await core.executeManualImport(target,input,rows,adapter(1),op,clock);assert(part.started&&!part.succeeded&&part.partial);assert.equal(part.record.status,"rollback_candidate_created");assert.equal(part.record.successfullyImportedCount,1);assert.equal(part.record.failedImportCount,1);assert(part.record.rollbackCandidate&&part.record.rollbackCandidate.automaticExecutionProhibited);assert.equal(part.record.attemptedImportCount,2);const partReplay=await core.executeManualImport(target,{...input,sourceDataHash:"hash-part-replay"},rows.map((x,i)=>({...x,recordKey:`part-replay-${i}`})),adapter(),op,clock);assert(!partReplay.started);assert(partReplay.reasons.some(x=>x.includes("candidateId")));
 core.resetRegistry();const fail=await core.executeManualImport(target,input,rows,adapter(0),op,clock);assert(!fail.succeeded);assert.equal(fail.record.status,"manual_formal_import_execution_failed");assert.equal(fail.record.successfullyImportedCount,0);assert.equal(fail.record.failedImportCount,1);
 core.resetRegistry();const inconsistent=await core.executeManualImport(target,input,rows,adapter(-1,true),op,clock);assert(!inconsistent.succeeded);assert.equal(inconsistent.record.integrityResult,"counts_inconsistent");assert.notEqual(inconsistent.record.status,"ready_for_manual_post_import_verification");
 core.resetRegistry();const interruptedAdapter=adapter();interruptedAdapter.count=async()=>{throw new Error("count interrupted")};const interrupted=await core.executeManualImport(target,input,rows,interruptedAdapter,op,clock);assert(interrupted.started&&!interrupted.succeeded);assert.equal(interrupted.record.status,"manual_formal_import_execution_interrupted");assert(interrupted.record.interruptionReason.includes("count interrupted"));assert.strictEqual(interrupted.record.automaticRetryPerformed,false);
 core.resetRegistry();const cancelled=core.cancelBeforeExecution(target,{...input,reason:"human cancel"},op,clock);assert(cancelled.cancelled);assert.equal(cancelled.record.status,"manual_formal_import_execution_cancelled");assert.equal(cancelled.record.cancellationReason,"human cancel");
 assert(!core.transition({status:"manual_formal_import_execution_failed",stateHistory:[]},"ready_for_manual_post_import_verification",op,clock).transitioned);
 const source=fs.readFileSync(path.join(root,"phase26-13-manual-formal-import-execution-core.js"),"utf8"),html=fs.readFileSync(path.join(root,"private-local.html"),"utf8"),css=fs.readFileSync(path.join(root,"dashboard.css"),"utf8"),readme=fs.readFileSync(path.join(root,"README.md"),"utf8");
 for(const pattern of[/fetch\s*\(/,/XMLHttpRequest/,/WebSocket\s*\(/,/setInterval\s*\(/,/localStorage\s*\.\s*setItem/,/automaticRetryPerformed:\s*true/,/automaticApplicationPerformed:\s*true/,/automaticLearningUpdatePerformed:\s*true/,/automaticRollbackPerformed:\s*true/])assert(!pattern.test(source),pattern);
 for(const marker of['id="phase26-13-manual-formal-import-execution"',"Private Local only","PLAN_ONLY","protectedMode","Phase26-12承認済み候補一覧","正式インポート対象詳細","実行前再確認","実行者名またはID","手動正式インポートを実行","実行中ステータス","取込件数表示","成功・部分成功・失敗・中断・取消","元データと取込結果の対応一覧","二重取込防止結果","ロールバック候補表示","実行証跡一覧","次状態"])assert(html.includes(marker),marker);
 assert(css.includes(".phase2613-panel"));assert(readme.includes("Phase26-13 Manual Formal Import Execution Core"));console.log("phase26ManualFormalImportExecutionCore.test.js: PASS");
}
run().catch(e=>{console.error(e);process.exitCode=1});
