const assert = require("assert"), fs = require("fs"), path = require("path");
const core = require("../phase23-3-approved-preview-staging-storage-core.js");
const root = path.join(__dirname, ".."), read = (f) => fs.readFileSync(path.join(root, f), "utf8");
function memoryStorage(initial = {}, fail = false) { const data = { ...initial }; return { getItem(k) { return Object.prototype.hasOwnProperty.call(data, k) ? data[k] : null; }, setItem(k,v) { if (fail) throw new Error("quota"); data[k]=String(v); }, removeItem(k) { delete data[k]; }, data }; }
const source = (overrides = {}) => ({ sourceValidationId:"p232-v1", state:"preview_ready", file:{name:"runners.csv",size:100,hash:"hash-a",format:"csv",encoding:"utf-8"}, dataType:"runner", providerId:"manual_csv", summary:{totalRecords:2,validCount:2,warningCount:1,errorCount:0,fatalCount:0,duplicateCount:0}, normalizedRecords:[{raceId:"r1",horseNumber:1,horseName:"A"},{raceId:"r1",horseNumber:2,horseName:"B"}], unknownFields:["memo"], mappingSummary:{馬番:"horseNumber"}, humanConfirmed:true, protectedMode:true, PLAN_ONLY:true, privateLocalOnly:true, phase22NotAppliedConfirmed:true, ...overrides });
const approval = (overrides = {}) => ({ humanConfirmed:true,approvedBy:"Approver",approvedAt:"2026-07-19T10:00:00+09:00",approvalReason:"human checked",exceptionApproval:false,exceptionReason:"",phase22NotAppliedConfirmed:true,stagedBy:"Operator",...overrides });

assert.strictEqual(core.SOURCE_STORAGE_KEY,"hashimotoKeibaAi.phase23.manualCsvJsonImportPreviewValidation.v1"); assert.strictEqual(core.STORAGE_KEY,"hashimotoKeibaAi.phase23.approvedPreviewStagingStorage.v1");
assert.strictEqual(core.normalizeSource(source()).state,"preview_ready");
for (const [change, expected] of [[{summary:{...source().summary,fatalCount:1}},"fatal_present"],[{state:"validating"},"source_not_preview_ready"],[{dataType:""},"data_type_required"],[{sourceValidationId:""},"source_validation_id_required"],[{file:{...source().file,hash:"",hashUnavailableReason:""}},"file_hash_or_reason_required"],[{summary:{...source().summary,totalRecords:0}},"records_required"],[{normalizedRecords:[]},"normalized_records_required"],[{humanConfirmed:false},"human_confirmation_required"],[{protectedMode:false},"protected_mode_required"],[{PLAN_ONLY:false},"plan_only_required"],[{privateLocalOnly:false},"private_local_required"]]) assert.ok(core.approvalProblems(source(change),approval()).includes(expected),expected);
assert.ok(core.approvalProblems(source(),approval({humanConfirmed:false})).includes("human_confirmation_required")); assert.ok(core.approvalProblems(source(),approval({approvedBy:""})).includes("approver_required")); assert.ok(core.approvalProblems(source(),approval({approvalReason:""})).includes("approval_reason_required")); assert.ok(core.approvalProblems(source(),approval({approvedAt:"2099-01-01T00:00:00+09:00"})).includes("approval_datetime_future")); assert.ok(core.approvalProblems(source(),approval({phase22NotAppliedConfirmed:false})).includes("phase22_non_application_confirmation_required"));
assert.ok(core.canApprove(source(),approval()).allowed); assert.ok(core.canApprove(source({summary:{...source().summary,warningCount:3}}),approval()).allowed); assert.ok(!core.canApprove(source({summary:{...source().summary,errorCount:1}}),approval()).allowed); assert.ok(core.canApprove(source({summary:{...source().summary,errorCount:1}}),approval({exceptionApproval:true,exceptionReason:"human exception"})).allowed);
assert.ok(core.generateStagingId(source(),new Date("2026-07-19T01:00:00Z")).startsWith("p233-runner-")); assert.strictEqual(core.nextVersion([],source()),1); assert.strictEqual(core.nextVersion([{sourceValidationId:"p232-v1",version:2}],source()),3);
let built=core.buildRecord(source(),approval(),[],new Date("2026-07-19T01:00:00Z")); assert.ok(built.created); let record=built.record; assert.strictEqual(record.phase22Applied,false); assert.strictEqual(record.phase22AppliedAt,null); assert.strictEqual(record.stagingStatus,"staging_ready"); assert.strictEqual(record.version,1); assert.strictEqual(record.normalizedRecords.length,2); assert.ok(record.recordsSummaryHash);
assert.strictEqual(typeof core.setPhase22Applied,"undefined");
const dangerous=core.stripDangerous({apiKey:"x",COOKIE:"x",AccessToken:"x",refreshTOKEN:"x",authorization:"x",account:"x",loginId:"x",rawFileContent:"body",nested:{password:"x",safe:1}}); for(const key of ["apiKey","COOKIE","AccessToken","refreshTOKEN","authorization","account","loginId","rawFileContent"]) assert.ok(!Object.prototype.hasOwnProperty.call(dangerous,key),key); assert.strictEqual(dangerous.nested.safe,1); assert.ok(!Object.prototype.hasOwnProperty.call(dangerous.nested,"password"));
assert.ok(core.estimateBytes(record)>0); assert.ok(core.canStore(record,core.defaultStore()).allowed); assert.ok(!core.canStore({...record,normalizedRecords:[{x:"x".repeat(core.MAX_STAGING_BYTES)}]},core.defaultStore()).allowed);
const exact=core.detectDuplicate({...record,stagingId:"new"},[{...record,stagingId:"old"}]); assert.strictEqual(exact.status,"exact_duplicate");
const possibleCandidate={...record,stagingId:"new",sourceFileHash:"hash-b",recordsSummaryHash:"different",normalizedRecords:[{raceId:"r2",horseNumber:1}],sourceFileName:record.sourceFileName}; assert.strictEqual(core.detectDuplicate(possibleCandidate,[record]).status,"possible_duplicate");
const conflictCandidate={...record,stagingId:"new",sourceFileHash:"hash-b",recordsSummaryHash:"different",normalizedRecords:[{raceId:"r1",horseNumber:1,horseName:"Changed"}]}; assert.strictEqual(core.detectDuplicate(conflictCandidate,[record]).status,"conflicting_duplicate");
assert.strictEqual(core.buildRecord(source(),approval(),[record],new Date("2026-07-19T01:01:00Z")).reason,"exact_duplicate");

let status="awaiting_manual_approval"; for(const next of ["approval_in_progress","approved","staging_ready","staged","rollback_planned","rolled_back"]){const r=core.transition(status,next);assert.ok(r.transitioned,`${status}->${next}`);status=r.status;} assert.strictEqual(core.transition("awaiting_manual_approval","staged").reason,"invalid_transition"); assert.strictEqual(core.transition("staged","approved").reason,"invalid_transition"); assert.strictEqual(core.transition("cancelled","approval_in_progress").reason,"terminal_locked"); assert.strictEqual(core.transition("expired","staging_ready").reason,"terminal_locked"); assert.strictEqual(core.transition("rolled_back","staged").reason,"terminal_locked"); assert.strictEqual(core.transition("staging_ready","staged",{processing:true}).reason,"staging_locked");
let h=core.appendHistory([], {historyId:"h1",stagingId:record.stagingId,action:"x"}); assert.ok(h.appended); assert.strictEqual(core.appendHistory(h.history,{historyId:"h1"}).reason,"duplicate_history");
const op=(reason="human operation")=>({reason,operator:"Operator",operatedAt:"2026-07-19T11:00:00+09:00",notes:"note"}); let staged={...record,stagingStatus:"staged"}; let operated=core.applyOperation(staged,"rollback_planned",op()); assert.ok(operated.created); assert.strictEqual(operated.record.normalizedRecords.length,2); operated=core.applyOperation(operated.record,"rolled_back",op()); assert.ok(operated.created); assert.strictEqual(operated.record.stagingStatus,"rolled_back"); assert.strictEqual(operated.record.phase22Applied,false); assert.strictEqual(core.applyOperation(operated.record,"staged",op()).reason,"invalid_operation"); assert.ok(core.applyOperation({...record,stagingStatus:"staging_ready"},"cancelled",op()).created); assert.ok(core.applyOperation({...record,stagingStatus:"staging_ready"},"expired",op()).created); assert.ok(core.applyOperation({...record,stagingStatus:"staging_ready"},"staging_failed",op()).created);

let storage=memoryStorage(); let added=core.addRecord(core.defaultStore(),record,storage,new Date("2026-07-19T02:00:00Z")); assert.ok(added.saved); assert.strictEqual(added.store.records[0].stagingStatus,"staged"); assert.strictEqual(core.addRecord(added.store,record,storage).reason,"duplicate_staging_id"); assert.strictEqual(core.loadStore(storage).store.records.length,1); assert.ok(core.loadStore(memoryStorage({[core.STORAGE_KEY]:"{bad"})).parseError);
const before=JSON.stringify(added.store), failing=memoryStorage({[core.STORAGE_KEY]:before},true), failed=core.saveStore({...added.store,savedAt:"changed"},failing); assert.ok(!failed.saved); assert.strictEqual(failing.data[core.STORAGE_KEY],before);
assert.ok(core.auditText(added.store.records[0]).includes("Phase22未反映")); assert.ok(core.auditText(added.store.records[0]).includes("phase22Applied=false"));

const code=read("phase23-3-approved-preview-staging-storage-core.js")+read("phase23-3-main-dashboard-integration.js"); for(const p of [/\bfetch\s*\(/,/XMLHttpRequest/,/\bWebSocket\s*\(/,/\bEventSource\s*\(/,/setInterval\s*\(/]) assert.ok(!p.test(code)); assert.ok(!/IPAT/i.test(code)); assert.ok(!/removeItem\s*\([^)]*staging/i.test(code)); assert.ok(!/localStorage\.setItem\s*\([^,]*(?:phase22|externalRacingDataAcquisitionSafetyDesign|manualCsvJsonImportPreviewValidation)/i.test(code));
const index=read("index.html"),local=read("private-local.html"),readme=read("README.md"),docs=read("docs/phase23-3-approved-preview-staging-storage-core.md"); assert.ok(index.includes('id="phase23-approved-preview-staging-storage"')); assert.ok(local.includes('href="index.html#phase23-approved-preview-staging-storage"')); assert.ok(index.indexOf('id="phase23-manual-csv-json-import-preview-validation"')<index.indexOf('id="phase23-approved-preview-staging-storage"')); assert.ok(local.indexOf("Phase23-2 手動")<local.indexOf("Phase23-3 承認")); assert.ok(index.indexOf("phase23-2-main-dashboard-integration.js")<index.indexOf("phase23-3-approved-preview-staging-storage-core.js")); assert.ok(index.indexOf("phase23-3-approved-preview-staging-storage-core.js")<index.indexOf("phase23-3-main-dashboard-integration.js"));
for(const f of ["index.html","private-local.html","phase22-22-private-local.html"]){const html=read(f),ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.strictEqual(ids.length,new Set(ids).size);for(const m of html.matchAll(/<script[^>]+src="([^"]+)"/g))if(!/^(?:https?:)?\/\//.test(m[1]))assert.ok(fs.existsSync(path.join(root,m[1])));} assert.ok(readme.includes("Phase23-3")); for(const marker of ["非破壊","2 MiB","重複","ロールバック","Phase22","Phase23-4","PLAN_ONLY"])assert.ok(docs.includes(marker),marker);
console.log("Phase23-3 approved preview staging storage core tests passed");
