"use strict";const assert=require("assert"),fs=require("fs"),path=require("path"),core=require("../phase26-38-phase26-completion-decision-core.js");
const clock={now:()=>new Date("2026-08-06T09:00:00Z")},expired={now:()=>new Date("2026-09-01T09:00:00Z")},op=reason=>({performedBy:"human-decider",reason,explicitConfirmation:true});
const audit=(o={})=>{const a={phase26IntegrityAuditId:"audit-37",postCorrectionClosureExecutionRecordId:"closure-36",registrationRecordId:"registration-1",sourceRecordId:"source-1",raceId:"race-1",targetRecordType:"race",targetRecordKey:"race-1",auditStatus:"ready_for_phase26_completion_decision",auditResult:"pass",unresolvedIssueCount:0,auditTrail:[{event:"completed"}],warningDetected:false,warningDetails:[]};core.TRUE_GATE.forEach(k=>a[k]=true);core.FALSE_GATE.forEach(k=>a[k]=false);core.EMPTY_GATE.forEach(k=>a[k]=[]);return Object.assign(a,o)};
const records=Array.from({length:36},(_,i)=>({phaseNumber:i+1,phaseId:`Phase26-${i+1}`,recordId:`record-${i+1}`,targetRecordKey:"race-1",raceId:"race-1"}));
const inputFor=a=>({decidedBy:"Decider",recordedBy:"Recorder",decisionEnvironment:"Private Local",decisionDevice:"local-pc",decisionLocation:"local",decisionMethod:"manual review",decisionReference:"decision-sheet",decisionExpiresAt:"2026-08-20T00:00:00Z",integrityAuditSnapshot:a,closureExecutionSnapshot:{},registrationSnapshot:{},importSnapshot:{},acquisitionSnapshot:{},currentTargetSnapshot:{},integrityAuditSnapshotHash:"audit-hash",closureExecutionSnapshotHash:"closure-hash",registrationSnapshotHash:"registration-hash",importSnapshotHash:"import-hash",acquisitionSnapshotHash:"acquisition-hash",currentTargetHash:"current-hash",integrityAuditVersion:"37.1",closureExecutionVersion:"36.1",registrationVersion:"1",importVersion:"1",acquisitionVersion:"1",currentTargetVersion:"v1"});
assert(core.validateAuditRecord(audit()).valid);assert(!core.validateAuditRecord(audit({auditResult:"fail"})).valid);assert(core.validateDecisionStartGate(audit(),records,[],inputFor(audit())).eligible);assert.strictEqual(core.extractDecisionCandidates([audit()],records,[],inputFor(audit())).length,1);assert(!core.validateDecisionStartGate(audit(),records.slice(1),[],inputFor(audit())).eligible);assert(!core.validateDecisionStartGate(audit(),records,[{phase26IntegrityAuditId:"audit-37"}],inputFor(audit())).eligible);
function create(a=audit()){core.resetRegistry();const x=core.createCompletionDecisionRecord(a,records,inputFor(a),op("create"),clock);assert(x.created,x.reasons);return x.record}function progress(a=audit()){let r=create(a),x=core.startManualDecision(r,{manualStartConfirmation:true},op("start"),clock);assert(x.transitioned);x=core.recordDecisionProgress(x.record,{deciderNote:"reviewing"},op("progress"),clock);assert(x.transitioned);return x.record}
let r=progress(),x=core.completeDecision(r,{completionDecisionResult:"approve_for_manual_phase26_completion_approval",completionDecisionReason:"all completion gates passed",nextAction:"manual Phase26 completion approval",warningsReviewed:true},op("approve"),clock);assert(x.completed,x.reasons);assert.strictEqual(x.record.completionDecisionStatus,"ready_for_manual_phase26_completion_approval");assert(x.record.approvedForManualPhase26CompletionApproval);assert(core.checkDecisionExpiry(x.record,clock).valid);assert(core.createApprovalCandidate(x.record,op("handoff"),clock).created);assert(!core.createApprovalCandidate(x.record,op("expired"),expired).created);assert(!core.transition(x.record,"manual_phase26_completion_decision_in_progress",op("overwrite"),clock).transitioned);
for(const result of["reject","return_for_integrity_audit","return_for_correction","return_for_reverification","return_for_redecision","rollback_required","additional_evidence_required","additional_review_required","manual_investigation_required","hold","blocked"]){r=progress();x=core.completeDecision(r,{completionDecisionResult:result,completionDecisionReason:`${result} required`,nextAction:"manual follow-up",blockingReasons:[result],owner:"Owner",deadline:"2026-08-10",requiredEvidence:["evidence"],warningsReviewed:true},op(result),clock);assert(x.completed,`${result}: ${x.reasons}`);assert.notStrictEqual(x.record.completionDecisionStatus,"ready_for_manual_phase26_completion_approval")}
r=progress();assert(!core.completeDecision(r,{completionDecisionResult:"approve_for_manual_phase26_completion_approval",completionDecisionReason:"bad",nextAction:"approval",warningsReviewed:false},op("bad warning"),clock).completed);assert(!core.createCompletionDecisionRecord(audit({criticalIssueDetected:true}),records,inputFor(audit()),op("critical"),clock).created);assert(!core.createCompletionDecisionRecord(audit(),records,{...inputFor(audit()),decisionExpiresAt:"2026-08-01T00:00:00Z"},op("expired create"),clock).created);assert(!core.createCompletionDecisionRecord(audit(),records,{...inputFor(audit()),decidedBy:""},op("missing decider"),clock).created);
const a=audit();assert(core.verifyPhaseContinuity({...a,expectedPhaseCount:36,detectedPhaseCount:36}).valid);assert(core.verifyReferences(a).valid);assert(core.verifyStatusTransitions(a).valid);assert(core.verifyTarget(a).valid);assert(core.verifyHashes(a).valid);assert(core.verifyVersions(a).valid);assert(core.verifyEvidence(a).valid);assert(core.verifyAuditTrail(a).valid);assert(core.verifyDuplicates(a).valid);assert(core.verifyMissing(a).valid);assert(core.verifyOrphans(a).valid);assert(core.verifyOverwrite(a).valid);assert(core.verifyRollback(a).valid);assert(core.verifySafety(a).valid);assert(!core.detectAbnormalities(a).detected);
const memory={value:null,setItem(k,v){this.value=v},getItem(){return this.value}};r=create();assert(core.saveRecords(memory,[r]).saved);assert(core.loadRecords(memory).loaded);memory.value=JSON.stringify({schemaVersion:"old",records:[]});assert(!core.loadRecords(memory).loaded);
const root=path.join(__dirname,".."),html=fs.readFileSync(path.join(root,"private-local.html"),"utf8"),css=fs.readFileSync(path.join(root,"phase26-38.css"),"utf8"),readme=fs.readFileSync(path.join(root,"README.md"),"utf8"),source=fs.readFileSync(path.join(root,"phase26-38-phase26-completion-decision-core.js"),"utf8");for(const text of["phase26-38-phase26-completion-decision","Phase26完了判定コア","対象監査記録","完了判定状態","判定期限","Phase連続性","参照整合性","hash結果","監査証跡","次工程移行可否","Private Local only","PLAN_ONLY","protectedMode","自動完了判定なし","自動承認なし","自動適用なし","自動学習更新なし","Public公開なし","外部送信なし"])assert(html.includes(text),text);assert(css.includes(".phase2638-panel")&&readme.includes("Phase26-38 Phase26 Completion Decision Core"));for(const p of[/fetch\s*\(/,/XMLHttpRequest/,/WebSocket\s*\(/,/automaticCompletionDecisionAllowed:\s*true/,/automaticApprovalAllowed:\s*true/,/registeredDataMutated:\s*true/])assert(!p.test(source));console.log("phase26CompletionDecisionCore.test.js: PASS");
