"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),core=require("../phase26-34-manual-post-registration-post-correction-closure-check-core.js");
const clock={now:()=>new Date("2026-08-04T07:00:00Z")},op=reason=>({performedBy:"human-checker",reason,explicitConfirmation:true});
const flags={acceptanceRecordValid:true,acceptanceStatusValid:true,acceptanceResultValid:true,targetIdentityConfirmed:true,targetKeyConfirmed:true,registrationReferenceConfirmed:true,decisionReferenceConfirmed:true,verificationReferenceConfirmed:true,executionReferenceConfirmed:true,hashResultConfirmed:true,versionResultConfirmed:true,conditionItemsConfirmed:true,outstandingItemsConfirmed:true,deadlinesConfirmed:true,ownersConfirmed:true,evidenceConfirmed:true,auditTrailConfirmed:true,rollbackStatusConfirmed:true,abnormalitiesResolved:true,criticalIssuesAbsent:true,warningsReviewed:true,safetyFlagsConfirmed:true};
const safety={protectedMode:true,planOnly:true,privateLocalOnly:true,automaticCorrectionAllowed:false,automaticExecutionAllowed:false,automaticVerificationAllowed:false,automaticDecisionAllowed:false,automaticApprovalAllowed:false,automaticAcceptanceAllowed:false,automaticClosureAllowed:false,automaticApplicationAllowed:false,automaticLearningAllowed:false,publicReleaseAllowed:false,externalTransmissionAllowed:false,registeredDataMutated:false,appliedToPrediction:false,appliedToLearning:false,sentExternally:false};
const management=(o={})=>({postCorrectionAcceptanceManagementId:"management-33",postCorrectionAcceptanceId:"acceptance-32",postCorrectionVerificationDecisionId:"decision-31",postCorrectionVerificationId:"verification-30",correctionExecutionId:"execution-29",correctionExecutionApprovalId:"approval-28",correctionPlanApprovalId:"approval-27",correctionPlanId:"plan-26",correctionRequestId:"request-25",correctionImpactReviewId:"impact-24",correctionTargetIdentificationId:"target-23",registrationRecordId:"registration-1",previousAcceptanceRecordId:"acceptance-old",importRecordId:"import-1",sourceRecordId:"source-1",raceId:"race-1",targetRecordType:"race_result",targetRecordKey:"race-1",managementStatus:"ready_for_manual_post_correction_closure",managementResult:"completed",conditionalAcceptance:false,conditionCompletionRate:0,unresolvedOutstandingItemCount:0,followUpRequired:false,followUpStatus:"not_required",conditionOverdue:false,outstandingItemOverdue:false,reverificationRequired:false,redecisionRequired:false,recorrectionRequired:false,rollbackRequired:false,additionalEvidenceRequired:false,additionalReviewRequired:false,abnormalityDetected:false,criticalIssueDetected:false,unresolvedIssueCount:0,currentTargetHash:"current-hash",currentTargetVersion:"v2",recordVersion:6,warningDetected:false,auditTrail:[{event:"management_completed",performedBy:"Manager",performedAt:"2026-08-04T06:00:00Z"}],...flags,...safety,...o});
const context=(o={})=>({postCorrectionAcceptanceManagementId:"management-33",phase2632AcceptanceValid:true,phase2631DecisionValid:true,phase2630VerificationValid:true,phase2629ExecutionValid:true,registrationRecordId:"registration-1",targetRecordKey:"race-1",managementSnapshotHash:"management-hash",managementVersion:"6",...o});
const input=(o={})=>({recordedBy:"recorder",checkEnvironment:"Private Local",checkDevice:"local-pc",checkLocation:"local",checkMethod:"manual final check",checkReference:"closure-check-sheet",managementSnapshot:{managementResult:"completed",conditionCompletionRate:0,unresolvedOutstandingItemCount:0,followUpStatus:"not_required"},acceptanceSnapshot:{acceptanceResult:"accept"},decisionSnapshot:{decisionResult:"approve_for_manual_post_correction_acceptance"},verificationSnapshot:{verificationResult:"verified"},executionSnapshot:{executionResult:"completed"},registrationSnapshot:{registrationRecordId:"registration-1"},currentTargetSnapshot:{finishTime:"1:34.8"},managementSnapshotHash:"management-hash",acceptanceSnapshotHash:"acceptance-hash",decisionSnapshotHash:"decision-hash",verificationSnapshotHash:"verification-hash",executionSnapshotHash:"execution-hash",registrationSnapshotHash:"registration-hash",currentTargetHash:"current-hash",managementVersion:"6",acceptanceVersion:"5",decisionVersion:"4",verificationVersion:"3",executionVersion:"2",registrationVersion:"1",currentTargetVersion:"v2",...o});
function create(){core.resetRegistry();const x=core.createClosureCheck(management(),context(),input(),op("create"),clock);assert(x.created,x.reasons);return x.record}
function inProgress(){let r=create(),x=core.startManualClosureCheck(r,{manualStartConfirmation:true,checkedBy:"Checker"},op("start"),clock);assert(x.transitioned,x.reasons);x=core.recordClosureCheckProgress(x.record,{checkerNote:"checking"},op("progress"),clock);assert(x.transitioned,x.reasons);return x.record}
const resultInput=(o={})=>({closureCheckReason:"all closure gates confirmed",closureCheckSummary:"manual final check",nextAction:"prepare closure approval",warningsReviewed:true,references:{phase2632AcceptanceValid:true,phase2631DecisionValid:true,phase2630VerificationValid:true,phase2629ExecutionValid:true,registrationRecordId:"registration-1",targetRecordKey:"race-1"},existingClosureChecks:[],...o});
let m=management(),g=core.validateClosureCheckEligibility(m,context(),[]);assert(g.eligible,g.reasons);assert.strictEqual(core.extractEligibleClosureCheckCandidates([m],[context()],[]).length,1);
for(const bad of[management({managementStatus:"management_completed"}),management({managementResult:"pending"}),management({conditionItemsConfirmed:false}),management({unresolvedOutstandingItemCount:1}),management({reverificationRequired:true}),management({redecisionRequired:true}),management({recorrectionRequired:true}),management({rollbackRequired:true}),management({additionalEvidenceRequired:true}),management({additionalReviewRequired:true}),management({abnormalityDetected:true}),management({criticalIssueDetected:true}),management({automaticClosureAllowed:true}),management({automaticApplicationAllowed:true}),management({automaticLearningAllowed:true}),management({publicReleaseAllowed:true}),management({externalTransmissionAllowed:true})])assert(!core.validateClosureCheckEligibility(bad,context(),[]).eligible);
assert(!core.validateClosureCheckEligibility(m,context({targetRecordKey:"other"}),[]).eligible);assert(!core.validateClosureCheckEligibility(m,context(),[{postCorrectionAcceptanceManagementId:"management-33",invalidatedAt:""}]).eligible);
let r=create(),x=core.startManualClosureCheck(r,{manualStartConfirmation:true,checkedBy:"Checker"},op("start"),clock);assert(x.transitioned);x=core.recordClosureCheckProgress(x.record,{},op("progress"),clock);assert(x.transitioned);let paused=core.pauseClosureCheck(x.record,"pause",op("pause"),clock);assert(paused.transitioned);let resumed=core.resumeClosureCheck(paused.record,{manualResumeConfirmation:true},op("resume"),clock);assert(resumed.transitioned);
r=resumed.record;x=core.markClosureReady(r,m,resultInput(),op("ready"),clock);assert(x.completed,x.reasons);assert.strictEqual(x.record.closureCheckStatus,"closure_check_ready");assert(x.record.readyForManualClosureApproval);let candidate=core.createClosureApprovalCandidate(x.record,op("handoff"),clock);assert(candidate.created);assert(candidate.candidate.readyForManualPostCorrectionClosureApproval);assert(!core.transition(candidate.record,"manual_closure_check_in_progress",op("overwrite"),clock).transitioned);
const route={target:"management-33",owner:"Owner",deadline:"2026-08-10T00:00:00Z",requiredEvidence:["evidence"],nextAction:"manual action"};for(const [fn,result,state] of[["returnForAcceptanceManagement","return_for_acceptance_management","returned_for_acceptance_management"],["returnForReverification","return_for_reverification","returned_for_reverification"],["returnForRedecision","return_for_redecision","returned_for_redecision"],["returnForCorrection","return_for_correction","returned_for_correction"],["requireRollback","rollback_required","rollback_required"],["requireAdditionalEvidence","additional_evidence_required","additional_evidence_required"],["requireAdditionalReview","additional_review_required","additional_review_required"],["holdClosureCheck","hold","closure_check_on_hold"],["blockClosureCheck","blocked","closure_check_blocked"]]){r=inProgress();x=core[fn](r,m,resultInput({...route,nextAction:result}),op(result),clock);assert(x.completed,x.reasons);assert.strictEqual(x.record.closureCheckStatus,state);assert(!core.createClosureApprovalCandidate(x.record,op("blocked"),clock).created)}
r=inProgress();assert(!core.markClosureReady(r,m,resultInput({closureCheckReason:""}),op("missing reason"),clock).completed);assert(!core.markClosureReady(r,management({currentTargetHash:"wrong"}),resultInput(),op("bad hash"),clock).completed);assert(!core.markClosureReady(r,management({conditionCompletionRate:80,conditionalAcceptance:true}),resultInput(),op("conditions incomplete"),clock).completed);
assert(core.verifyManagementIntegrity(m,resultInput().references).allValid);assert(core.verifyHashes(m,input()).valid);assert(core.verifyVersions(m,input()).valid);
const memory={value:null,setItem(k,val){this.value=val},getItem(){return this.value}};r=create();assert(core.saveRecords(memory,[r]).saved);assert(core.loadRecords(memory).loaded);memory.value=JSON.stringify({schemaVersion:"old",records:[]});assert(!core.loadRecords(memory).loaded);
assert(core.SAFETY.privateLocalOnly&&core.SAFETY.planOnly&&core.SAFETY.protectedMode);for(const k of["automaticClosureAllowed","automaticApplicationAllowed","automaticLearningAllowed","publicReleaseAllowed","externalTransmissionAllowed","registeredDataMutated","sentExternally","nextPhaseAutomaticallyStarted"])assert.strictEqual(core.SAFETY[k],false,k);
const root=path.join(__dirname,".."),html=fs.readFileSync(path.join(root,"private-local.html"),"utf8"),css=fs.readFileSync(path.join(root,"dashboard.css"),"utf8"),readme=fs.readFileSync(path.join(root,"README.md"),"utf8"),source=fs.readFileSync(path.join(root,"phase26-34-manual-post-registration-post-correction-closure-check-core.js"),"utf8");for(const text of["phase26-34-manual-post-registration-post-correction-closure-check","対象受入管理記録","対象受入記録","対象判定記録","対象検証記録","対象修正実行記録","対象正式登録記録","確認状態","確認者","確認日時","管理結果","受入結果","hash結果","version結果","条件完了状況","未完了項目数","フォローアップ状況","期限解消状況","証跡・監査証跡","再検証・再判定・再修正要否","ロールバック要否","追加証跡・追加レビュー要否","異常・警告","クローズ可否","確認理由","次工程移行可否","Private Local only","PLAN_ONLY","protectedMode","自動クローズなし","自動適用なし","自動学習更新なし","Public公開なし","外部送信なし"])assert(html.includes(text),text);assert(css.includes(".phase2634-panel")&&readme.includes("Phase26-34 Manual Post-Correction Closure Check Core"));for(const p of[/fetch\s*\(/,/XMLHttpRequest/,/WebSocket\s*\(/,/automaticClosureAllowed:\s*true/,/automaticApplicationAllowed:\s*true/,/registeredDataMutated:\s*true/])assert(!p.test(source));
console.log("phase26ManualPostRegistrationPostCorrectionClosureCheckCore.test.js: PASS");
