"use strict";
const assert=require("assert"),fs=require("fs"),vm=require("vm"),p307=require("../phase30-7-phase30-post-start-acceptance-core.js"),code=fs.readFileSync(require.resolve("../phase30-8-phase30-post-start-stabilization-review-core.js"),"utf8"),dependency={...p307,validatePhase306Eligibility:s=>({valid:!!(s&&s.chainValid===true),reasons:[]})},sandbox={module:{exports:{}},exports:{},require:id=>{assert.strictEqual(id,"./phase30-7-phase30-post-start-acceptance-core.js");return dependency}};
vm.runInNewContext(code,sandbox);const core=sandbox.module.exports,NOW="2027-01-01T00:00:00Z",options={now:()=>new Date(NOW)},human={performedBy:"human",reason:"manual decision",explicitConfirmation:true,performedAt:NOW};
function source(p={}){const b={phase30PostStartAcceptanceId:"verification-1",phase30PostStartAcceptanceStatus:"ready_for_manual_phase30_post_start_stabilization_review",phase30PostStartAcceptanceResult:"accept_phase30_post_start",phase306SourceSnapshot:{chainValid:true},phase30Started:true,manualPhase30StartCompleted:true,unresolvedIssues:[],criticalIssues:[],blockingConditions:[],recordVersion:5,auditTrail:[{}],...p307.SAFETY};core.REFERENCE_IDS.forEach(k=>b[k]=b[k]||`${k}-1`);core.UPSTREAM_FIELDS.forEach(k=>b[k]=b[k]||`${k}-1`);const s={...b};return{...b,phase30PostStartAcceptanceSnapshot:s,phase30PostStartAcceptanceSnapshotHash:p307.computeSnapshotHash(s),phase30PostStartAcceptanceVersion:p307.SCHEMA_VERSION,...p}}
function input(p={}){const r={};core.REVIEW_FIELDS.forEach(k=>r[k]=k.endsWith("Evidence")?{confirmed:true}:k);core.ARRAY_FIELDS.forEach(k=>r[k]=[]);core.REQUIRED_TRUE.forEach(k=>r[k]=true);return{...r,...p}}
function create(){const x=core.createStabilizationReviewRecord(source(),input(),human,options,[]);assert(x.created,x.reasons.join());return x.record}function review(){let r=create();r=core.beginStabilizationReview(r,human,options).record;return core.submitStabilizationReview(r,human,options).record}
assert.strictEqual(core.PHASE307_REFERENCE,dependency);assert.strictEqual(core.NEXT_STAGE,"manual_phase30_post_start_stabilization_decision");assert(core.STATES.includes("ready_for_manual_phase30_post_start_stabilization_decision"));assert(core.RESULTS.includes("phase30_post_start_stabilization_stable"));const eligibility=core.validatePhase307Eligibility(source());assert(eligibility.valid,eligibility.reasons.join());assert.strictEqual(core.extractStabilizationReviewCandidates([source()],[]).length,1);
for(const p of [{phase30PostStartAcceptanceStatus:"phase30_post_start_acceptance_rejected"},{phase30PostStartAcceptanceResult:"reject_phase30_post_start"},{phase30PostStartAcceptanceSnapshotHash:"bad"},{phase30PostStartAcceptanceVersion:"bad"},{privateLocalOnly:false},{planOnly:false},{protectedMode:false},{invalidatedAt:NOW},{expiredAt:NOW},{auditTrail:[]},{recordVersion:0},{phase306SourceSnapshot:{chainValid:false}},{phase30PostStartAcceptanceId:""},{unresolvedIssues:["x"]},{criticalIssues:["x"]},{blockingConditions:["x"]},{phase30AutomaticallyStarted:true},{nextPhaseAutomaticallyStarted:true},{phase30PostStartVerificationDecisionAutomaticallyExecuted:true}])assert.strictEqual(core.validatePhase307Eligibility(source(p)).valid,false,JSON.stringify(p));
assert.strictEqual(core.createStabilizationReviewRecord(source(),input(),{},options,[]).created,false);assert.strictEqual(core.createStabilizationReviewRecord(source(),input(),{...human,explicitConfirmation:false},options,[]).created,false);for(const p of [{reviewTarget:""},{reviewOperator:""},{runtimeStateConfirmation:null},{privateLocalOnly:false},{planOnly:false},{protectedMode:false},{unresolvedIssues:"bad"}])assert.strictEqual(core.createStabilizationReviewRecord(source(),input(p),human,options,[]).created,false,JSON.stringify(p));
const src=source(),first=core.createStabilizationReviewRecord(src,input(),human,options,[]);assert(first.created);assert(Object.isFrozen(core));assert(Object.isFrozen(first.record));assert.strictEqual(core.createStabilizationReviewRecord(src,input(),human,options,[first.record]).created,false);assert.strictEqual(core.extractStabilizationReviewCandidates([src],[first.record]).length,0);assert.strictEqual(core.submitStabilizationReview(first.record,human,options).transitioned,false);
let r=core.beginStabilizationReview(first.record,human,options).record;assert.strictEqual(r.phase30PostStartStabilizationReviewStatus,"manual_phase30_post_start_stabilization_review_in_progress");for(const p of [{phase30Started:false},{phase307SourceSnapshot:{}},{privateLocalOnly:false},{auditTrail:[]}])assert.strictEqual(core.updateStabilizationReview(r,p,human,options).updated,false,JSON.stringify(p));const updated=core.updateStabilizationReview(r,{reviewNotes:"updated"},human,options);assert(updated.updated);r=core.submitStabilizationReview(updated.record,human,options).record;assert.strictEqual(r.phase30PostStartStabilizationReviewStatus,"awaiting_manual_phase30_post_start_stabilization_review_completion");
const approve={result:"phase30_post_start_stabilization_stable",reviewSummary:"stable manually",completedBy:"reviewer",completedAt:NOW,stabilizationAfterSnapshot:{state:"after"}};for(const p of [{reviewSummary:""},{completedAt:"bad"},{completedBy:""},{stabilizationAfterSnapshot:null},{unresolvedIssues:["x"]},{criticalIssues:["x"]},{blockingConditions:["x"]},{protectedMode:false}])assert.strictEqual(core.completeStabilizationReview(r,{...approve,...p},human,options).completed,false,JSON.stringify(p));const ok=core.completeStabilizationReview(r,approve,human,options);assert(ok.completed,ok.reasons.join());assert.strictEqual(ok.record.phase30PostStartStabilizationReviewStatus,"ready_for_manual_phase30_post_start_stabilization_decision");assert.strictEqual(ok.record.phase30PostStartStabilizationReviewResult,"phase30_post_start_stabilization_stable");assert.strictEqual(ok.record.phase30Started,true);assert.strictEqual(ok.record.manualPhase30StartCompleted,true);
assert.strictEqual(core.completeStabilizationReview(review(),{result:"phase30_post_start_stabilization_conditionally_stable"},human,options).completed,false);assert(core.completeStabilizationReview(review(),{result:"phase30_post_start_stabilization_conditionally_stable",conditions:"c",conditionReason:"r",conditionOwner:"o",conditionDeadline:"2027-02-01",conditionVerificationMethod:"manual",conditionReleaseCriteria:"verified"},human,options).completed);assert.strictEqual(core.completeStabilizationReview(review(),{result:"phase30_post_start_stabilization_unstable"},human,options).completed,false);assert(core.completeStabilizationReview(review(),{result:"phase30_post_start_stabilization_unstable",unstableReason:"unstable",requiredActions:["review"]},human,options).completed);for(const result of ["phase30_post_start_stabilization_review_incomplete","phase30_post_start_stabilization_review_blocked"])assert(core.completeStabilizationReview(review(),{result},human,options).completed,result);
for(const [k,v] of Object.entries(core.SAFETY))assert.strictEqual(ok.record[k],v,k);assert(core.integrityIntact(ok.record));assert(core.safetyIntact(ok.record));assert.strictEqual(core.integrityIntact({...ok.record,phase30PostStartStabilizationReviewSnapshotHash:"bad"}),false);assert.strictEqual(core.safetyIntact({...ok.record,networkCommunicationPerformed:true}),false);assert(core.invalidateStabilizationReview(ok.record,human,options).transitioned);
const mem={v:null,setItem(_k,v){this.v=v},getItem(){return this.v}};assert(core.saveStabilizationReviewRecords(mem,[ok.record]).saved);assert(core.loadStabilizationReviewRecords(mem).loaded);mem.v=JSON.stringify({schemaVersion:"bad",records:[ok.record]});assert.strictEqual(core.loadStabilizationReviewRecords(mem).loaded,false);mem.v=JSON.stringify({schemaVersion:core.SCHEMA_VERSION,records:[{}]});assert.strictEqual(core.loadStabilizationReviewRecords(mem).loaded,false);
for(const k of ["automaticallyDecide","automaticallyCorrect","automaticallyRollback","automaticallyRecover","startPhase30","startNextPhase"])assert.strictEqual(core[k],undefined,k);const browser={HashimotoPhase307PostStartAcceptance:dependency};vm.runInNewContext(code,browser);assert(browser.HashimotoPhase308PostStartStabilizationReview);assert(code.includes('require("./phase30-7-phase30-post-start-acceptance-core.js")'));assert.throws(()=>vm.runInNewContext(code,{}),/Phase30-7/);assert(!/fetch\s*\(|XMLHttpRequest|WebSocket|EventSource|sendBeacon\s*\(|http\.request|https\.request|child_process|execSync|spawnSync|setInterval\s*\(|setTimeout\s*\(|(?:new\s+)?(?:Shared)?Worker\s*\(|fs\.writeFile|fs\.mkdir|mkdirSync|writeFileSync|Authorization\s*:|Bearer\s+/.test(code));console.log("phase30PostStartStabilizationReviewCore.test.js: PASS");


