"use strict";
const assert=require("assert"),fs=require("fs"),vm=require("vm"),core=require("../phase28-5-source-trust-review-core.js"),p284=core.PHASE284_REFERENCE,p281=p284.PHASE283_REFERENCE.PHASE282_REFERENCE.PHASE281_REFERENCE,NOW="2027-01-01T00:00:00Z",options={now:()=>new Date(NOW)},human={performedBy:"human",reason:"manual",explicitConfirmation:true,performedAt:NOW};
const candidate={sourceCandidateId:"source-1",sourceCode:"source_one",sourceName:"Candidate",providerName:"Provider",sourceType:"official_web",officialStatus:"official_candidate",targetCategories:[...p284.REQUIRED_CATEGORIES]};
function source(p={}){const base={phase28SourceCandidateRegistrationId:"registration-1",phase28SourceCandidateRegistrationStatus:"ready_for_manual_phase28_source_trust_review",phase28SourceCandidateRegistrationResult:"source_candidates_registered",sourceCandidates:[candidate],expiresAt:"2027-12-01T00:00:00Z",recordVersion:4,auditTrail:[{action:"handoff"}],correctionRequired:false,rollbackRequired:false,recoveryRequired:false,criticalIssues:[],blockingConditions:[],...p284.SAFETY};p284.REFERENCE_IDS.forEach(k=>base[k]=`${k}-1`);p284.ZERO_COUNTS.forEach(k=>base[k]=0);const snapshot={...base};return{...base,phase28SourceCandidateRegistrationSnapshot:snapshot,phase28SourceCandidateRegistrationSnapshotHash:p284.computeSnapshotHash(snapshot),phase28SourceCandidateRegistrationVersion:p284.SCHEMA_VERSION,...p}}
function input(p={}){return{reviewLead:"reviewer",responsiblePerson:"owner",confirmedBy:"confirmer",reviewReason:"trust review",reviewScope:"all sources",reviewTarget:"registered candidates",trustReviewPolicy:"human evidence only",rollbackPoint:"before",recoveryPoint:"snapshot",gitEvidence:{safe:true},testEvidence:{pass:true},stateEvidence:{stable:true},safetyEvidence:{intact:true},expiresAt:"2027-11-01T00:00:00Z",...p}}
function review(p={}){const r={};for(const key of core.TRUST_REVIEW_FIELDS)r[key]=key==="targetCategories"?[...candidate.targetCategories]:key==="trustScoreCandidate"?80:key==="reviewedAt"?NOW:key==="crossSourceVerificationCandidate"?true:`review_${key}`;return{...r,...candidate,reviewedBy:"human reviewer",reviewedAt:NOW,trustClassification:"trusted_candidate",trustScoreCandidate:80,sourceTrustReason:"sufficient human evidence",riskEvidence:{reviewed:true},manualVerificationEvidence:{verified:true},...p}}
function create(){const x=core.createSourceTrustReviewRecord(source(),input(),human,options,[]);assert(x.created,x.reasons.join());return x.record}function progress(){let r=create();r=core.startSourceTrustReview(r,human,options).record;return core.progressSourceTrustReview(r,human,options).record}function accepted(p={}){return{result:"source_trust_review_accepted",trustReviews:[review()],reviewSummary:"reviewed",reviewConclusion:"candidate may proceed to policy review",sourceCoverageEvidence:{complete:true},trustClassificationEvidence:{human:true},officialEvidenceSummary:{recorded:true},providerEvidenceSummary:{recorded:true},provenanceEvidenceSummary:{recorded:true},riskEvidenceSummary:{recorded:true},manualVerificationSummary:{recorded:true},auditEvidence:{ok:true},integrityEvidence:{ok:true},reviewAfterSnapshot:{reviewed:true},rollbackEvidence:{ready:true},recoveryEvidence:{ready:true},correctionRequired:false,rollbackRequired:false,recoveryRequired:false,criticalIssues:[],blockingConditions:[],...p}}
assert(core.PHASE284_REFERENCE);assert.strictEqual(core.CURRENT_STAGE,"source_trust_review");assert.strictEqual(core.NEXT_STAGE,"terms_and_policy_review");assert(p281.PHASE28_STAGES.includes(core.CURRENT_STAGE)&&p281.PHASE28_STAGES.includes(core.NEXT_STAGE));assert.strictEqual(core.extractSourceTrustReviewCandidates([source()],[]).length,1);
for(const p of [{phase28SourceCandidateRegistrationStatus:"bad"},{phase28SourceCandidateRegistrationResult:"bad"},{invalidatedAt:NOW},{expiredAt:NOW},{phase28SourceCandidateRegistrationSnapshot:null},{phase28SourceCandidateRegistrationSnapshotHash:"bad"},{phase28SourceCandidateRegistrationVersion:"bad"},{auditTrail:[]},{recordVersion:0},{protectedMode:false},{sourceCandidates:[]},{sourceCandidates:[{...candidate,targetCategories:["race_entry"]}]},{criticalIssues:["x"]},{blockingConditions:["x"]},{correctionRequired:true},{rollbackRequired:true},{recoveryRequired:true}])assert.strictEqual(core.validatePhase284Eligibility(source(p)).valid,false,JSON.stringify(p));
assert.strictEqual(core.createSourceTrustReviewRecord(source(),input(),{},options,[]).created,false);const src=source(),text=JSON.stringify(src);assert(core.createSourceTrustReviewRecord(src,input(),human,options,[]).created);assert.strictEqual(JSON.stringify(src),text);const first=create();assert.strictEqual(core.extractSourceTrustReviewCandidates([source()],[first]).length,0);assert.strictEqual(core.createSourceTrustReviewRecord(source(),input(),human,options,[first]).created,false);
let r=core.startSourceTrustReview(first,human,options).record;r=core.progressSourceTrustReview(r,human,options).record;assert(core.pauseSourceTrustReview(r,human,options).transitioned);assert(core.resumeSourceTrustReview(core.pauseSourceTrustReview(r,human,options).record,human,options).transitioned);assert(core.stopSourceTrustReview(r,human,options).transitioned);assert(core.cancelSourceTrustReview(r,human,options).transitioned);assert(core.failSourceTrustReview(r,human,options).transitioned);assert.strictEqual(core.updateSourceTrustReview(first,{},human,options).updated,false);assert(core.updateSourceTrustReview(r,{reviewReason:"updated"},human,options).updated);
for(const p of [{trustReviews:[]},{trustReviews:[review({sourceCandidateId:"unknown"})]},{trustReviews:[review(),review()]},{trustReviews:[review({sourceTrustReason:""})]},{trustReviews:[review({riskEvidence:null})]},{trustReviews:[review({manualVerificationEvidence:null})]},{trustReviews:[review({reviewedAt:"bad"})]}])assert.strictEqual(core.completeSourceTrustReview(r,accepted(p),human,options).completed,false,JSON.stringify(p));
for(const classification of ["untrusted_candidate","rejected_candidate","high_risk_candidate","insufficient_evidence"])assert.strictEqual(core.completeSourceTrustReview(r,accepted({trustReviews:[review({trustClassification:classification})]}),human,options).completed,false,classification);for(const p of [{criticalIssues:["x"]},{blockingConditions:["x"]},{correctionRequired:true},{rollbackRequired:true},{recoveryRequired:true},{reviewSummary:null}])assert.strictEqual(core.completeSourceTrustReview(r,accepted(p),human,options).completed,false);
const ok=core.completeSourceTrustReview(r,accepted(),human,options);assert(ok.completed,ok.reasons.join());assert.strictEqual(ok.record.phase28SourceTrustReviewStatus,"source_trust_review_accepted");
const routes=[["source_trust_review_conditionally_accepted",{conditions:"c",conditionReason:"r",conditionOwner:"o",conditionDeadline:"2027-03-01",conditionVerificationMethod:"m",conditionReleaseCriteria:"c"}],...["source_trust_review_rejected","source_trust_review_incomplete","additional_trust_evidence_required","manual_verification_required","multiple_source_verification_required","official_confirmation_required","source_candidate_replacement_required","source_candidate_registration_review_required","correction_plan_required","rollback_plan_required","recovery_plan_required","manual_investigation_required","hold","blocked"].map(x=>[x,{}])];for(const[result,p]of routes)assert(core.completeSourceTrustReview(progress(),{result,...p},human,options).completed,result);
assert.strictEqual(core.advanceToTermsAndPolicyReview(ok.record,{},options).advanced,false);const hand=core.advanceToTermsAndPolicyReview(ok.record,human,options);assert(hand.advanced);assert.strictEqual(hand.record.phase28SourceTrustReviewStatus,"ready_for_manual_phase28_terms_and_policy_review");for(const k of ["networkCommunicationPerformed","externalDataAcquired","apiRequestPerformed","authenticationPerformed","credentialsStored","automaticSourceTrustDecisionPerformed","sourceAutomaticallyApproved","bettingExecuted","appliedToPrediction","appliedToLearning","phase28AutomaticallyAdvanced"])assert.strictEqual(hand.record[k],false,k);
assert(core.integrityIntact(first));for(const p of [{phase28SourceTrustReviewSnapshot:{tampered:true}},{phase28SourceTrustReviewSnapshotHash:"bad"},{phase28SourceTrustReviewVersion:"bad"}])assert.strictEqual(core.integrityIntact({...first,...p}),false);Object.entries(core.SAFETY).forEach(([k,v])=>assert.strictEqual(first[k],v,k));assert(core.invalidateSourceTrustReview(ok.record,human,options).transitioned);assert.strictEqual(core.expireSourceTrustReview({...first,expiresAt:"2026-01-01"},{},options).expired,false);assert(core.expireSourceTrustReview({...first,expiresAt:"2026-01-01"},human,options).expired);
const mem={v:null,setItem(_k,v){this.v=v},getItem(){return this.v}};assert(core.saveSourceTrustReviewRecords(mem,[ok.record]).saved);assert(core.loadSourceTrustReviewRecords(mem).loaded);mem.v="{";assert.strictEqual(core.loadSourceTrustReviewRecords(mem).loaded,false);
const code=fs.readFileSync(require.resolve("../phase28-5-source-trust-review-core.js"),"utf8"),browser={HashimotoPhase284SourceCandidateRegistration:p284};vm.runInNewContext(code,browser);assert(browser.HashimotoPhase285SourceTrustReview);assert(code.includes('require("./phase28-4-source-candidate-registration-core.js")'));assert.throws(()=>vm.runInNewContext(code,{}),/Phase28-4/);assert(!/fetch\s*\(|XMLHttpRequest|WebSocket|EventSource|sendBeacon\s*\(|http\.request|https\.request|child_process|execSync|spawnSync|setInterval\s*\(/.test(code));console.log("phase28SourceTrustReviewCore.test.js: PASS");

