const assert=require("assert"),fs=require("fs"),path=require("path"),core=require("../phase23-audit-follow-up-final-closure-handoff-core.js");
const root=path.join(__dirname,".."),read=f=>fs.readFileSync(path.join(root,f),"utf8");
function plan(){return{resolutionPlanId:"rp-1",version:3,auditRecordId:"audit-1",followUpId:"fu-1",status:"plan_approved",plannedActions:[{actionId:"a1",sequence:1},{actionId:"a2",sequence:2,prerequisiteActionIds:["a1"]}]}}
function execution(){return{executionRecordId:"exec-1",version:4,resolutionPlanId:"rp-1",auditRecordId:"audit-1",followUpId:"fu-1",status:"execution_completed",actions:[{actionId:"a1",sequence:1,required:true,status:"completed",prerequisiteActionIds:[]},{actionId:"a2",sequence:2,required:true,status:"completed",prerequisiteActionIds:["a1"]}],evidence:[{evidenceId:"ev-1",evidenceType:"summary",summary:"metadata",checksum:"sha256-x",localReference:"local/ref"}]}}
function verification(status="verification_passed",issues=[],risks=["low"]){return{verificationRecordId:"verify-1",version:2,executionRecordId:"exec-1",resolutionPlanId:"rp-1",auditRecordId:"audit-1",followUpId:"fu-1",sourceSeverity:"error",status,checks:[{checkId:"c1",result:"confirmed",evidenceIds:["ev-1"]}],decision:{decision:status,unresolvedIssues:issues,residualRisks:risks,conditions:status==="verification_passed_with_conditions"?"monitor":"",conditionsCompleted:false}}}
function memory(initial={},fail=false){const data={...initial};return{data,getItem:k=>Object.prototype.hasOwnProperty.call(data,k)?data[k]:null,setItem(k,v){if(fail)throw Error("quota");data[k]=String(v)},removeItem(){throw Error("physical deletion forbidden")}}}
for(const s of core.ELIGIBLE_VERIFICATION_STATUSES)assert.strictEqual(core.eligibleVerifications({records:[verification(s)]}).length,1);for(const s of["awaiting_manual_verification","verification_in_progress","closed","cancelled","expired"])assert.strictEqual(core.eligibleVerifications({records:[verification(s)]}).length,0);
assert.ok(core.referenceProblems(verification("verification_in_progress"),execution(),plan()).includes("verification_not_decided"));assert.ok(core.referenceProblems({...verification(),terminalLocked:true},execution(),plan()).includes("verification_terminal_locked"));assert.ok(core.referenceProblems({...verification(),auditRecordId:"other"},execution(),plan()).includes("audit_record_id_mismatch"));
let made=core.createClosureRecord(verification(),execution(),plan(),{createdBy:"Reviewer"},new Date("2026-07-24T00:00:00Z"));assert.ok(made.created);let r=made.record;assert.strictEqual(r.source.verificationRecordId,"verify-1");assert.deepStrictEqual(r.source.actions.map(a=>a.actionId),["a1","a2"]);
let x=core.startReview(r,{reviewer:"Reviewer",reviewedAt:"2026-07-24T00:01:00Z",reason:"manual final review"},new Date("2026-07-24T01:00:00Z"));assert.ok(x.started);r=x.record;x=core.pauseReview(r,{reviewer:"Reviewer",reason:"wait"});assert.ok(x.paused);r=x.record;x=core.resumeReview(r,{reviewer:"Reviewer",reason:"resume"});assert.ok(x.resumed);r=x.record;
const base={reviewer:"Reviewer",reviewedAt:"2026-07-24T00:03:00Z",reason:"confirmed",evidenceReviewResult:"confirmed",remainingIssues:[],remainingRisks:["low"],requiredConditionsCompleted:true,humanConfirmed:true};
assert.ok(core.recordDecision({...r,source:{...r.source,verificationStatus:"verification_failed"}},"closure_approved",base,new Date("2026-07-24T01:00:00Z")).problems.includes("verification_passed_required"));assert.ok(core.recordDecision(r,"closure_approved",{...base,remainingIssues:[{severity:"error",summary:"left"}]},new Date("2026-07-24T01:00:00Z")).problems.includes("fatal_or_error_unresolved"));assert.ok(core.recordDecision(r,"closure_approved",{...base,remainingRisks:["critical"]},new Date("2026-07-24T01:00:00Z")).problems.includes("remaining_risk_unacceptable"));
let approved=core.recordDecision(r,"closure_approved",base,new Date("2026-07-24T01:00:00Z"));assert.ok(approved.recorded);let closed=core.closeRecord(approved.record,{reviewer:"Reviewer",closedAt:"2026-07-24",reason:"complete"});assert.ok(closed.closed);assert.strictEqual(core.cancelRecord(closed.record,{reviewer:"R",reason:"x"}).reason,"terminal_locked");
let cr=core.createClosureRecord(verification("verification_passed_with_conditions"),execution(),plan(),{createdBy:"R"}).record;cr=core.startReview(cr,{reviewer:"R",reviewedAt:"2026-07-24",reason:"review"}).record;let conditional=core.recordDecision(cr,"closure_approved_with_conditions",{...base,conditions:"monitor",owner:"Owner",dueAt:"2026-08-01",recheckMethod:"manual",conditionFailureHandling:"handoff to rework"});assert.ok(conditional.recorded);assert.strictEqual(core.closeRecord(conditional.record,{reviewer:"R",closedAt:"2026-07-24",reason:"x"}).reason,"closure_approval_required");conditional=core.confirmConditions(conditional.record,{reviewer:"R",confirmedAt:"2026-07-25",result:"met"});assert.ok(conditional.confirmed);assert.ok(core.closeRecord(conditional.record,{reviewer:"R",closedAt:"2026-07-25",reason:"met"}).closed);
function started(status){let q=core.createClosureRecord(verification(status),execution(),plan(),{createdBy:"R"}).record;return core.startReview(q,{reviewer:"R",reviewedAt:"2026-07-24",reason:"review"}).record}const hand={...base,handoffDestination:"manual queue",handoffReason:"continue",owner:"Owner",dueAt:"2026-08-01",requiredEvidence:"summary",completionCriteria:"human confirmed"};
assert.ok(core.recordDecision(started("rework_required"),"handoff_to_rework",{...hand,targetActionIds:["a2"],requiredWork:"redo"}).recorded);assert.ok(core.recordDecision(started("plan_revision_required"),"handoff_to_plan_revision",{...hand,planRevisionTarget:"action dependency",planRevisionReason:"invalid",reapprovalRequired:true}).recorded);assert.ok(core.recordDecision(started("manual_investigation_required"),"handoff_to_manual_investigation",{...hand,investigationTarget:"evidence",investigationReason:"unclear"}).recorded);let rb=core.recordDecision(started("rollback_review_required"),"handoff_to_rollback_review",{...hand,rollbackReviewTarget:"formal record",rollbackReason:"impact",impactScope:"race",decisionOwner:"Owner"});assert.ok(rb.recorded);assert.strictEqual(rb.record.decision.rollbackExecuted,false);assert.strictEqual(rb.record.decision.automaticRecordCreated,false);
assert.ok(core.recordDecision(started("verification_failed"),"closure_rejected",{...base,rejectionReason:"failed",remainingIssues:[{severity:"error",summary:"left"}],nextManualAction:"investigate",humanConfirmer:"Reviewer"}).recorded);
const originals={formal:"same",snapshot:"same",pending:"same",p236:"same",p237:"same",p238:"same",p239:"same",p2310:"same",phase22:"same"},mem=memory(originals);let saved=core.addRecord(core.defaultStore(),made.record,mem);assert.ok(saved.saved);for(const[k,v]of Object.entries(originals))assert.strictEqual(mem.data[k],v);assert.strictEqual(core.addRecord(saved.store,{...made.record,closureRecordId:"other"},mem).reason,"active_closure_record_exists");
const old=mem.data[core.STORAGE_KEY],fail=memory({[core.STORAGE_KEY]:old},true);assert.strictEqual(core.saveStore({records:[closed.record]},fail).saved,false);assert.strictEqual(fail.data[core.STORAGE_KEY],old);assert.strictEqual(core.replaceRecord({records:[closed.record]},{...closed.record,closedBy:"other"},mem).reason,"terminal_locked");
const index=read("index.html"),local=read("private-local.html"),code=read("phase23-audit-follow-up-final-closure-handoff-core.js")+read("phase23-11-main-dashboard-integration.js");assert.ok(index.includes('id="phase23-audit-follow-up-final-closure-handoff"'));assert.ok(local.includes('href="index.html#phase23-audit-follow-up-final-closure-handoff"'));assert.ok(index.indexOf('id="phase23-audit-follow-up-manual-resolution-verification-decision"')<index.indexOf('id="phase23-audit-follow-up-final-closure-handoff"'));assert.ok(index.indexOf("phase23-10-main-dashboard-integration.js")<index.indexOf("phase23-audit-follow-up-final-closure-handoff-core.js"));
for(const pattern of[/\bfetch\s*\(/,/XMLHttpRequest/,/\bWebSocket\s*\(/,/\bEventSource\s*\(/,/sendBeacon/,/setInterval\s*\(/,/addEventListener\s*\(\s*["']storage/,/\.removeItem\s*\(/])assert.ok(!pattern.test(code));for(const file of["index.html","private-local.html","phase22-22-private-local.html"]){const html=read(file),ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.strictEqual(ids.length,new Set(ids).size,file);for(const m of html.matchAll(/<script[^>]+src="([^"]+)"/g))if(!/^(?:https?:)?\/\//.test(m[1]))assert.ok(fs.existsSync(path.join(root,m[1])),m[1])}
console.log("Phase23-11 final closure handoff core tests passed");
