"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),{webcrypto}=require("crypto");
const core=require("../phase24-3-manual-acquisition-result-registration-quarantine-storage.js"),root=path.resolve(__dirname,".."),now=new Date("2026-07-25T04:00:00.000Z");
const approved={preparationId:"manual-preparation-request-1",requestId:"request-1",sourceId:"source-1",targetId:"target-1",targetType:"odds",status:"awaiting_manual_acquisition",executionPlan:{scheduledAt:"2026-07-25T03:00:00Z",scope:"race 11"},history:[{event:"status_preparation_approved"}]};
const phase242={preparations:[approved,{...approved,preparationId:"not-approved",status:"preparation_approved"},{...approved,preparationId:"no-plan",executionPlan:null}]};
module.exports=(async()=>{
assert.deepEqual(core.eligiblePreparations(phase242).map(x=>x.preparationId),["manual-preparation-request-1"]);
assert(core.preparationProblems(phase242,"not-approved").includes("phase24_2_manual_acquisition_approval_required"));assert(core.preparationProblems(phase242,"missing").includes("phase24_2_record_not_found"));
let store=core.defaultStore(),r=core.createDraft(store,phase242,{acquisitionResultId:"result-1",sourcePhase24_2RecordId:approved.preparationId,targetDate:"2026-07-25",racecourse:"Tokyo",raceNumber:"11",raceName:"Main",createdBy:"operator"},now);assert.equal(r.created,true);store=r.store;assert.equal(r.record.status,"draft");assert.equal(r.record.sourceSnapshot.preparationId,approved.preparationId);assert.equal(r.record.safetyFlags.formalDataModified,false);
assert.equal(core.createDraft(store,phase242,{acquisitionResultId:"result-2",sourcePhase24_2RecordId:"not-approved",createdBy:"operator"},now).created,false);
const input={sourcePhase24_2RecordId:approved.preparationId,acquisitionPlanId:"request-1",targetType:"odds",targetDate:"2026-07-25",racecourse:"Tokyo",raceNumber:"11",raceName:"Main",sourceName:"Official source",sourceUrlText:"https://example.invalid/reference-text-only",acquiredAt:"2026-07-25T03:30:00Z",acquiredBy:"human-a",registeredBy:"human-b",rawText:"race=11 odds=2.5",rawJsonText:'{"raceId":"202607250511","odds":2.5}',memo:"manually pasted",sourceDisplayedTime:"12:30 JST",dataEffectiveTime:"12:29 JST",recordCount:1,changeReason:"manual acquisition result"};
let h=await core.generateContentHash(input,webcrypto);assert.equal(h.generated,true);assert.match(h.contentHash,/^[a-f0-9]{64}$/);
assert(core.registerResult(store,"result-1",{...input,contentHash:h.contentHash,rawJsonText:"{"},now).problems.includes("raw_json_invalid"));
r=core.registerResult(store,"result-1",{...input,contentHash:h.contentHash},now);assert.equal(r.registered,true,JSON.stringify(r.problems));store=r.store;assert.equal(r.record.status,"quarantine");assert.equal(r.record.safetyFlags.formalImportExecuted,false);
let duplicate=core.createDraft(store,phase242,{acquisitionResultId:"result-duplicate",sourcePhase24_2RecordId:approved.preparationId,targetDate:"2026-07-25",racecourse:"Tokyo",raceNumber:"11",raceName:"Main",createdBy:"operator"},now);duplicate=core.registerResult(duplicate.store,"result-duplicate",{...input,contentHash:h.contentHash},now);assert(duplicate.problems.includes("duplicate_result"));
assert.equal(core.transitionRecord(store,"result-1","approved",{operator:"x",reason:"x"},now).transitioned,false);
r=core.transitionRecord(store,"result-1","awaiting_manual_review",{operator:"reviewer",reason:"review"},now);store=r.store;r=core.transitionRecord(store,"result-1","review_in_progress",{operator:"reviewer",reason:"start"},now);store=r.store;r=core.transitionRecord(store,"result-1","needs_correction",{operator:"reviewer",reason:"wrong odds",correctionRequest:"correct raw content"},now);assert.equal(r.transitioned,true);store=r.store;
const corrected={...input,rawText:"race=11 odds=2.6",rawJsonText:'{"raceId":"202607250511","odds":2.6}',changeReason:"manual correction"};h=await core.generateContentHash(corrected,webcrypto);r=core.registerResult(store,"result-1",{...corrected,contentHash:h.contentHash},now);assert.equal(r.registered,true);store=r.store;assert.equal(r.record.revision,1);assert.notEqual(r.record.previousContentHash,r.record.contentHash);assert(r.record.statusHistory.some(x=>x.event==="corrected"));
assert.equal(core.softDelete(store,"result-1",{operator:"operator",reason:"test",confirmation:"wrong"},now).deleted,false);r=core.softDelete(store,"result-1",{operator:"operator",reason:"test",confirmation:"DELETE"},now);assert.equal(r.deleted,true);store=r.store;r=core.restoreDeleted(store,"result-1",{operator:"operator",reason:"restore",confirmation:"RESTORE"},now);assert.equal(r.restored,true);store=r.store;
const backup=core.exportBackup(store,now),validated=core.validateBackup(backup);assert.equal(validated.valid,true);assert.equal(validated.backup.recordCount,1);assert.equal(core.validateBackup("{").valid,false);assert.equal(core.restoreBackup(store,backup,"replace",{operator:"operator",reason:"restore",confirmation:"wrong"},now).restored,false);
r=core.restoreBackup(core.defaultStore(),backup,"merge",{operator:"operator",reason:"restore"},now);assert.equal(r.restored,true);r=core.restoreBackup(store,backup,"replace",{operator:"operator",reason:"restore",confirmation:"REPLACE"},now);assert.equal(r.restored,true);
assert.equal(core.resetStore(store,{operator:"operator",reason:"reset",confirmation:"wrong"},now).reset,false);assert.equal(core.resetStore(store,{operator:"operator",reason:"reset",confirmation:"RESET ALL PHASE24-3"},now).reset,true);
function storage(initial=null,bad=false){let value=initial,writes=0;return{getItem(){return bad&&writes===1?"broken":value},setItem(_k,v){writes++;value=v},removeItem(){value=null},value(){return value}}}
const mem=storage();assert.equal(core.saveStore(store,mem,now).saved,true);assert.equal(core.loadStore(mem).store.records.length,1);assert.equal(core.loadStore(storage("{broken")).parseError,true);
const original=JSON.stringify(core.defaultStore()),fail=storage(original,true);assert.equal(core.saveStore(store,fail,now).saved,false);assert.equal(fail.value(),original);
const code=fs.readFileSync(path.join(root,"phase24-3-manual-acquisition-result-registration-quarantine-storage.js"),"utf8");for(const token of["fetch(","XMLHttpRequest","WebSocket(","EventSource(","sendBeacon(","setInterval(","eval(","new Function(","innerHTML"])assert.equal(code.includes(token),false,token);
const html=fs.readFileSync(path.join(root,"index.html"),"utf8"),privateHtml=fs.readFileSync(path.join(root,"private-local.html"),"utf8"),css=fs.readFileSync(path.join(root,"dashboard.css"),"utf8"),readme=fs.readFileSync(path.join(root,"README.md"),"utf8");assert(html.includes('id="phase24-3-manual-acquisition-result-quarantine"'));assert(html.includes("phase24-3-manual-acquisition-result-registration-quarantine-storage.js"));assert(privateHtml.includes("#phase24-3-manual-acquisition-result-quarantine"));assert(css.includes(".phase243-panel"));assert(readme.includes("Phase24-3"));assert(!core.STATUSES.some(x=>["approved","verified","imported","applied"].includes(x)));assert(core.auditText(store).includes("No external communication"));
console.log("phase24ManualAcquisitionResultQuarantine.test.js: PASS");
})();
