const assert = require("assert");
const fs = require("fs");
const path = require("path");
const core = require("../phase23-2-manual-csv-json-import-preview-validation-core.js");
const root = path.join(__dirname, ".."); const read = (f) => fs.readFileSync(path.join(root, f), "utf8");
const memoryStorage = (initial = {}) => { const data = { ...initial }; return { getItem: (k) => Object.prototype.hasOwnProperty.call(data, k) ? data[k] : null, setItem: (k, v) => { data[k] = String(v); }, data }; };

for (const name of ["x.csv", "X.CSV"]) assert.deepStrictEqual(core.detectFormat({ name }), { supported: true, format: "csv" });
for (const name of ["x.json", "X.JSON"]) assert.deepStrictEqual(core.detectFormat({ name }), { supported: true, format: "json" });
assert.strictEqual(core.detectFormat({ name: "x.txt" }).supported, false);
assert.ok(core.fileInfo({ name: "a.csv", size: core.LIMITS.maxFileBytes + 1 }).tooLarge); assert.ok(core.fileInfo({ name: "a.csv", size: 0 }).empty); assert.strictEqual(core.fileInfo({ name: "a.csv", size: 4, type: "", lastModified: 1 }).format, "csv");

let parsed = core.parseCsv("a,b\n1,2"); assert.ok(parsed.ok); assert.deepStrictEqual(parsed.records[0], Object.assign(Object.create(null), { a: "1", b: "2" }));
assert.ok(core.parseCsv("\uFEFFa,b\r\n1,2\r\n").ok); assert.ok(core.parseCsv("a,b\n1,2\n").ok);
parsed = core.parseCsv('a,b\n"x,y","line1\nline2"'); assert.strictEqual(parsed.records[0].a, "x,y"); assert.strictEqual(parsed.records[0].b, "line1\nline2");
assert.strictEqual(core.parseCsv('a\n"say ""hi"""').records[0].a, 'say "hi"');
assert.ok(!core.parseCsv("a,a\n1,2").ok); assert.ok(!core.parseCsv("a,\n1,2").ok); assert.ok(!core.parseCsv('a\n"bad').ok);
assert.ok(!core.parseCsv(`${Array(core.LIMITS.maxColumns + 1).fill("x").map((x,i)=>x+i).join(",")}\n`).ok);
assert.ok(!core.parseCsv(`a\n${Array(core.LIMITS.maxRows + 1).fill("1").join("\n")}`).ok);

for (const source of ['{"raceId":"r1"}', '[{"raceId":"r1"}]', '{"records":[{"raceId":"r1"}]}', '{"runner":[{"raceId":"r1"}]}']) assert.ok(core.parseJson(source).ok);
assert.ok(!core.parseJson("{bad").ok); let deep = "0"; for(let i=0;i<=core.LIMITS.maxJsonDepth;i++) deep=`{"x":${deep}}`; assert.ok(!core.parseJson(deep).ok);
const poison = core.parseJson('{"records":[{"__proto__":{"polluted":1},"constructor":{"x":1},"prototype":{"x":1},"safe":1}]}'); assert.ok(poison.ok); assert.strictEqual(poison.records[0].safe, 1); assert.ok(!Object.prototype.hasOwnProperty.call(poison.records[0], "__proto__")); assert.ok(!Object.prototype.hasOwnProperty.call(poison.records[0], "constructor"));
const tooMany = JSON.stringify({ records: Array(core.LIMITS.maxRecords + 1).fill({ a: 1 }) }); assert.ok(!core.parseJson(tooMany).ok);

const samples = { meeting: { raceDate:"2026-07-19",meetingNumber:1,dayNumber:1 }, race:{raceId:"r",raceNumber:1,raceName:"x"}, runner:{raceId:"r",horseNumber:1,horseName:"h"}, oddsSnapshot:{raceId:"r",betType:"win",combination:"1",odds:2,capturedAt:"x"}, result:{raceId:"r",horseNumber:1,finishPosition:1,finishStatus:"finished"}, payout:{raceId:"r",betType:"win",combination:"1",payout:200}, acquisitionRecord:{acquisitionId:"a",providerId:"p",acquisitionMode:"manual"} };
for (const [type, sample] of Object.entries(samples)) assert.strictEqual(core.inferDataType(sample).dataType, type, type);
assert.strictEqual(core.inferDataType({ foo: 1 }).dataType, ""); assert.strictEqual(core.normalizeHeader("馬番").target, "horseNumber"); assert.ok(core.normalizeHeader("曖昧").warning);
let normalized = core.normalizeRecord({ "馬番":" １２ ", "馬名":" テスト ", "未知":"保持" }, "runner"); assert.strictEqual(normalized.normalized.horseNumber, 12); assert.strictEqual(normalized.normalized.horseName, "テスト"); assert.strictEqual(normalized.extraFields["未知"], "保持");
assert.strictEqual(core.normalizeNumber("1,230円", "payout"), 1230); assert.strictEqual(core.normalizeNumber("1600m", "distance"), 1600); assert.strictEqual(core.normalizeNumber("55.0kg", "assignedWeight"), 55); assert.strictEqual(core.normalizeNumber("+12kg", "bodyWeightChange"), 12); assert.strictEqual(core.normalizeBoolean("true"), true); assert.strictEqual(core.normalizeBoolean("0"), false);
assert.ok(core.normalizeDate("2026-07-19", false).valid); assert.ok(!core.normalizeDate("2026-02-30", false).valid); assert.ok(core.normalizeDate("2026-07-19T15:40:00", true).timezoneMissing);
assert.strictEqual(core.normalizeRecord({ horseName:"" }, "runner").normalized.horseName, null); assert.strictEqual(core.normalizeRecord({ horseName:"null" }, "runner").normalized.horseName, "null");

const valid = { meeting:{raceDate:"2026-07-19",venueCode:"05"}, race:{raceDate:"2026-07-19",venueCode:"05",raceNumber:1}, runner:{raceId:"r",horseNumber:1,horseName:"h"}, oddsSnapshot:{raceId:"r",betType:"win",combination:"1",odds:2,capturedAt:"2026-07-19T10:00:00+09:00"}, result:{raceId:"r",horseNumber:1,finishPosition:1}, payout:{raceId:"r",betType:"win",combination:"1",payout:200}, acquisitionRecord:{acquisitionId:"a",providerId:"p",acquisitionMode:"manual",status:"acquired"} };
for (const type of core.TYPES) assert.strictEqual(core.validateRecord(valid[type], type).filter((x)=>x.level==="error").length, 0, type);
for (const type of core.TYPES) assert.ok(core.validateRecord({}, type).some((x)=>x.code==="REQUIRED_MISSING"), type);
assert.ok(core.validateRecord({...valid.oddsSnapshot,odds:0},"oddsSnapshot").some((x)=>x.code==="RANGE_INVALID")); assert.ok(core.validateRecord({...valid.oddsSnapshot,popularity:0},"oddsSnapshot").some((x)=>x.code==="RANGE_INVALID"));
for (const field of ["scratched","excluded"]) assert.ok(core.validateRecord({ ...valid.result, [field]:true }, "result").some((x)=>x.code==="FINISH_STATUS_CONFLICT")); assert.ok(core.validateRecord({ ...valid.result, finishStatus:"競走中止" }, "result").some((x)=>x.code==="FINISH_STATUS_CONFLICT"));
for (const [type, record] of [["runner",valid.runner],["oddsSnapshot",valid.oddsSnapshot],["payout",valid.payout],["result",valid.result]]) assert.ok(core.validateConsistency([{normalized:record},{normalized:{...record}}],type).some((x)=>x.code==="DUPLICATE_RECORD"),type);
assert.ok(core.validateConsistency([{normalized:valid.result},{normalized:{...valid.result,horseNumber:2}}],"result").some((x)=>x.code==="FINISH_POSITION_DUPLICATE")); assert.ok(!core.validateConsistency([{normalized:valid.result},{normalized:{...valid.result,horseNumber:2,finishStatus:"同着"}}],"result").some((x)=>x.code==="FINISH_POSITION_DUPLICATE")); assert.ok(core.validateRecord({...valid.acquisitionRecord,requestedAt:"2026-07-20T10:00:00+09:00",receivedAt:"2026-07-19T10:00:00+09:00"},"acquisitionRecord").some((x)=>x.code==="DATETIME_ORDER"));

assert.strictEqual(core.defaultStore().state, "idle"); let state="idle"; for(const next of ["file_selected","reading","parsing","normalizing","validating","preview_ready"]){const r=core.transition(state,next);assert.ok(r.transitioned,`${state}->${next}`);state=r.state;} assert.strictEqual(core.transition("idle","parsing").reason,"invalid_transition"); assert.strictEqual(core.transition("reading","parsing",{processing:true}).reason,"processing_locked"); assert.strictEqual(core.transition("cancelled","reading").reason,"cancelled_locked"); assert.strictEqual(core.transition("validating","preview_ready",{fatalCount:1}).reason,"fatal_present");
let h=core.appendHistory([], {historyId:"h1", action:"selected"}); assert.ok(h.appended); assert.strictEqual(core.appendHistory(h.history,{historyId:"h1"}).reason,"duplicate_history");
assert.ok(core.previousFileDuplicate("abc",[{historyId:"old",fileHash:"abc"}]).duplicate); assert.ok(!core.previousFileDuplicate("",[]).duplicate);
const storage=memoryStorage(), unsafe={state:"preview_ready",content:"FILE BODY",records:[{x:1}],apiKey:"x",Cookie:"x",accessToken:"x",history:h.history}; assert.ok(core.saveStore(unsafe,storage,"2026-07-19T12:00:00+09:00").saved); const raw=storage.data[core.STORAGE_KEY]; for(const forbidden of ["FILE BODY","apiKey","Cookie","accessToken","\"records\""]) assert.ok(!raw.includes(forbidden),forbidden); assert.strictEqual(core.loadStore(storage).store.state,"preview_ready"); assert.ok(core.loadStore(memoryStorage({[core.STORAGE_KEY]:"{bad"})).parseError); assert.ok(core.auditText({...core.defaultStore(),file:{name:"x.csv",size:1,hash:"abc",format:"csv"}}).includes("Phase22へ反映なし"));

const source=read("phase23-2-manual-csv-json-import-preview-validation-core.js")+read("phase23-2-main-dashboard-integration.js"); for(const pattern of [/\bfetch\s*\(/,/XMLHttpRequest/,/\bWebSocket\s*\(/,/\bEventSource\s*\(/,/setInterval\s*\(/]) assert.ok(!pattern.test(source)); assert.ok(!/IPAT/i.test(source)); assert.ok(!/localStorage\.setItem\s*\([^,]*(?:phase22|externalRacingDataAcquisitionSafetyDesign)/i.test(source));
const index=read("index.html"),local=read("private-local.html"),readme=read("README.md"),docs=read("docs/phase23-2-manual-csv-json-import-preview-validation-core.md"); assert.ok(index.includes('id="phase23-manual-csv-json-import-preview-validation"')); assert.ok(local.includes('href="index.html#phase23-manual-csv-json-import-preview-validation"')); assert.ok(index.indexOf('id="phase23-external-racing-data-acquisition-safety-design"')<index.indexOf('id="phase23-manual-csv-json-import-preview-validation"')); assert.ok(local.indexOf("Phase23-1 外部")<local.indexOf("Phase23-2 手動")); assert.ok(index.indexOf("phase23-1-main-dashboard-integration.js")<index.indexOf("phase23-2-manual-csv-json-import-preview-validation-core.js")); assert.ok(index.indexOf("phase23-2-manual-csv-json-import-preview-validation-core.js")<index.indexOf("phase23-2-main-dashboard-integration.js"));
for(const htmlFile of ["index.html","private-local.html","phase22-22-private-local.html"]){const html=read(htmlFile),ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.strictEqual(new Set(ids).size,ids.length);for(const m of html.matchAll(/<script[^>]+src="([^"]+)"/g))if(!/^(?:https?:)?\/\//.test(m[1]))assert.ok(fs.existsSync(path.join(root,m[1])));} assert.ok(readme.includes("Phase23-2")); for(const marker of ["5 MiB","CSV","JSON","認証","Phase22","Phase23-3","PLAN_ONLY"]) assert.ok(docs.includes(marker),marker);
console.log("Phase23-2 manual CSV JSON import preview validation core tests passed");
