const assert = require("assert");
const fs = require("fs");
const path = require("path");
const core = require("../phase22-24-manual-operation-start-approval-record-core.js");
function memoryStorage(initial = {}) { const data = { ...initial }; return { getItem(key) { return Object.prototype.hasOwnProperty.call(data, key) ? data[key] : null; }, setItem(key, value) { data[key] = String(value); } }; }
function checks(checked = true) { return ["owner", "backup", "start", "scope"].map((checkId) => ({ checkId, required: true, checked })); }
function source(overrides = {}) { return { readinessRecordId: "readiness-1", sourceDecisionRecordId: "decision-1", sourceComparisonId: "comparison-1", registeredTrialId: "trial-1", status: "ready_for_manual_start", checks: checks(), sourceSnapshot: { registeredTrialId: "trial-1", handoff: { scope: "limited races", owner: "Owner", monitoringItems: "warnings" } }, updatedAt: "2026-07-19T10:00:00", ...overrides }; }
const sourceStore = { schemaVersion: 1, savedAt: "2026-07-19T10:00:00Z", records: [source(), source({ readinessRecordId: "checking", status: "checking" }), source({ readinessRecordId: "incomplete", checks: checks(false) })] };
function completeDetails(overrides = {}) { return { approver: "Approver", approvalReviewer: "Reviewer", approvedAt: "2026-07-19T11:00:00", approvalReason: "manual approval", notes: "record only", plannedManualStartAt: "2026-07-20T09:00:00", startOwner: "Starter", monitoringOwner: "Monitor", stopDecisionOwner: "Stop owner", rollbackOwner: "Rollback owner", communicationOwner: "Contact", approvalExpiresAt: "2026-07-20T08:30:00", approvalConditions: "all checks remain valid", startProhibitedConditions: "new warning", finalPreStartMemo: "recheck locally", ...overrides }; }
assert.strictEqual(core.STORAGE_KEY, "hashimotoKeibaAi.phase22.manualOperationStartApprovalRecord.v1");
assert.strictEqual(core.eligibleSources(sourceStore).length, 1, "ready and all checks only");
assert.strictEqual(core.normalizeStore({}, { ...sourceStore, records: [source(), source()] }).records.length, 1, "duplicates prevented");
let record = core.normalizeStore({}, sourceStore).records[0]; assert.strictEqual(record.status, "awaiting_manual_start_approval"); assert.strictEqual(record.sourceDecisionRecordId, "decision-1"); assert.strictEqual(record.targetScope, "limited races"); assert.strictEqual(record.finalApproval, ""); assert.strictEqual(record.recommendedResult, "manual_start_approved");
assert.strictEqual(core.updateApprovalDetails(record, completeDetails(), "Approver", "x", "edit").reason, "approval_reviewing_required");
let result = core.transition(record, "approval_reviewing", "Approver", "2026-07-19T10:30:00", "begin review"); assert.ok(result.transitioned); record = result.record;
assert.strictEqual(core.transition(record, "manual_start_approved", "Approver", "2026-07-19T10:31:00", "approve").reason, "approval_fields_incomplete"); assert.ok(core.missingApprovalFields(record).length > 0);
result = core.updateApprovalDetails(record, completeDetails(), "Approver", "2026-07-19T11:00:00", "manual input", "reviewed"); assert.ok(result.updated); record = result.record; assert.strictEqual(core.missingApprovalFields(record).length, 0); assert.ok(record.approvalChangeHistory.length === 1); assert.ok(record.approvalChangeHistory[0].changedFields.includes("approvalConditions"));
assert.strictEqual(record.status, "approval_reviewing", "details do not auto approve"); assert.strictEqual(record.finalApproval, "", "recommendation remains separate");
assert.strictEqual(core.transition(record, "awaiting_manual_start_approval", "Approver", "x", "bad").reason, "invalid_transition");
result = core.transition(record, "manual_start_approved", "Approver", "2026-07-19T11:05:00", "human final approval"); assert.ok(result.transitioned); record = result.record; assert.strictEqual(record.finalApproval, "manual_start_approved"); assert.strictEqual(record.transitionHistory.length, 2); assert.strictEqual(core.transition(record, "approval_reviewing", "Approver", "x", "resume").reason, "terminal_locked"); assert.strictEqual(core.updateApprovalDetails(record, {}, "Approver", "x", "edit").reason, "terminal_locked");
for (const terminal of ["approval_rejected", "on_hold", "blocked"]) { let candidate = core.normalizeStore({}, sourceStore).records[0]; candidate = core.transition(candidate, "approval_reviewing", "Owner", "x", "review").record; const terminalResult = core.transition(candidate, terminal, "Owner", "y", terminal); assert.ok(terminalResult.transitioned, terminal); assert.strictEqual(terminalResult.record.finalApproval, terminal); assert.strictEqual(core.transition(terminalResult.record, "approval_reviewing", "Owner", "z", "resume").reason, "terminal_locked"); }
for (const terminal of ["cancelled", "expired"]) { const candidate = core.normalizeStore({}, sourceStore).records[0]; const terminalResult = core.transition(candidate, terminal, "Owner", "y", terminal); assert.ok(terminalResult.transitioned, terminal); assert.strictEqual(core.transition(terminalResult.record, "approval_reviewing", "Owner", "z", "resume").reason, "terminal_locked"); }
const storage = memoryStorage({ [core.SOURCE_STORAGE_KEY]: JSON.stringify(sourceStore) }); const sourceBefore = storage.getItem(core.SOURCE_STORAGE_KEY); assert.ok(core.saveStore({ records: [record] }, storage, "2026-07-19T12:00:00Z").saved); assert.strictEqual(storage.getItem(core.SOURCE_STORAGE_KEY), sourceBefore, "Phase22-23 not mutated"); const restored = core.loadStore(storage, sourceStore).store.records[0]; assert.strictEqual(restored.status, "manual_start_approved"); assert.strictEqual(restored.details.startOwner, "Starter"); assert.strictEqual(restored.approvalChangeHistory.length, 1); assert.ok(core.loadSource(memoryStorage({ [core.SOURCE_STORAGE_KEY]: "{bad" })).parseError); assert.strictEqual(core.loadSource(memoryStorage({ [core.SOURCE_STORAGE_KEY]: "{bad" })).sourceStore.records.length, 0); assert.ok(core.loadStore(memoryStorage({ [core.STORAGE_KEY]: "{bad" }), sourceStore).rejected); const audit = core.buildAuditText(record); assert.ok(audit.includes("approval record only")); assert.ok(audit.includes("actualStart=false")); assert.ok(audit.includes("history:"));
const root = path.join(__dirname, ".."); const read = (file) => fs.readFileSync(path.join(root, file), "utf8"); const index = read("index.html"), local = read("private-local.html"), css = read("dashboard.css"), readme = read("README.md"); assert.ok(index.includes('id="phase22-manual-operation-start-approval-core"')); assert.ok(index.indexOf('id="phase22-pre-operation-final-readiness-core"') < index.indexOf('id="phase22-manual-operation-start-approval-core"')); assert.ok(local.includes('href="index.html#phase22-manual-operation-start-approval-core"')); assert.ok(local.indexOf('href="index.html#phase22-pre-operation-final-readiness-core"') < local.indexOf('href="index.html#phase22-manual-operation-start-approval-core"')); assert.ok(index.indexOf("phase22-23-pre-operation-final-readiness-check-core.js") < index.indexOf("phase22-24-manual-operation-start-approval-record-core.js")); assert.ok(css.includes(".phase2224-approval-panel")); assert.ok(readme.includes(core.STORAGE_KEY));
for (const htmlFile of ["index.html", "private-local.html", "phase22-22-private-local.html"]) { const html = read(htmlFile); const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map((match) => match[1]); assert.strictEqual(new Set(ids).size, ids.length, `${htmlFile} IDs unique`); for (const match of html.matchAll(/<script[^>]+src="([^"]+)"/g)) { if (!/^(?:https?:)?\/\//.test(match[1])) assert.ok(fs.existsSync(path.join(root, match[1])), `${match[1]} exists`); } }
const safe = core.safety(); ["privateLocal", "planOnly", "protectedMode", "approvalRecordOnly", "humanApprovalOnly"].forEach((key) => assert.strictEqual(safe[key], true)); ["actualApplication", "actualStart", "automaticStart", "automaticApproval", "automaticApply", "automaticProductionRelease", "automaticPurchase", "automaticLearning", "automaticUpdate", "sourceMutation", "predictionMutation", "bettingMutation", "ruleMutation", "learningMutation", "publicUrl", "githubPages", "externalApi"].forEach((key) => assert.strictEqual(safe[key], false));
console.log("Phase22-24 manual operation start approval record core tests passed");
