const assert = require("assert"), fs = require("fs"), path = require("path");
const core = require("../phase23-5-formal-import-preparation-review-core.js");
const root = path.join(__dirname, ".."), read = (file) => fs.readFileSync(path.join(root, file), "utf8");
function storage(initial = {}, fail = false) { const data = { ...initial }; return { data, getItem(key) { return Object.prototype.hasOwnProperty.call(data, key) ? data[key] : null; }, setItem(key, value) { if (fail) throw new Error("quota"); data[key] = String(value); }, removeItem(key) { delete data[key]; } }; }
const samples = { meeting: { meetingId: "m1", raceDate: "2026-07-19", venueCode: "TOK", name: "meeting" }, race: { raceId: "r1", meetingId: "m1", raceNumber: 1, distance: 1600 }, runner: { runnerId: "runner1", raceId: "r1", horseNumber: 1, horseName: "A" }, oddsSnapshot: { raceId: "r1", betType: "win", combination: "1", capturedAt: "2026-07-19T11:00:00+09:00", odds: 2 }, result: { raceId: "r1", horseNumber: 1, finishPosition: 1 }, payout: { raceId: "r1", betType: "win", combination: "1", payoutAmount: 200 }, acquisitionRecord: { acquisitionId: "a1", sourceValidationId: "v1", fileHash: "h1", stagingId: "s1", dataType: "meeting" } };
function gate(type = "meeting", overrides = {}) { return { gateRecordId: `g-${type}`, stagingId: `s-${type}`, stagingVersion: 1, sourceValidationId: `v-${type}`, fileHash: `h-${type}`, dataType: type, providerId: "manual", gateStatus: "import_candidate_ready", importCandidateReady: true, formalImportExecuted: false, validationSummary: { fatal: 0, error: 0, warning: 0 }, referenceSummary: { status: "checked" }, chronologySummary: { status: "checked" }, countSummary: { status: "checked" }, conflictSummary: { status: "no_conflict" }, warningConfirmed: true, gateApprovedBy: "Gate", gateApprovalReason: "checked", gateApprovedAt: "2026-07-19T09:00:00+09:00", ...overrides }; }
function staged(type = "meeting", records = [samples[type]]) { return { stagingId: `s-${type}`, version: 1, stagingStatus: "staged", dataType: type, normalizedRecords: records }; }
const complete = (keys) => Object.fromEntries(keys.map((key) => [key, true]));
const rollback = { rollbackPlanId: "rb1", rollbackRequired: true, rollbackScope: "candidate", rollbackTargetIdentifiers: ["m1"], expectedAffectedRecordCount: 1, backupRequired: true, backupConfirmed: true, preImportSnapshotRequired: true, preImportSnapshotConfirmed: true, restoreOrder: [...core.ORDER].reverse(), verificationAfterRollback: "counts and references", rollbackOwner: "Owner", rollbackReason: "safe restore", rollbackPreparedAt: "2026-07-19T10:00:00+09:00", rollbackNotes: "manual only" };
const review = (overrides = {}) => ({ highImpactConfirmed: true, diffConfirmed: true, countsConfirmed: true, rollbackConfirmed: true, verificationPlanConfirmed: true, approvedBy: "Reviewer", reason: "all preparation checked", approvedAt: "2026-07-19T11:00:00+09:00", protectedMode: true, PLAN_ONLY: true, privateLocalOnly: true, phase22NotAppliedConfirmed: true, formalImportNotExecutedConfirmed: true, noExternalCommunicationConfirmed: true, noAutomaticProcessingConfirmed: true, ...overrides });

assert.strictEqual(core.STORAGE_KEY, "hashimotoKeibaAi.phase23.formalImportPreparationReview.v1"); assert.strictEqual(core.SOURCE_GATE_KEY, "hashimotoKeibaAi.phase23.stagingIntegrityReferenceImportGate.v1");
for (const status of ["rejected", "cancelled", "expired", "gate_approval_in_progress"]) assert.strictEqual(core.eligibleGateRecords({ records: [gate("meeting", { gateStatus: status, importCandidateReady: false })] }).length, 0);
assert.strictEqual(core.eligibleGateRecords({ records: [gate(), gate("race", { formalImportExecuted: true })] }).length, 1);
const snapshot = core.sourceSnapshot(gate()); for (const key of ["gateRecordId", "stagingId", "stagingVersion", "sourceValidationId", "fileHash", "dataType", "providerId", "validationSummary", "warningConfirmed", "gateApprovedBy"]) assert.ok(Object.prototype.hasOwnProperty.call(snapshot, key), key);
assert.strictEqual(core.stagingForGate(gate(), { records: [staged()] }).stagingId, "s-meeting"); assert.strictEqual(core.stagingForGate(gate(), { records: [staged(), staged()] }), null);

const lookup = core.buildLookup({ meeting: [samples.meeting], race: [samples.race], runner: [samples.runner], oddsSnapshot: [], result: [], payout: [], acquisitionRecord: [{ ...samples.acquisitionRecord, stagingId: "v1" }] });
for (const type of core.TYPES) { const context = type === "acquisitionRecord" ? { ...lookup, acquisitionReferenceConfirmed: true } : lookup; assert.strictEqual(core.classifyRecord(type, samples[type], [], context).classification, "new_record", type); assert.strictEqual(core.classifyRecord(type, samples[type], [samples[type]], context).classification, "exact_match", type); }
assert.strictEqual(core.classifyRecord("runner", { ...samples.runner, horseName: "B" }, [samples.runner], lookup).classification, "update_candidate");
assert.strictEqual(core.classifyRecord("meeting", { ...samples.meeting, venueCode: "KYO" }, [samples.meeting], lookup).classification, "conflicting_match");
assert.strictEqual(core.classifyRecord("race", { ...samples.race, meetingId: "missing" }, [], lookup).classification, "missing_dependency");
assert.strictEqual(core.classifyRecord("meeting", samples.meeting, [samples.meeting, samples.meeting], lookup).classification, "ambiguous_match");
assert.strictEqual(core.classifyRecord("unsupported", {}, [], lookup).classification, "unsupported_change"); assert.strictEqual(core.classifyRecord("meeting", samples.meeting, null, lookup).classification, "review_unavailable");
const diff = core.classifyAll("runner", [samples.runner, { ...samples.runner, runnerId: "runner2" }, { ...samples.runner, horseName: "B" }], [samples.runner], lookup); assert.deepStrictEqual([diff.insert, diff.update, diff.skip, diff.conflict, diff.unchanged], [1, 1, 1, 0, 1]);

assert.ok(core.dependencySummary("race", [samples.race], lookup).confirmed); assert.ok(core.dependencySummary("runner", [samples.runner], lookup).confirmed); assert.ok(core.dependencySummary("oddsSnapshot", [samples.oddsSnapshot], lookup).confirmed); assert.ok(core.dependencySummary("result", [samples.result], lookup).confirmed); assert.ok(core.dependencySummary("payout", [samples.payout], lookup).confirmed); assert.ok(core.dependencySummary("acquisitionRecord", [samples.acquisitionRecord], { ...lookup, acquisitionReferenceConfirmed: true }).confirmed);
assert.ok(core.dependencySummary("race", [samples.race], { available: {}, group: {} }).issues.some((item) => item.code === "MISSING_DEPENDENCY")); assert.ok(core.dependencySummary("race", [samples.race], { ...lookup, branchCount: 2 }).issues.some((item) => item.code === "DEPENDENCY_BRANCH")); assert.ok(core.dependencySummary("race", [samples.race], { ...lookup, circular: true }).issues.some((item) => item.code === "CIRCULAR_DEPENDENCY")); assert.ok(core.dependencySummary("race", [samples.race], lookup, ["race", "meeting"]).issues.some((item) => item.code === "PREPARATION_ORDER_VIOLATION"));

assert.strictEqual(core.buildPreparation(gate("meeting", { gateStatus: "rejected", importCandidateReady: false }), staged(), [], {}).reason, "source_gate_not_ready"); assert.strictEqual(core.buildPreparation(gate("meeting", { formalImportExecuted: true }), staged(), [], {}).reason, "source_already_imported");
const gateBefore = JSON.stringify(gate()), stagingBefore = JSON.stringify(staged()); let built = core.buildPreparation(gate(), staged(), [], { context: lookup, rollbackPreparation: rollback, verificationPlan: complete(Object.keys(core.defaultVerificationPlan())), operatorChecklist: complete(core.CHECKLIST) }, new Date("2026-07-19T01:00:00Z")); assert.ok(built.created); assert.strictEqual(JSON.stringify(gate()), gateBefore); assert.strictEqual(JSON.stringify(staged()), stagingBefore); assert.strictEqual(built.record.expectedInsertCount, 1); assert.strictEqual(built.record.formalImportExecuted, false); assert.strictEqual(built.record.phase22Applied, false);
let ready = { ...built.record, preparationStatus: "preparation_completed", rollbackPreparation: rollback, verificationPlan: complete(Object.keys(core.defaultVerificationPlan())), operatorChecklist: complete(core.CHECKLIST), issueCounts: { fatal: 0, error: 0, warning: 0 }, dependencySummary: { confirmed: true }, impactSummary: { level: "medium" }, expectedConflictCount: 0 };
for (const [change, expected] of [[{ impactSummary: { level: "critical" } }, "critical_impact"], [{ impactSummary: { level: "unknown" } }, "unknown_impact"], [{ impactSummary: { level: "high" } }, null], [{ expectedConflictCount: 1 }, "unresolved_conflict"], [{ dependencySummary: { confirmed: false } }, "dependency_confirmation_required"], [{ operatorChecklist: {} }, "operator_checklist_incomplete"], [{ rollbackPreparation: { ...rollback, backupConfirmed: false } }, "rollback_preparation_incomplete"]]) { const problems = core.readyProblems({ ...ready, ...change }, change.impactSummary && change.impactSummary.level === "high" ? review({ highImpactConfirmed: false }) : review()); assert.ok(expected ? problems.includes(expected) : problems.includes("high_impact_confirmation_required")); }
assert.ok(core.readyProblems(ready, review({ approvedBy: "" })).includes("review_approver_required")); assert.ok(core.readyProblems(ready, review({ approvedAt: "2099-01-01T00:00:00+09:00" })).includes("review_datetime_future"));
let finalized = core.finalizePreparation(ready, review(), [], new Date("2026-07-19T02:00:00Z")); assert.ok(finalized.finalized); assert.strictEqual(finalized.record.preparationStatus, "ready_for_formal_import_execution"); assert.strictEqual(finalized.record.formalImportExecuted, false); assert.ok(core.readyProblems(ready, review(), [finalized.record]).includes("duplicate_gate_preparation"));
let state = "awaiting_preparation"; for (const next of ["preparation_in_progress", "preparation_completed", "awaiting_manual_review", "manual_review_in_progress", "ready_for_formal_import_execution"]) { const moved = core.transition(state, next, { humanApproved: true }); assert.ok(moved.transitioned); state = moved.status; } assert.strictEqual(core.transition("cancelled", "preparation_in_progress").reason, "terminal_locked"); assert.strictEqual(core.transition("ready_for_formal_import_execution", "revision_required").reason, "terminal_locked");
assert.ok(core.buildGroup("group", [ready]).created); assert.strictEqual(core.buildGroup("group2", [ready], [{ groupStatus: "awaiting_preparation", gateRecordIds: [ready.gateRecordId] }]).reason, "gate_already_grouped");
let h = core.appendHistory([], { historyId: "h1", action: "x" }); assert.ok(h.appended); assert.strictEqual(core.appendHistory(h.history, { historyId: "h1" }).reason, "duplicate_history");
const dangerous = core.stripDangerous({ APIKey: "x", password: "x", cookie: "x", accessToken: "x", rawRecords: [1], nested: { constructor: "x", safe: 1 } }); assert.strictEqual(dangerous.nested.safe, 1); for (const key of ["APIKey", "password", "cookie", "accessToken", "rawRecords"]) assert.ok(!Object.prototype.hasOwnProperty.call(dangerous, key)); assert.ok(!Object.prototype.hasOwnProperty.call(dangerous.nested, "constructor"));

const keys = { p22: "22", p231: "231", p232: "232", p233: "233", p234: "234", official: "official" }, mem = storage(keys); let saved = core.addRecord(core.defaultStore(), finalized.record, mem, new Date("2026-07-19T03:00:00Z")); assert.ok(saved.saved); assert.strictEqual(core.loadStore(mem).store.records.length, 1); for (const [key, value] of Object.entries(keys)) assert.strictEqual(mem.data[key], value); assert.strictEqual(core.addRecord(saved.store, finalized.record, mem).reason, "duplicate_preparation_id");
const old = JSON.stringify({ schemaVersion: 1, records: [{ importPreparationId: "old" }] }), failedStore = storage({ [core.STORAGE_KEY]: old }, true); assert.ok(!core.saveStore({ records: [finalized.record] }, failedStore).saved); assert.strictEqual(failedStore.data[core.STORAGE_KEY], old); const normalized = core.normalizeStore({ records: [{ ...finalized.record, formalImportExecuted: true, phase22Applied: true }] }); assert.strictEqual(normalized.records[0].formalImportExecuted, false); assert.strictEqual(normalized.records[0].phase22Applied, false); assert.ok(core.auditText(finalized.record).includes("formalImportExecuted=false"));

const code = read("phase23-5-formal-import-preparation-review-core.js") + read("phase23-5-main-dashboard-integration.js"); for (const pattern of [/\bfetch\s*\(/, /XMLHttpRequest/, /\bWebSocket\s*\(/, /\bEventSource\s*\(/, /setInterval\s*\(/]) assert.ok(!pattern.test(code)); assert.ok(!/formalImportExecuted\s*:\s*true/.test(code)); assert.ok(!/(?:insert|update|upsert|delete)(?:One|Many|Record|Data)\s*\(/i.test(code)); assert.ok(!/localStorage\.setItem\s*\([^,]*(?:phase22|stagingIntegrityReferenceImportGate|approvedPreviewStagingStorage)/i.test(code));
const index = read("index.html"), local = read("private-local.html"); assert.ok(index.includes('id="phase23-formal-import-preparation-review"')); assert.ok(local.includes('href="index.html#phase23-formal-import-preparation-review"')); assert.ok(index.indexOf('id="phase23-staging-integrity-reference-import-gate"') < index.indexOf('id="phase23-formal-import-preparation-review"')); assert.ok(index.indexOf("phase23-4-main-dashboard-integration.js") < index.indexOf("phase23-5-formal-import-preparation-review-core.js")); assert.ok(index.indexOf("phase23-5-formal-import-preparation-review-core.js") < index.indexOf("phase23-5-main-dashboard-integration.js"));
for (const file of ["index.html", "private-local.html", "phase22-22-private-local.html"]) { const html = read(file), ids = [...html.matchAll(/\bid="([^"]+)"/g)].map((match) => match[1]); assert.strictEqual(ids.length, new Set(ids).size); for (const match of html.matchAll(/<script[^>]+src="([^"]+)"/g)) if (!/^(?:https?:)?\/\//.test(match[1])) assert.ok(fs.existsSync(path.join(root, match[1])), match[1]); }
console.log("Phase23-5 formal import preparation review core tests passed");
