const assert = require("assert");
const fs = require("fs");
const path = require("path");
const core = require("../phase22-23-pre-operation-final-readiness-check-core.js");
function memoryStorage(initial = {}) { const data = { ...initial }; return { getItem(key) { return Object.prototype.hasOwnProperty.call(data, key) ? data[key] : null; }, setItem(key, value) { data[key] = String(value); } }; }
function source(overrides = {}) { return { decisionRecordId: "decision-1", sourceComparisonId: "comparison-1", registeredTrialId: "trial-1", status: "finalized", finalDecision: "limited_application_approved", decisionMaker: "Owner", decidedAt: "2026-07-19T10:00:00", decisionReason: "approved", handoff: { owner: "Owner", backupOwner: "Backup", startAt: "2026-07-20T10:00:00", reviewAt: "2026-07-27T10:00:00", scope: "limited", monitoringItems: "errors", stopConditions: "warning", rollbackProcedure: "manual rollback", communicationPlan: "phone" }, ...overrides }; }
const sourceStore = { schemaVersion: 1, savedAt: "2026-07-19T10:00:00Z", records: [source(), source({ decisionRecordId: "not-final", status: "handoff_planned" }), source({ decisionRecordId: "rejected", finalDecision: "limited_application_rejected" }), source({ decisionRecordId: "no-handoff", handoff: { owner: "Owner" } })] };
assert.strictEqual(core.STORAGE_KEY, "hashimotoKeibaAi.phase22.preOperationFinalReadinessCheck.v1");
assert.strictEqual(core.eligibleSources(sourceStore).length, 1, "only finalized approved complete handoff is eligible");
assert.strictEqual(core.normalizeStore({}, { ...sourceStore, records: [source(), source()] }).records.length, 1, "duplicate source record is generated once");
let record = core.normalizeStore({}, sourceStore).records[0];
assert.strictEqual(record.status, "awaiting_readiness_check"); assert.strictEqual(record.checks.length, 13); assert.strictEqual(core.uncheckedItems(record).length, 13); assert.ok(core.isSafetyValid(record.safety));
assert.strictEqual(core.updateChecks(record, {}, "Owner", "2026-07-19T11:00:00", "check").reason, "checking_required");
let result = core.transition(record, "checking", "Owner", "2026-07-19T11:00:00", "begin manual check"); assert.ok(result.transitioned); record = result.record;
assert.strictEqual(core.transition(record, "ready_for_manual_start", "Owner", "2026-07-19T11:01:00", "ready").reason, "required_checks_incomplete");
const allChecked = Object.fromEntries(core.REQUIRED_CHECKS.map((check) => [check.checkId, true]));
result = core.updateChecks(record, allChecked, "Owner", "2026-07-19T11:05:00", "manually verified", "evidence retained"); assert.ok(result.updated); record = result.record;
assert.strictEqual(core.uncheckedItems(record).length, 0); assert.strictEqual(record.checkHistory.length, 13); assert.strictEqual(record.operationHistory.length, 2);
assert.strictEqual(record.status, "checking", "checks do not automatically set ready");
assert.strictEqual(core.transition(record, "awaiting_readiness_check", "Owner", "2026-07-19T11:06:00", "bad").reason, "invalid_transition");
result = core.transition(record, "ready_for_manual_start", "Owner", "2026-07-19T11:10:00", "human ready decision"); assert.ok(result.transitioned); record = result.record;
assert.strictEqual(record.status, "ready_for_manual_start"); assert.strictEqual(record.transitionHistory.length, 2);
assert.strictEqual(core.transition(record, "checking", "Owner", "2026-07-19T11:11:00", "resume").reason, "terminal_locked");
assert.strictEqual(core.updateChecks(record, { owner_confirmed: false }, "Owner", "2026-07-19T11:12:00", "change").reason, "terminal_locked");
for (const terminal of ["on_hold", "blocked", "cancelled", "expired"]) { let candidate = core.normalizeStore({}, sourceStore).records[0]; if (["on_hold", "blocked"].includes(terminal)) candidate = core.transition(candidate, "checking", "Owner", "x", "start").record; const terminalResult = core.transition(candidate, terminal, "Owner", "y", terminal); assert.ok(terminalResult.transitioned, terminal); assert.strictEqual(core.transition(terminalResult.record, "checking", "Owner", "z", "resume").reason, "terminal_locked"); }

const storage = memoryStorage({ [core.SOURCE_STORAGE_KEY]: JSON.stringify(sourceStore) }); const sourceBefore = storage.getItem(core.SOURCE_STORAGE_KEY); const save = core.saveStore({ schemaVersion: 1, records: [record] }, storage, "2026-07-19T12:00:00Z"); assert.ok(save.saved); assert.strictEqual(storage.getItem(core.SOURCE_STORAGE_KEY), sourceBefore, "Phase22-22 source not mutated"); const restored = core.loadStore(storage, sourceStore); assert.strictEqual(restored.store.records[0].status, "ready_for_manual_start"); assert.strictEqual(restored.store.records[0].checkHistory.length, 13); assert.ok(core.loadSource(memoryStorage({ [core.SOURCE_STORAGE_KEY]: "{bad" })).parseError); assert.strictEqual(core.loadSource(memoryStorage({ [core.SOURCE_STORAGE_KEY]: "{bad" })).sourceStore.records.length, 0); assert.ok(core.loadStore(memoryStorage({ [core.STORAGE_KEY]: "{bad" }), sourceStore).rejected); const audit = core.buildAuditText(record); assert.ok(audit.includes("ready_for_manual_start")); assert.ok(audit.includes("PLAN_ONLY=true")); assert.ok(audit.includes("history:"));

const root = path.join(__dirname, ".."); const read = (file) => fs.readFileSync(path.join(root, file), "utf8"); const index = read("index.html"), local = read("private-local.html"), css = read("dashboard.css"), readme = read("README.md"); assert.ok(index.includes('id="phase22-pre-operation-final-readiness-core"')); assert.ok(index.indexOf('id="phase22-limited-application-final-decision-handoff-main-core"') < index.indexOf('id="phase22-pre-operation-final-readiness-core"')); assert.ok(local.includes('href="index.html#phase22-pre-operation-final-readiness-core"')); assert.ok(local.indexOf('href="phase22-22-private-local.html"') < local.indexOf('href="index.html#phase22-pre-operation-final-readiness-core"')); assert.ok(index.indexOf("phase22-22a-main-dashboard-integration.js") < index.indexOf("phase22-23-pre-operation-final-readiness-check-core.js")); assert.ok(css.includes(".phase2223-readiness-panel")); assert.ok(readme.includes(core.STORAGE_KEY));
for (const htmlFile of ["index.html", "private-local.html", "phase22-22-private-local.html"]) { const html = read(htmlFile); const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map((match) => match[1]); assert.strictEqual(new Set(ids).size, ids.length, `${htmlFile} IDs unique`); for (const match of html.matchAll(/<script[^>]+src="([^"]+)"/g)) { if (!/^(?:https?:)?\/\//.test(match[1])) assert.ok(fs.existsSync(path.join(root, match[1])), `${match[1]} exists`); } }
const safe = core.safety(); ["privateLocal", "planOnly", "protectedMode", "readinessCheckOnly", "humanReadyDecisionOnly"].forEach((key) => assert.strictEqual(safe[key], true)); ["automaticStart", "automaticApply", "automaticProductionRelease", "automaticPurchase", "automaticLearning", "automaticUpdate", "sourceMutation", "predictionMutation", "bettingMutation", "ruleMutation", "learningMutation", "publicUrl", "githubPages", "externalApi"].forEach((key) => assert.strictEqual(safe[key], false));
console.log("Phase22-23 pre-operation final readiness check core tests passed");
