const assert=require("assert"),fs=require("fs"),path=require("path"),core=require("../phase23-import-audit-flow-final-integration-check.js");
const root=path.join(__dirname,".."),read=f=>fs.readFileSync(path.join(root,f),"utf8");function memory(initial={},fail=false){const data={...initial};return{data,getItem:k=>Object.prototype.hasOwnProperty.call(data,k)?data[k]:null,setItem(k,v){if(fail)throw Error("quota");data[k]=String(v)},removeItem(){throw Error("physical deletion forbidden")}}}
assert.strictEqual(core.PHASES.length,10);assert.strictEqual(new Set(core.PHASES.map(p=>p.key)).size,10);assert.strictEqual(core.CHECK_DEFS.length,20);
const artifacts={"index.html":read("index.html"),"private-local.html":read("private-local.html"),"dashboard.css":read("dashboard.css"),"README.md":read("README.md")};for(const p of core.PHASES)for(const f of[p.core,p.ui,p.doc])artifacts[f]=read(f);const inspection=core.inspectArtifacts(artifacts);assert.ok(inspection.passed,JSON.stringify(inspection.findings));assert.strictEqual(inspection.phaseCount,10);assert.ok(core.inspectArtifacts({...artifacts,[core.PHASES[0].core]:undefined}).findings.some(f=>f.code==="file_missing"));
let made=core.createRecord({reviewer:"Reviewer"},new Date("2026-07-24T00:00:00Z"));assert.ok(made.created);let r=made.record;assert.strictEqual(r.status,"awaiting_integration_review");assert.strictEqual(r.checks.length,20);let x=core.startReview(r,{reviewer:"Reviewer",reviewedAt:"2026-07-24T00:01:00Z",reason:"manual integration review"},new Date("2026-07-24T01:00:00Z"));assert.ok(x.started);r=x.record;
assert.strictEqual(core.recordCheck(r,"missing",{reviewer:"R",checkedAt:"2026-07-24",status:"manual_confirmed",note:"x"}).reason,"check_not_found");for(const c of r.checks){x=core.recordCheck(r,c.checkId,{reviewer:"Reviewer",checkedAt:"2026-07-24T00:02:00Z",status:"manual_confirmed",note:"checked",evidenceRefs:["test-log"],rawPayload:{secret:"x"},password:"x"});assert.ok(x.recorded);r=x.record}assert.ok(!JSON.stringify(r).includes("password"));
const base={reviewer:"Reviewer",reviewedAt:"2026-07-24T00:03:00Z",reason:"all checked",unresolvedIssues:[],remainingRisks:["low"],safetyBoundaryConfirmed:true};let passed=core.recordDecision(r,"integration_passed",base,new Date("2026-07-24T01:00:00Z"));assert.ok(passed.recorded);let closed=core.closeRecord(passed.record,{reviewer:"Reviewer",closedAt:"2026-07-24",reason:"complete"});assert.ok(closed.closed);assert.strictEqual(core.cancelRecord(closed.record,{reviewer:"R",reason:"x"}).reason,"terminal_locked");
let warningRecord=core.startReview(core.createRecord({reviewer:"R",integrationTargetId:"warning-target"}).record,{reviewer:"R",reviewedAt:"2026-07-24",reason:"review"}).record;x=core.recordCheck(warningRecord,"cores",{reviewer:"R",checkedAt:"2026-07-24",status:"warning",note:"minor"});warningRecord=x.record;let warning=core.recordDecision(warningRecord,"integration_passed_with_warnings",{...base,warningContent:"minor",warningImpact:"none",warningPolicy:"monitor",owner:"Owner"});assert.ok(warning.recorded);assert.strictEqual(core.closeRecord(warning.record,{reviewer:"R",closedAt:"2026-07-24",reason:"x"}).reason,"passing_decision_required");warning=core.acceptWarnings(warning.record,{reviewer:"R",acceptedAt:"2026-07-24",reason:"accepted"});assert.ok(warning.accepted);assert.ok(core.closeRecord(warning.record,{reviewer:"R",closedAt:"2026-07-24",reason:"accepted"}).closed);
function active(target){return core.startReview(core.createRecord({reviewer:"R",integrationTargetId:target}).record,{reviewer:"R",reviewedAt:"2026-07-24",reason:"review"}).record}assert.ok(core.recordDecision(active("rework"),"integration_rework_required",{...base,targetPhases:["23-6"],targetFiles:["phase23-6.js"],reworkReason:"fix",owner:"O",dueAt:"2026-08-01"}).recorded);assert.ok(core.recordDecision(active("blocked"),"integration_blocked",{...base,blockReason:"dependency",dependencies:"manual result",unblockConditions:"result supplied"}).recorded);assert.ok(core.recordDecision(active("failed"),"integration_failed",{...base,failureReason:"broken",impactScope:"flow",unresolvedIssues:[{severity:"error",summary:"broken"}],nextManualDecision:"repair plan"}).recorded);
const originals={formal:"same",snapshot:"same",pending:"same",phase22:"same",p232:"same",p2311:"same"},mem=memory(originals);let saved=core.addRecord(core.defaultStore(),made.record,mem);assert.ok(saved.saved);for(const[k,v]of Object.entries(originals))assert.strictEqual(mem.data[k],v);assert.strictEqual(core.addRecord(saved.store,{...made.record,integrationRecordId:"other"},mem).reason,"active_integration_record_exists");const old=mem.data[core.STORAGE_KEY],fail=memory({[core.STORAGE_KEY]:old},true);assert.strictEqual(core.saveStore({records:[closed.record]},fail).saved,false);assert.strictEqual(fail.data[core.STORAGE_KEY],old);assert.strictEqual(core.replaceRecord({records:[closed.record]},{...closed.record,closedBy:"other"},mem).reason,"terminal_locked");
const index=artifacts["index.html"],local=artifacts["private-local.html"],code=read("phase23-import-audit-flow-final-integration-check.js")+read("phase23-12-main-dashboard-integration.js");assert.ok(index.includes('id="phase23-import-audit-flow-final-integration-check"'));assert.ok(local.includes('href="index.html#phase23-import-audit-flow-final-integration-check"'));assert.ok(index.indexOf('id="phase23-audit-follow-up-final-closure-handoff"')<index.indexOf('id="phase23-import-audit-flow-final-integration-check"'));assert.ok(index.indexOf("phase23-11-main-dashboard-integration.js")<index.indexOf("phase23-import-audit-flow-final-integration-check.js"));for(const pattern of[/\bfetch\s*\(/,/XMLHttpRequest/,/\bWebSocket\s*\(/,/\bEventSource\s*\(/,/sendBeacon/,/setInterval\s*\(/,/addEventListener\s*\(\s*["']storage/,/\.removeItem\s*\(/])assert.ok(!pattern.test(code));for(const file of["index.html","private-local.html","phase22-22-private-local.html"]){const html=read(file),ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.strictEqual(ids.length,new Set(ids).size,file);for(const m of html.matchAll(/<script[^>]+src="([^"]+)"/g))if(!/^(?:https?:)?\/\//.test(m[1]))assert.ok(fs.existsSync(path.join(root,m[1])),m[1])}
console.log("Phase23-12 import audit flow final integration check tests passed");
