"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path");
const core=require("../phase25-2-external-data-source-candidate-registration-management.js");
const phase251=require("../phase25-1-purpose-scope-safety-boundary-definition.js");
const now=new Date("2026-07-28T00:00:00Z"),base={sourceCandidateId:"SAMPLE-001",sourceName:"SAMPLE LOCAL ONLY",sourceType:"local_file_source",dataCategory:["odds","race_result"],sourceUrlReference:"https://example.invalid/reference-only",providerName:"DUMMY",description:"LOCAL ONLY",acquisitionMethodCandidate:"local_file_only",authenticationRequirement:"none",registrationStatus:"draft",riskLevel:"low",createdBy:"human",reason:"manual test"};
let store=core.defaultStore(),r=core.createCandidate(store,base,now);assert.equal(r.created,true);store=r.store;assert.equal(store.auditLogs[0].action,"candidate_registered");assert.equal(r.candidate.externalAcquisitionExecutionAllowed,false);
assert(core.createCandidate(store,base,now).errors.includes("duplicate_source_candidate_id"));
assert(core.createCandidate(store,{...base,sourceCandidateId:"x",sourceName:""},now).errors.includes("sourceName_required"));
assert(core.createCandidate(store,{...base,sourceCandidateId:"x",sourceType:"bad"},now).errors.includes("invalid_source_type"));
assert(core.createCandidate(store,{...base,sourceCandidateId:"x",notes:"javascript:alert(1)"},now).errors.includes("notes_executable_text_rejected"));
r=core.updateCandidate(store,"SAMPLE-001",{registrationStatus:"approved_for_method_review"},{updatedBy:"human",reason:"manual review"},now);assert.equal(r.updated,true);store=r.store;
let gate=core.evaluateMethodReviewGate(r.candidate,{...phase251.SAFETY_BOUNDARY,networkCommunicationAllowed:false});assert.equal(gate.eligibleForMethodReview,true);assert.equal(gate.externalAcquisitionExecutionAllowed,false);
r=core.recordGateEvaluation(store,"SAMPLE-001",{...phase251.SAFETY_BOUNDARY,networkCommunicationAllowed:false},"human","manual gate",now);assert.equal(r.recorded,true);assert.equal(r.store.auditLogs.at(-1).action,"safety_gate_evaluated");
for(const patch of[{sourceType:"prohibited"},{acquisitionMethodCandidate:"prohibited"},{usagePermissionStatus:"prohibited"},{termsReviewStatus:"unacceptable"},{robotsReviewStatus:"unacceptable"},{accessRestrictionReviewStatus:"unacceptable"},{riskLevel:"critical"}])assert.equal(core.evaluateMethodReviewGate({...r.candidate,...patch},{...phase251.SAFETY_BOUNDARY,networkCommunicationAllowed:false}).eligibleForMethodReview,false);
r=core.updateCandidate(store,"SAMPLE-001",{registrationStatus:"prohibited"},{updatedBy:"human",reason:"blocked"},now);assert.equal(r.updated,true);assert.equal(r.store.auditLogs.at(-1).action,"candidate_marked_prohibited");assert.equal(core.updateCandidate(r.store,"SAMPLE-001",{notes:"change"},{updatedBy:"human",reason:"x"},now).updated,false);
const memory={v:null,getItem(){return this.v},setItem(_k,v){this.v=v}};assert.equal(core.saveStore(store,memory,now).saved,true);assert.equal(core.loadStore(memory).store.candidates.length,1);
const root=path.resolve(__dirname,".."),source=fs.readFileSync(path.join(root,"phase25-2-external-data-source-candidate-registration-management.js"),"utf8"),html=fs.readFileSync(path.join(root,"index.html"),"utf8"),privateHtml=fs.readFileSync(path.join(root,"private-local.html"),"utf8"),readme=fs.readFileSync(path.join(root,"README.md"),"utf8");
for(const token of["fetch(","XMLHttpRequest","WebSocket(","EventSource(","sendBeacon(","setInterval("])assert.equal(source.includes(token),false,token);
assert(html.includes('id="phase25-2-source-candidate-management"'));assert(html.includes("phase25-2-external-data-source-candidate-registration-management.js"));assert(privateHtml.includes("#phase25-2-source-candidate-management"));assert(readme.includes("Phase25-2 External Data Source Candidate Management"));
console.log("phase25ExternalDataSourceCandidateManagement.test.js: PASS");
