"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path");
const p261=require("../phase26-1-external-data-acquisition-boundary.js"),p262=require("../phase26-2-manual-acquisition-request-precheck-core.js"),p263=require("../phase26-3-manual-acquisition-approval-prestart-record-core.js"),core=require("../phase26-4-manual-acquisition-start-request-final-check-core.js");
const root=path.resolve(__dirname,".."),clock={now:()=>new Date("2026-08-05T02:00:00Z")},op={performedBy:"owner",reason:"manual",explicitConfirmation:true};
const request={...p262.createDraftRequest({requestId:"r1",createdBy:"owner",acquisitionMethod:"manual_entry",sourceTrustLevel:"official_source",sourceName:"Official",meetingDate:"2026-08-05",racecourse:"Tokyo",raceNumber:11,targetDataTypes:["出馬表"],dataTimepoint:"pre_race",expectedRecordCount:18,purpose:"prediction_input_support",consentConfirmed:true,termsCheckConfirmed:true,accessRestrictionCheckConfirmed:true},clock),requestStatus:"ready_for_manual_request",validationResult:"ready_for_manual_request",blockingReasons:[]};
const p3checks=Object.fromEntries(p263.PRESTART_CHECKS.map(k=>[k,true]));
const approval={...p263.createApprovalDraft(request,{approvedBy:"owner",approvedAt:"2026-08-05T01:00:00Z",approvalReason:"ok",reviewerRole:"Owner",preStartChecklist:p3checks,cancellationConditions:"mismatch",expirationAt:"2026-08-06T06:00:00Z"},clock),approvalStatus:"ready_for_manual_start_request",preStartValidationResult:"ready_for_manual_start_request",preStartBlockingReasons:[]};
const checks=Object.fromEntries(core.FINAL_EXECUTION_CHECKS.map(k=>[k,true]));
const input={requestedBy:"owner",requestedAt:"2026-08-05T01:30:00Z",startReason:"manual request",operatorRole:"Owner",finalExecutionChecklist:checks,stopConditions:"stop on mismatch",cancellationConditions:"cancel on mismatch",allowedExecutionWindowStart:"2026-08-05T03:00:00Z",allowedExecutionWindowEnd:"2026-08-05T05:00:00Z",expirationAt:"2026-08-06T06:00:00Z"};
assert.strictEqual(core.PHASE261_DEFINITION.safetyBoundary,p261.definition().safetyBoundary);assert.strictEqual(core.PHASE262_REFERENCE,p262);assert.strictEqual(core.PHASE263_REFERENCE,p263);
assert(core.validateApprovalRecord(approval,clock).valid);
for(const s of["approval_blocked","cancelled","expired"])assert(!core.validateApprovalRecord({...approval,approvalStatus:s},clock).valid,s);
assert(!core.validateApprovalRecord({...approval,preStartBlockingReasons:["x"]},clock).valid);
assert(!core.validateApprovalRecord({...approval,approvedBy:""},clock).valid);
for(const k of["acquisitionStarted","acquisitionExecuted","acquisitionCompleted"])assert(!core.validateApprovalRecord({...approval,[k]:true},clock).valid,k);
function evaluate(changes={},a=approval){const d=core.createStartRequestDraft(a,{...input,...changes},clock);return core.evaluateFinalPreexecutionCheck(a,d,op,clock)}
assert.equal(evaluate({requestedBy:""}).finalValidationResult,"blocked_by_missing_requester");
for(const requestedBy of["system","auto","bot","scheduler","background"])assert.equal(evaluate({requestedBy}).finalValidationResult,"blocked_by_reserved_requester");
assert.equal(evaluate({requestedAt:"2026-08-05T03:00:00Z"}).finalValidationResult,"blocked_by_invalid_request_time");
assert.equal(evaluate({startReason:""}).finalValidationResult,"blocked_by_missing_start_reason");
assert.equal(evaluate({operatorRole:""}).finalValidationResult,"blocked_by_missing_operator_role");
assert.equal(evaluate({allowedExecutionWindowEnd:"2026-08-05T02:30:00Z"}).finalValidationResult,"blocked_by_invalid_execution_window");
assert.equal(evaluate({}, {...approval,requestSnapshot:{...approval.requestSnapshot,credentialsRequired:true}}).finalValidationResult,"blocked_by_credentials_requirement");
assert.equal(evaluate({}, {...approval,externalCommunicationEnabled:true}).finalValidationResult,"blocked_by_safety_flag_mismatch");
const recorded=evaluate();assert(recorded.recorded);assert.equal(recorded.record.startRequestStatus,"start_request_recorded");assert(recorded.record.selfRequest);
const begun=core.beginFinalCheck(recorded.record,op,clock);assert(begun.transitioned);
assert(!core.completeFinalCheck({...begun.record,finalExecutionChecklist:{...checks,finalHumanConfirmation:false}},op,clock).completed);
const complete=core.completeFinalCheck(begun.record,op,clock);assert(complete.completed);assert.equal(complete.record.startRequestStatus,"ready_for_manual_execution_request");assert(!core.beginFinalCheck(complete.record,op,clock).transitioned);
for(const[k,v]of Object.entries({...core.SAFE_FLAGS}))assert.strictEqual(complete.record[k],v,k);
const polluted={...approval,apiKey:"x",Cookie:"x",password:"x",token:"x",session:"x",acquiredData:[1],formalData:[1],externalResponse:[1]};
for(const snapshot of[core.makeApprovalSnapshot(polluted),core.makeRequestSnapshot({...polluted,requestSnapshot:{...polluted.requestSnapshot,apiKey:"x",Cookie:"x",acquiredData:[1],externalResponse:[1]}})])for(const k of["apiKey","Cookie","password","token","session","acquiredData","formalData","externalResponse"])assert(!Object.prototype.hasOwnProperty.call(snapshot,k),k);
assert.equal(core.getStartRequestSummary(complete.record).notice,"ready_for_manual_execution_requestは取得開始・実行許可を意味しません");
const source=fs.readFileSync(path.join(root,"phase26-4-manual-acquisition-start-request-final-check-core.js"),"utf8"),html=fs.readFileSync(path.join(root,"private-local.html"),"utf8"),css=fs.readFileSync(path.join(root,"dashboard.css"),"utf8"),readme=fs.readFileSync(path.join(root,"README.md"),"utf8");
for(const t of["fetch(","XMLHttpRequest","WebSocket(","EventSource(","sendBeacon(","setInterval(","Worker("])assert(!source.includes(t),t);
for(const name of["startAcquisition","authorizeAcquisition","executeAcquisition","runAcquisition","downloadData","fetchData","callApi","scrapeData","scheduleAcquisition","completeAcquisition","setStartAuthorizedTrue","setExecutionAuthorizedTrue"])assert.equal(core[name],undefined);
for(const marker of['id="phase26-4-manual-acquisition-start-request-final-check"','id="phase264-start-request-form"',"開始要求者","開始要求日時","開始理由","操作者役割","自己開始要求","承認記録サマリー","approvalSnapshot","requestSnapshot","実行前最終チェックリスト","実行可能時間帯","停止条件","取消条件","有効期限","最終判定結果","finalBlockingReasons","開始要求サマリー","startAuthorized = false","executionAuthorized = false","ready_for_manual_execution_requestは取得開始・実行許可を意味しません"])assert(html.includes(marker),marker);
assert(html.includes("phase26-4-manual-acquisition-start-request-final-check-core.js"));assert(css.includes(".phase264-panel"));assert(readme.includes("Phase26-4 Manual Acquisition Start Request and Final Preexecution Check Core"));
console.log("phase26ManualAcquisitionStartRequestFinalCheckCore.test.js: PASS");
