"use strict";
const assert=require("assert"),fs=require("fs"),vm=require("vm"),path=require("path"),{createRequire}=require("module");
const real=require("../phase31-8-phase31-post-start-stabilization-review-core.js"),p317=require("../phase31-7-phase31-post-start-verification-acceptance-core.js"),p316=require("../phase31-6-phase31-post-start-verification-decision-core.js");
const code=fs.readFileSync(require.resolve("../phase31-8-phase31-post-start-stabilization-review-core.js"),"utf8"),acceptanceCode=fs.readFileSync(require.resolve("../phase31-7-phase31-post-start-verification-acceptance-core.js"),"utf8");
const copy=v=>JSON.parse(JSON.stringify(v)),NOW="2027-02-08T00:00:00Z",options={now:()=>NOW},human={performedBy:"operator",performedAt:NOW,reason:"explicit manual stabilization review",explicitConfirmation:true};
// Isolate only the older decision validator. Phase31-7 generation, completion,
// safety, snapshot, audit and reference validation remain the actual implementation.
const decisionDependency={...p316,integrityIntact(s){
 if(!s||s.phase315SourceSnapshot?.chainValid!==true)return false;
 const body=copy(s);delete body.phase31PostStartVerificationDecisionSnapshot;delete body.phase31PostStartVerificationDecisionSnapshotHash;
 return p316.computeSnapshotHash(body)===s.phase31PostStartVerificationDecisionSnapshotHash&&p316.computeSnapshotHash(s.phase31PostStartVerificationDecisionSnapshot)===s.phase31PostStartVerificationDecisionSnapshotHash;
}};
const acceptanceSandbox={module:{exports:{}},require:id=>{assert.strictEqual(id,"./phase31-6-phase31-post-start-verification-decision-core.js");return decisionDependency}};
vm.runInNewContext(acceptanceCode,acceptanceSandbox);const acceptance=acceptanceSandbox.module.exports;
let forbiddenCalls=0;const forbidden=()=>{forbiddenCalls++;throw Error("forbidden external/automatic operation or implicit clock")};
class ExplicitDate extends Date{constructor(...args){if(!args.length)forbidden();super(...args)}static now(){return forbidden()}}
function load(dependency=acceptance){
 const sandbox={module:{exports:{}},require:id=>{assert.strictEqual(id,"./phase31-7-phase31-post-start-verification-acceptance-core.js");return dependency},Date:ExplicitDate,fetch:forbidden,XMLHttpRequest:forbidden,WebSocket:forbidden,EventSource:forbidden,setTimeout:forbidden,setInterval:forbidden,Worker:forbidden,navigator:{sendBeacon:forbidden},localStorage:{getItem:forbidden,setItem:forbidden}};
 vm.runInNewContext(code,sandbox);return sandbox.module.exports;
}
const core=load();
function evidence(k){const e={confirmed:true,confirmedBy:"reviewer",confirmedAt:NOW};return k==="gitStateEvidence"?{...e,branch:"codex/review",headCommit:"175f488"}:k==="workingTreeEvidence"?{...e,status:"clean",clean:true}:k==="mainOriginMainAlignmentEvidence"?{...e,mainCommit:"175f488",originMainCommit:"175f488",aligned:true}:{...e,summary:"required tests passed",passed:true}}
function stamp(r,prefix="phase31PostStartStabilizationReview",sourceField="phase317SourceSnapshot"){
 const body=copy(r);delete body[prefix+"Snapshot"];delete body[prefix+"SnapshotHash"];if(sourceField)delete body[sourceField];return {...r,[prefix+"Snapshot"]:body,[prefix+"SnapshotHash"]:core.computeSnapshotHash(body)};
}
function source(){
 let d={...p316.SAFETY,safetyBoundary:copy(p316.SAFETY_BOUNDARY),phase:"phase31",stage:p316.CURRENT_STAGE,nextStage:p316.NEXT_STAGE,phase31PostStartVerificationDecisionStatus:p316.STATES[3],phase31PostStartVerificationDecisionResult:p316.RESULTS[0],phase31PostStartVerificationDecisionVersion:p316.SCHEMA_VERSION,schemaVersion:p316.SCHEMA_VERSION,phase31Started:true,manualPhase31StartCompleted:true,canProceedToNextStage:true,rollbackPoint:"rollback",recoveryPoint:"recovery",unresolvedIssues:[],criticalIssues:[],blockingConditions:[],phase315SourceSnapshot:{chainValid:true}};
 for(const k of acceptance.REFERENCE_IDS.concat(acceptance.UPSTREAM_FIELDS))if(!d[k])d[k]=k+"-1";
 d=stamp(d,"phase31PostStartVerificationDecision",null);
 const data={};for(const k of acceptance.ACCEPTANCE_FIELDS)data[k]=k;for(const k of acceptance.REQUIRED_TRUE)data[k]=true;for(const k of acceptance.ISSUE_FIELDS)data[k]=[];
 for(const k of Object.keys(acceptance.EVIDENCE_FIELDS))data[k]=evidence(k);
 Object.assign(data,{rollbackPoint:d.rollbackPoint,recoveryPoint:d.recoveryPoint,correctionRequired:false,rollbackRequired:false});
 let r=acceptance.createPostStartAcceptanceRecord(d,data,human,options,[]);assert(r.created,r.reasons.join());r=acceptance.beginPostStartAcceptance(r.record,human,options);assert(r.transitioned);r=acceptance.submitPostStartAcceptanceForReview(r.record,human,options);assert(r.transitioned);
 r=acceptance.decidePostStartAcceptance(r.record,{result:acceptance.RESULTS[0],canProceedToNextStage:true,nextStageCandidate:acceptance.NEXT_STAGE,acceptanceSummary:"accepted manually",acceptedBy:"operator",acceptedAt:NOW,acceptanceReason:"evidence checked",reviewedBy:"reviewer",reviewedAt:NOW},human,options);assert(r.accepted,r.reasons.join());assert(acceptance.integrityIntact(r.record));return copy(r.record);
}
const src=source(),sourceBefore=JSON.stringify(src);
function input(s=src,patch={}){const r={};for(const k of core.REVIEW_FIELDS)r[k]=k;for(const k of core.REQUIRED_TRUE)r[k]=true;for(const k of core.ARRAY_FIELDS)r[k]=[];for(const k of Object.keys(core.EVIDENCE_FIELDS))r[k]=evidence(k);return {...r,rollbackPoint:s.rollbackPoint,recoveryPoint:s.recoveryPoint,...patch}}
function completion(result=core.RESULTS[0]){return {result,canProceedToNextStage:result===core.RESULTS[0],reviewSummary:"human reviewed stabilization",completedBy:"operator",completedAt:NOW,stabilizationAfterSnapshot:{runtimeState:"reviewed locally"}}}
function review(patch={}){let r=core.createStabilizationReviewRecord(src,input(src,patch),human,options,[]);assert(r.created,r.reasons.join());r=core.beginStabilizationReview(r.record,human,options);assert(r.transitioned);r=core.submitStabilizationReview(r.record,human,options);assert(r.transitioned);return r.record}
function rejectSource(patch,rehash=true){const changed={...src,...patch},s=rehash?stamp(changed,"phase31PostStartVerificationAcceptance","phase316SourceSnapshot"):changed,before=JSON.stringify(s);assert.strictEqual(core.validatePhase317Eligibility(s,options).valid,false,JSON.stringify(patch));assert.strictEqual(core.createStabilizationReviewRecord(s,input(),human,options,[]).created,false);assert.strictEqual(core.extractStabilizationReviewCandidates([s],[],options).length,0);assert.strictEqual(JSON.stringify(s),before)}
assert.strictEqual(real.PHASE317_REFERENCE,p317);assert.strictEqual(core.PHASE317_REFERENCE,acceptance);
assert.strictEqual(core.STORAGE_KEY,"hashimoto.phase31.8.postStartStabilizationReviewRecords");assert.strictEqual(core.SCHEMA_VERSION,"31.8.1");assert.strictEqual(core.CURRENT_STAGE,"phase31_post_start_stabilization_review");assert.strictEqual(core.NEXT_STAGE,"manual_phase31_post_start_stabilization_decision");
const model=require("../phase30-8-phase30-post-start-stabilization-review-core.js");for(const k of ["STATES","RESULTS","RESULT_STATUS","REVIEW_FIELDS","ARRAY_FIELDS","REQUIRED_TRUE"])assert.strictEqual(JSON.stringify(core[k]),JSON.stringify(model[k]).replaceAll("phase30","phase31"),k);
assert(core.validatePhase317Eligibility(src,options).valid);assert(Object.isFrozen(core.validateReviewInput(input())));assert(Object.isFrozen(core.validateReviewInput({})));
for(const patch of [{phase31PostStartVerificationAcceptanceStatus:acceptance.STATES[4]},{phase31PostStartVerificationAcceptanceResult:acceptance.RESULTS[1]},{canProceedToNextStage:false},{phase:"phase30"},{stage:"wrong"},{nextStage:"wrong"},{phase31Started:false},{manualPhase31StartCompleted:false},{invalidatedAt:NOW},{expiredAt:NOW},{expiresAt:"2000-01-01"},{expiresAt:"bad"},{schemaVersion:"wrong"},{phase31PostStartVerificationAcceptanceVersion:"wrong"},{phase316SourceSnapshot:null},{auditTrail:[]},{recordVersion:0},{safetyBoundary:{}},{rollbackPoint:"other"},{recoveryPoint:"other"}])rejectSource(patch);
for(const v of [false,0,null,""])rejectSource({expiredAt:v});
for(const [k,v] of Object.entries(acceptance.SAFETY))rejectSource({[k]:!v});
for(const k of core.REFERENCE_IDS.concat(core.UPSTREAM_FIELDS)){rejectSource({[k]:""},k!=="phase31PostStartVerificationAcceptanceSnapshotHash");rejectSource({[k]:"other"},k!=="phase31PostStartVerificationAcceptanceSnapshotHash")}
for(const k of core.ISSUE_FIELDS)for(const v of [["issue"],null,"bad",[1]])rejectSource({[k]:v});
rejectSource({phase316SourceSnapshot:{...src.phase316SourceSnapshot,phase315SourceSnapshot:{chainValid:false}}});
for(const patch of [{phase31PostStartVerificationAcceptanceSnapshot:{}},{phase31PostStartVerificationAcceptanceSnapshotHash:"bad"},{acceptanceTarget:"tampered"}])rejectSource(patch,false);
for(const patch of [{action:"automatic_review"},{action:"toString"},{from:"wrong"},{to:"wrong"},{explicitConfirmation:false}])rejectSource({auditTrail:src.auditTrail.map((e,i)=>i===0?{...e,...patch}:e)});
for(const s of [null,undefined,[],"bad",{}])assert.strictEqual(core.validatePhase317Eligibility(s).valid,false);
for(const patch of [{CURRENT_STAGE:"wrong"},{NEXT_STAGE:"wrong"}])assert.strictEqual(load({...acceptance,...patch}).validatePhase317Eligibility(src,options).valid,false);
const expiring=stamp({...src,expiresAt:"2027-02-09T00:00:00Z"},"phase31PostStartVerificationAcceptance","phase316SourceSnapshot");assert.strictEqual(core.validatePhase317Eligibility(expiring).valid,false);assert(core.validatePhase317Eligibility(expiring,options).valid);assert.strictEqual(core.validatePhase317Eligibility(expiring,{now:()=>"2027-02-10T00:00:00Z"}).valid,false);
for(const k of core.CONTENT_FIELDS){const bad=input();delete bad[k];assert.strictEqual(core.createStabilizationReviewRecord(src,bad,human,options,[]).created,false,k)}
for(const k of core.REQUIRED_TRUE)for(const v of [false,"true",undefined])assert.strictEqual(core.createStabilizationReviewRecord(src,input(src,{[k]:v}),human,options,[]).created,false,k);
for(const k of core.ARRAY_FIELDS)for(const v of [null,"bad",[1]])assert.strictEqual(core.createStabilizationReviewRecord(src,input(src,{[k]:v}),human,options,[]).created,false,k);
for(const k of ["sourceRecordId","raceId","rollbackPoint","recoveryPoint"])assert.strictEqual(core.createStabilizationReviewRecord(src,input(src,{[k]:"other"}),human,options,[]).created,false);
for(const h of [null,{}, {...human,performedAt:"bad"},{...human,explicitConfirmation:false},{...human,reason:""}])assert.strictEqual(core.createStabilizationReviewRecord(src,input(),h,options,[]).created,false);
const cycle={};cycle.self=cycle;for(const patch of [{reviewNotes:cycle},{reviewSummary:"injected"},{automaticReviewPerformed:true},{result:core.RESULTS[0]},{canProceedToNextStage:true}])assert.strictEqual(core.createStabilizationReviewRecord(src,input(src,patch),human,options,[]).created,false);
let getterCalls=0;
const accessorInput=input();Object.defineProperty(accessorInput,"reviewTarget",{enumerable:true,get(){getterCalls++;return "unsafe"}});
assert.strictEqual(core.createStabilizationReviewRecord(src,accessorInput,human,options,[]).created,false);
const hiddenInput=input();Object.defineProperty(hiddenInput,"reviewTarget",{enumerable:false,value:"hidden"});assert.strictEqual(core.createStabilizationReviewRecord(src,hiddenInput,human,options,[]).created,false);
const customJson=input();Object.defineProperty(customJson,"toJSON",{value(){getterCalls++;return input()}});assert.strictEqual(core.createStabilizationReviewRecord(src,customJson,human,options,[]).created,false);
const accessorHuman={...human};Object.defineProperty(accessorHuman,"performedBy",{enumerable:true,get(){getterCalls++;return "unsafe"}});assert.strictEqual(core.createStabilizationReviewRecord(src,input(),accessorHuman,options,[]).created,false);
const accessorSource={...src};Object.defineProperty(accessorSource,"phase",{enumerable:true,get(){getterCalls++;return "phase31"}});assert.strictEqual(core.validatePhase317Eligibility(accessorSource,options).valid,false);
const accessorRecords=[];Object.defineProperty(accessorRecords,"0",{enumerable:true,get(){getterCalls++;return src}});assert.strictEqual(core.extractStabilizationReviewCandidates(accessorRecords,[],options).length,0);assert.strictEqual(core.createStabilizationReviewRecord(src,input(),human,options,accessorRecords).created,false);assert.strictEqual(core.saveStabilizationReviewRecords({setItem:forbidden},accessorRecords).saved,false);
const accessorView={};Object.defineProperty(accessorView,"reviewTarget",{enumerable:true,get(){getterCalls++;return "unsafe"}});assert.strictEqual(core.render(accessorView).reviewTarget,"");
const accessorPoint=input();Object.defineProperty(accessorPoint,"rollbackPoint",{enumerable:true,get(){getterCalls++;return src.rollbackPoint}});assert.strictEqual(core.createStabilizationReviewRecord(src,accessorPoint,human,options,[]).created,false);
const accessorIdSource={...src};Object.defineProperty(accessorIdSource,"sourceRecordId",{enumerable:true,get(){getterCalls++;return src.sourceRecordId}});assert.strictEqual(core.createStabilizationReviewRecord(accessorIdSource,input(src,{sourceRecordId:src.sourceRecordId}),human,options,[]).created,false);
const accessorSafety={...src};Object.defineProperty(accessorSafety,"safetyBoundary",{enumerable:true,get(){getterCalls++;return src.safetyBoundary}});assert.strictEqual(core.safetyIntact(accessorSafety),false);assert.throws(()=>core.computeSnapshotHash(accessorView),/JSON-safe/);
assert.strictEqual(getterCalls,0);
const data=input(),beforeData=JSON.stringify(data),created=core.createStabilizationReviewRecord(src,data,human,options,[]);assert(created.created,created.reasons.join());const initial=created.record;assert(core.integrityIntact(initial));assert(Object.isFrozen(initial));assert(Object.isFrozen(initial.phase317SourceSnapshot));
assert.strictEqual(JSON.stringify(core.createStabilizationReviewRecord(src,data,human,options,[])),JSON.stringify(created));assert.strictEqual(JSON.stringify(core.createStabilizationReviewRecord(src,data,human,undefined,[])),JSON.stringify(created));
assert.strictEqual(core.createStabilizationReviewRecord(src,Object.fromEntries(Object.entries(data).reverse()),human,options,[]).record.phase31PostStartStabilizationReviewSnapshotHash,initial.phase31PostStartStabilizationReviewSnapshotHash);
assert.strictEqual(core.createStabilizationReviewRecord(src,data,human,options,[initial]).created,false);assert.strictEqual(core.createStabilizationReviewRecord(src,data,human,options).created,false);assert.strictEqual(core.extractStabilizationReviewCandidates([src,src],[],options).length,1);assert.strictEqual(core.extractStabilizationReviewCandidates([src],[initial],options).length,0);
const accessorRecord={...initial};Object.defineProperty(accessorRecord,"phase31PostStartStabilizationReviewStatus",{enumerable:true,get(){getterCalls++;return core.STATES[1]}});
for(const op of [()=>core.beginStabilizationReview(accessorRecord,human,options),()=>core.submitStabilizationReview(accessorRecord,human,options),()=>core.updateStabilizationReview(accessorRecord,{reviewNotes:"x"},human,options),()=>core.completeStabilizationReview(accessorRecord,completion(),human,options),()=>core.invalidateStabilizationReview(accessorRecord,human,options)])assert(Object.values(op()).includes(false));assert.strictEqual(getterCalls,0);
assert.strictEqual(core.submitStabilizationReview(initial,human,options).transitioned,false);assert.strictEqual(core.completeStabilizationReview(initial,completion(),human,options).completed,false);
const begun=core.beginStabilizationReview(initial,human,options);assert(begun.transitioned);assert.strictEqual(core.beginStabilizationReview(begun.record,human,options).transitioned,false);
const updated=core.updateStabilizationReview(begun.record,{reviewNotes:"human observations"},human,options);assert(updated.updated);assert(core.integrityIntact(updated.record));
for(const k of core.PROTECTED_FIELDS)assert.strictEqual(core.updateStabilizationReview(begun.record,{[k]:"injected"},human,options).updated,false,k);
assert.strictEqual(core.updateStabilizationReview(begun.record,{reviewNotes:cycle},human,options).updated,false);
const pending=core.submitStabilizationReview(updated.record,human,options);assert(pending.transitioned);assert.strictEqual(pending.record.canProceedToNextStage,false);assert.strictEqual(pending.record.reviewDecision,"");
for(const k of Object.keys(completion())){const c=completion();delete c[k];assert.strictEqual(core.completeStabilizationReview(pending.record,c,human,options).completed,false,k)}
for(const patch of [{result:"automatic"},{canProceedToNextStage:false},{completedAt:"bad"},{stabilizationAfterSnapshot:{}},{stabilizationAfterSnapshot:cycle},{conditions:"forbidden"},{automaticReviewPerformed:true}])assert.strictEqual(core.completeStabilizationReview(pending.record,{...completion(),...patch},human,options).completed,false);
const done=core.completeStabilizationReview(pending.record,completion(),human,options);assert(done.completed,done.reasons.join());assert(core.integrityIntact(done.record));assert.strictEqual(done.record.phase31PostStartStabilizationReviewStatus,"ready_for_manual_phase31_post_start_stabilization_decision");assert.strictEqual(done.record.phase31PostStartStabilizationReviewResult,"phase31_post_start_stabilization_stable");assert.strictEqual(done.record.canProceedToNextStage,true);
for(const patch of [{errors:["error"]},{unresolvedIssues:["open"]},{criticalIssues:["critical"]},{blockingConditions:["blocked"]},{workingTreeEvidence:{...evidence("workingTreeEvidence"),status:"dirty",clean:false}},{mainOriginMainAlignmentEvidence:{...evidence("mainOriginMainAlignmentEvidence"),originMainCommit:"other",aligned:false}},{requiredTestResults:{...evidence("requiredTestResults"),passed:false}}]){const r=review(patch);assert.strictEqual(core.completeStabilizationReview(r,completion(),human,options).completed,false);const blocked=core.completeStabilizationReview(r,{...completion(core.RESULTS[4]),blockedReason:"human held review"},human,options);assert(blocked.completed);assert.strictEqual(blocked.record.canProceedToNextStage,false);assert(core.integrityIntact(blocked.record))}
assert(core.completeStabilizationReview(review({warnings:["nonblocking warning"]}),completion(),human,options).completed);
const nonNormal=[];
for(const result of core.RESULTS.slice(1)){
 const c=completion(result);if(result===core.RESULTS[1]){for(const k of core.CONDITION_FIELDS)c[k]=k;c.conditionDeadline="2027-03-01T00:00:00Z";for(const k of core.CONDITION_FIELDS){const bad={...c};delete bad[k];assert.strictEqual(core.completeStabilizationReview(pending.record,bad,human,options).completed,false)}}
 if(result===core.RESULTS[2]){c.unstableReason="unstable";c.requiredActions=["manual review"];for(const k of ["unstableReason","requiredActions"]){const bad={...c};delete bad[k];assert.strictEqual(core.completeStabilizationReview(pending.record,bad,human,options).completed,false)}}
 if(result===core.RESULTS[3])c.incompleteReason="missing evidence";if(result===core.RESULTS[4])c.blockedReason="manual block";
 assert.strictEqual(core.completeStabilizationReview(pending.record,{...c,canProceedToNextStage:true},human,options).completed,false);
 const r=core.completeStabilizationReview(pending.record,c,human,options);assert(r.completed,r.reasons.join());assert(core.integrityIntact(r.record));assert.strictEqual(r.record.canProceedToNextStage,false);nonNormal.push(r.record);
}
for(const result of core.RESULTS.slice(3))assert.strictEqual(core.completeStabilizationReview(pending.record,completion(result),human,options).completed,false);
const invalid=core.invalidateStabilizationReview(done.record,human,options);assert(invalid.transitioned);assert(core.integrityIntact(invalid.record));
for(const r of [invalid.record,stamp({...initial,expiresAt:"2000-01-01"}),stamp({...initial,expiredAt:NOW})]){assert.strictEqual(core.beginStabilizationReview(r,human,options).transitioned,false);assert.strictEqual(core.invalidateStabilizationReview(r,human,options).transitioned,false);assert.strictEqual(core.createStabilizationReviewRecord(src,data,human,options,[r]).created,false)}
for(const patch of [{phase31PostStartStabilizationReviewSnapshot:{}},{phase31PostStartStabilizationReviewSnapshotHash:"bad"},{reviewNotes:"tampered"},{phase317SourceSnapshot:null}])assert.strictEqual(core.integrityIntact({...done.record,...patch}),false);
for(const patch of [{phase31PostStartStabilizationReviewId:"other"},{schemaVersion:"wrong"},{phase31PostStartStabilizationReviewVersion:"wrong"},{sourceRecordId:"other"},{raceId:"other"},{phase31PostStartVerificationAcceptanceId:"other"},{recordVersion:0},{auditTrail:[]},{safetyBoundary:{}},{automaticReviewPerformed:true},{reviewDecision:core.RESULTS[1]},{canProceedToNextStage:false},{errors:["error"]}])assert.strictEqual(core.integrityIntact(stamp({...done.record,...patch})),false);
for(const patch of [{action:"automatic_review"},{action:"toString"},{from:"wrong"},{to:"wrong"},{explicitConfirmation:false}])assert.strictEqual(core.integrityIntact(stamp({...done.record,auditTrail:done.record.auditTrail.map((e,i)=>i===0?{...e,...patch}:e)})),false);
for(const k of ["expiredAt","expiresAt"])for(const v of [false,0,null,"bad",""]){const bad=stamp({...initial,[k]:v});assert.strictEqual(core.integrityIntact(bad),false);assert.strictEqual(core.beginStabilizationReview(bad,human,options).transitioned,false)}
for(const r of [null,undefined,{},[],"bad",cycle]){assert.strictEqual(core.integrityIntact(r),false);assert(Object.isFrozen(core.beginStabilizationReview(r,human,options)));assert.strictEqual(core.beginStabilizationReview(r,human,options).transitioned,false)}
for(const operation of [()=>core.beginStabilizationReview(initial,null,options),()=>core.updateStabilizationReview(begun.record,{reviewNotes:"x"},null,options),()=>core.submitStabilizationReview(begun.record,null,options),()=>core.completeStabilizationReview(pending.record,completion(),null,options),()=>core.invalidateStabilizationReview(done.record,null,options)]){const r=operation();assert(Object.values(r).includes(false));assert(Object.isFrozen(r))}
const mem={v:null,writes:0,setItem(k,v){assert.strictEqual(k,core.STORAGE_KEY);this.writes++;this.v=v},getItem(k){assert.strictEqual(k,core.STORAGE_KEY);return this.v}};
for(const r of [initial,done.record,...nonNormal,invalid.record]){assert(core.saveStabilizationReviewRecords(mem,[r]).saved);const loaded=core.loadStabilizationReviewRecords(mem);assert(loaded.loaded);assert.strictEqual(JSON.stringify(loaded.records[0]),JSON.stringify(r));assert(Object.isFrozen(loaded.records[0]))}
for(const records of [null,{},[{}],[done.record,done.record],[{...done.record,raceId:"other"}]]){const writes=mem.writes;assert.strictEqual(core.saveStabilizationReviewRecords(mem,records).saved,false);assert.strictEqual(mem.writes,writes)}
for(const v of ["{",JSON.stringify({schemaVersion:"wrong",records:[]}),JSON.stringify({schemaVersion:core.SCHEMA_VERSION,records:[{}]}),JSON.stringify({schemaVersion:core.SCHEMA_VERSION,records:[done.record,done.record]})]){mem.v=v;assert.strictEqual(core.loadStabilizationReviewRecords(mem).loaded,false)}
assert.strictEqual(core.saveStabilizationReviewRecords({setItem(){throw Error("storage unavailable")}},[]).saved,false);assert.strictEqual(core.loadStabilizationReviewRecords({getItem(){throw Error("storage unavailable")}}).loaded,false);
const malformedViewInput={reviewTarget:{nested:true},reviewScope:[]};const malformedBefore=JSON.stringify(malformedViewInput);assert.strictEqual(core.render(malformedViewInput).reviewTarget,"");assert.strictEqual(JSON.stringify(malformedViewInput),malformedBefore);assert.strictEqual(Object.isFrozen(malformedViewInput.reviewTarget),false);
const view=core.render(done.record);for(const k of ["manualStartRecorded","privateLocalOnly","planOnly","protectedMode","automaticReviewDisabled","automaticAdvanceDisabled","externalCommunicationDisabled","automationDisabled","safetyIntact","integrityIntact"])assert.strictEqual(view[k],true,k);assert.strictEqual(view.phase317Dependency,src.phase31PostStartVerificationAcceptanceId);assert(Object.isFrozen(view));
for(const [k,v] of Object.entries(core.SAFETY))assert.strictEqual(done.record[k],v,k);
const browser={HashimotoPhase317PostStartVerificationAcceptance:acceptance};vm.runInNewContext(code,browser);assert(browser.HashimotoPhase318PostStartStabilizationReview);assert.throws(()=>load(null),/Phase31-7 post-start verification acceptance definition is required/);assert.throws(()=>vm.runInNewContext(code,{}),/Phase31-7/);
assert(!/fetch\s*\(|XMLHttpRequest|WebSocket|EventSource|sendBeacon\s*\(|child_process|execSync|spawnSync|setInterval\s*\(|setTimeout\s*\(|writeFile|mkdir|localStorage|Date\.now\s*\(|Math\.random\s*\(|eval\s*\(|new\s+Function\s*\(/.test(code));
for(const k of ["automaticallyReview","automaticallyDecide","automaticallyCorrect","automaticallyRollback","automaticallyRecover","startPhase31","startNextPhase","releaseConditions"])assert.strictEqual(core[k],undefined);
assert.strictEqual(forbiddenCalls,0);assert.strictEqual(JSON.stringify(src),sourceBefore);assert.strictEqual(JSON.stringify(data),beforeData);assert.strictEqual(Object.isFrozen(src),false);assert.strictEqual(Object.isFrozen(data),false);
console.log("Phase31-8 unit, strict Phase31-7 contract, audit, storage, deterministic and browser cases: PASS");
if(!process.argv.includes("--unit-only")){
 const previousPath=require.resolve("./phase31PostStartVerificationAcceptanceCore.test.js"),previous=fs.readFileSync(previousPath,"utf8"),integration={require:createRequire(previousPath),__dirname:path.dirname(previousPath),console,process};
 vm.runInNewContext(previous.replace('console.log("phase31PostStartVerificationAcceptanceCore.test.js: PASS','globalThis.realAcceptance=r.record;console.log("phase31PostStartVerificationAcceptanceCore.test.js: PASS'),integration);
 const actual=integration.realAcceptance,before=JSON.stringify(actual);assert(real.validatePhase317Eligibility(actual,options).valid);
 let r=real.createStabilizationReviewRecord(actual,input(actual),human,options,[]);assert(r.created,r.reasons.join());r=real.beginStabilizationReview(r.record,human,options);assert(r.transitioned);r=real.submitStabilizationReview(r.record,human,options);assert(r.transitioned);r=real.completeStabilizationReview(r.record,completion(),human,options);assert(r.completed,r.reasons.join());assert(real.integrityIntact(r.record,options));assert.strictEqual(JSON.stringify(actual),before);
 console.log("phase31PostStartStabilizationReviewCore.test.js: PASS (unchanged Phase31-1 through Phase31-7 regressions and real recursive Phase30 source chain)");
}
