const assert = require("assert"), fs = require("fs"), path = require("path");
const core = require("../phase23-7-post-import-verification-audit-core.js");
const root = path.join(__dirname, ".."), read = (file) => fs.readFileSync(path.join(root, file), "utf8");
function memory(initial = {}, fail = false) { const data = { ...initial }; return { data, getItem(key) { return Object.prototype.hasOwnProperty.call(data, key) ? data[key] : null; }, setItem(key, value) { if (fail) throw new Error("quota"); data[key] = String(value); }, removeItem() { throw new Error("physical deletion forbidden"); } }; }
const payloads = { meeting: { meetingId: "m1", raceDate: "2026-07-19", venueCode: "TOK" }, race: { raceId: "r1", meetingId: "m1", raceNumber: 1, distance: 1600 }, runner: { runnerId: "runner1", raceId: "r1", horseNumber: 1, horseName: "A" }, oddsSnapshot: { raceId: "r1", betType: "win", combination: "1", capturedAt: "2026-07-19T11:00:00+09:00", odds: 2 }, result: { raceId: "r1", runnerId: "runner1", horseNumber: 1, finishPosition: 1, confirmedAt: "2026-07-19T12:10:00+09:00" }, payout: { raceId: "r1", betType: "win", combination: "1", payoutAmount: 200, confirmedAt: "2026-07-19T12:15:00+09:00" }, acquisitionRecord: { acquisitionId: "a1", sourceValidationId: "v1", fileHash: "h1", stagingId: "s1", dataType: "meeting", acquiredAt: "2026-07-19T10:00:00+09:00" } };
function execution(status = "verified", overrides = {}) { return { executionRecordId: "exec1", executionVersion: 1, executionPlanId: "plan1", snapshotId: "snap1", rollbackSnapshotId: null, preparationGroupId: "group1", importPreparationIds: ["p1"], gateRecordIds: ["g1"], stagingIds: ["s1"], stagingVersions: [1], sourceValidationIds: ["v1"], fileHashes: ["h1"], dataTypes: [...core.TYPES], providerIds: ["manual"], operator: "Executor", executionReason: "manual", executionApprovedAt: "2026-07-19T10:00:00+09:00", executionStartedAt: "2026-07-19T10:01:00+09:00", executionCompletedAt: "2026-07-19T10:02:00+09:00", verificationCompletedAt: "2026-07-19T10:03:00+09:00", expectedCounts: { insert: 7, update: 0, skip: 0, unchanged: 0, conflict: 0 }, actualCounts: { insert: 7, update: 0, skip: 0, unchanged: 0, conflict: 0 }, operationResults: core.TYPES.map((type, index) => ({ operationId: `op${index + 1}`, result: "inserted", recordId: `rec-${type}` })), verificationSummary: { countsMatched: true }, rollbackStatus: "eligible", formalImportExecuted: true, formalImportExecutedAt: "2026-07-19T10:02:00+09:00", status, ...overrides }; }
function formal(overrides = {}) { const records = core.TYPES.map((type) => ({ recordId: `rec-${type}`, dataType: type, naturalKey: core.naturalKey(type, payloads[type]), payload: payloads[type], sourceValidationId: "v1", fileHash: "h1", stagingId: "s1", stagingVersion: 1, gateRecordId: "g1", importPreparationId: "p1", executionRecordId: "exec1", importedAt: "2026-07-19T10:01:30+09:00", importedBy: "Executor", recordVersion: 1, active: true, createdAt: "2026-07-19T10:01:30+09:00", updatedAt: "2026-07-19T10:01:30+09:00", provenance: [{ eventId: `ev-${type}`, action: "insert", operator: "Executor", timestamp: "2026-07-19T10:01:30+09:00", executionRecordId: "exec1", afterVersion: 1 }], protectedMode: true, privateLocalOnly: true })); const store = { schemaVersion: 1, records, modelStores: Object.fromEntries(core.TYPES.map((type) => [type, records.filter((record) => record.dataType === type)])) }; store.checksum = core.checksum(records); return { ...store, ...overrides }; }
function snapshot(overrides = {}) { const value = { snapshotId: "snap1", executionRecordId: "exec1", preparationGroupId: "group1", createdAt: "2026-07-19T10:00:30+09:00", createdBy: "Executor", affectedDataTypes: [...core.TYPES], affectedNaturalKeys: core.TYPES.map((type) => `${type}:${core.naturalKey(type, payloads[type])}`), beforeRecords: [], beforeRecordCount: 0, formalDataSchemaVersion: 1, rollbackEligible: true, verificationStatus: "created", history: [], ...overrides }; value.checksum = core.checksum({ ...value, checksum: undefined }); return value; }
const fullReview = (decision = "audit_verified_clean", overrides = {}) => ({ decision, warningConfirmed: decision === "audit_verified_with_warnings", warningReason: decision === "audit_verified_with_warnings" ? "human checked" : "", auditReviewer: "Auditor", auditReason: "all checks reviewed", auditReviewedAt: "2026-07-19T11:00:00+09:00", formalChecksumConfirmed: true, planChecksumConfirmed: true, snapshotChecksumConfirmed: true, operationCountsConfirmed: true, referencesConfirmed: true, countsConfirmed: true, provenanceConfirmed: true, pendingConfirmed: true, phase236UnchangedConfirmed: true, phase2315UnchangedConfirmed: true, phase22UnchangedConfirmed: true, noExternalCommunicationConfirmed: true, noAutomaticRepairConfirmed: true, noAutomaticRollbackConfirmed: true, protectedMode: true, privateLocalOnly: true, ...overrides });

for (const status of ["verified", "verification_failed", "rollback_candidate", "rolled_back"]) assert.strictEqual(core.eligibleExecutions({ records: [execution(status)] }).length, 1); for (const status of ["execution_in_progress", "execution_completed", "rejected", "cancelled", "expired"]) assert.strictEqual(core.eligibleExecutions({ records: [execution(status)] }).length, 0);
const f = formal(), e = execution(), ss = { records: [snapshot()] }; let checked = core.validateFormalStore(f, { records: [e] }); assert.ok(!checked.issues.some((item) => item.level === "fatal"), JSON.stringify(checked.issues)); assert.strictEqual(checked.summary.total, 7); for (const type of core.TYPES) assert.strictEqual(checked.summary.byType[type].total, 1);
assert.ok(core.validateFormalStore({ ...f, modelStores: null }, { records: [e] }).issues.some((item) => item.code === "MODEL_STORES_MISSING")); assert.ok(core.validateFormalStore({ schemaVersion: 1, modelStores: {}, records: {} }, { records: [e] }).issues.some((item) => item.code === "FORMAL_RECORDS_NOT_ARRAY"));
function formalIssue(change, code) { const copy = JSON.parse(JSON.stringify(f)); change(copy); return core.validateFormalStore(copy, { records: [e] }).issues.some((item) => item.code === code); }
assert.ok(formalIssue((x) => x.records.push({ ...x.records[0] }), "RECORD_ID_DUPLICATE")); assert.ok(formalIssue((x) => { x.records[1].naturalKey = x.records[0].naturalKey; x.records[1].dataType = "meeting"; }, "ACTIVE_NATURAL_KEY_DUPLICATE")); assert.ok(formalIssue((x) => { x.records[0].recordVersion = 0; }, "RECORD_VERSION_INVALID")); assert.ok(formalIssue((x) => { x.records[0].active = "yes"; }, "ACTIVE_INVALID")); assert.ok(formalIssue((x) => { x.records = x.records.filter((r) => r.dataType !== "meeting"); x.modelStores.meeting = []; }, "MEETING_REFERENCE_MISSING")); assert.ok(formalIssue((x) => { x.records = x.records.filter((r) => r.dataType !== "race"); x.modelStores.race = []; }, "RACE_REFERENCE_MISSING")); assert.ok(formalIssue((x) => { x.records.find((r) => r.dataType === "oddsSnapshot").payload.combination = "9"; }, "ODDS_COMBINATION_MISSING")); assert.ok(formalIssue((x) => { x.records.find((r) => r.dataType === "payout").payload.combination = "9"; }, "PAYOUT_COMBINATION_MISSING")); assert.ok(formalIssue((x) => { x.records[0].provenance = []; }, "PROVENANCE_REQUIRED")); assert.ok(formalIssue((x) => { x.records[0].executionRecordId = "missing"; }, "EXECUTION_REFERENCE_MISSING"));
let executionCheck = core.validateExecution(e, checked); assert.strictEqual(executionCheck.issues.length, 0); assert.strictEqual(executionCheck.countStatus, "exact_match"); assert.ok(core.validateExecution(execution("verified", { actualCounts: { insert: 6 } }), checked).issues.some((item) => item.code === "OPERATION_RESULT_COUNT_MISMATCH")); assert.ok(core.validateExecution(execution("verified", { operationResults: [] }), checked).issues.some((item) => item.code === "OPERATION_RESULT_COUNT_MISMATCH"));
let snapCheck = core.validateSnapshot(e, snapshot(), 1); assert.strictEqual(snapCheck.status, "verified"); assert.ok(core.validateSnapshot(e, null, 1).issues.some((item) => item.code === "SNAPSHOT_MISSING")); assert.ok(core.validateSnapshot(e, snapshot({ executionRecordId: "other" }), 1).issues.some((item) => item.code === "SNAPSHOT_EXECUTION_MISMATCH")); const badSnap = snapshot(); badSnap.checksum = "bad"; assert.ok(core.validateSnapshot(e, badSnap, 1).issues.some((item) => item.code === "SNAPSHOT_CHECKSUM_MISMATCH")); assert.ok(core.validateSnapshot(e, snapshot({ createdAt: "2026-07-19T10:01:30+09:00" }), 1).issues.some((item) => item.code === "SNAPSHOT_AFTER_EXECUTION_START"));
assert.strictEqual(core.checksum({ a: 1, b: 2 }), core.checksum({ b: 2, a: 1 })); assert.notStrictEqual(core.checksum({ a: 1 }), core.checksum({ a: 2 }));
assert.ok(core.chronology(execution("verified", { executionStartedAt: "2026-07-19T09:00:00+09:00" }), f.records, new Date().toISOString()).issues.some((item) => item.code === "EXECUTION_BEFORE_APPROVAL")); assert.ok(core.chronology(execution("verified", { executionCompletedAt: "2026-07-19T09:00:00+09:00" }), f.records, new Date().toISOString()).issues.some((item) => item.code === "EXECUTION_COMPLETED_BEFORE_START")); assert.ok(core.chronology(execution("verified", { executionApprovedAt: "2026-07-19T10:00:00" }), f.records, new Date().toISOString()).issues.some((item) => item.code === "TIMEZONE_MISSING"));
assert.strictEqual(core.pendingAudit(null, f, e).status, "clear"); assert.strictEqual(core.pendingAudit({ status: "committed", executionRecordId: "exec1" }, f, e).status, "finalized"); assert.strictEqual(core.pendingAudit({ status: "invalidated", executionRecordId: "exec1" }, f, e).status, "invalidated"); assert.strictEqual(core.pendingAudit({ status: "validated_pending_commit", executionRecordId: "exec1" }, f, e).status, "stale"); assert.strictEqual(core.pendingAudit({ status: "committed", executionRecordId: "other" }, f, e).status, "conflicting");
assert.strictEqual(core.resultFromIssues([core.issue("X", "fatal", "x", "", "x")], e), "verification_fatal"); assert.strictEqual(core.resultFromIssues([core.issue("X", "error", "x", "", "x")], e), "verification_error"); assert.strictEqual(core.resultFromIssues([core.issue("X", "warning", "x", "", "x")], e), "verified_with_warnings"); assert.strictEqual(core.resultFromIssues([], e), "verified_clean");
const sourcesBefore = JSON.stringify({ e, f, ss }); let built = core.buildAudit(e, f, ss, { status: "committed", executionRecordId: "exec1" }, new Date("2026-07-19T02:00:00Z")); assert.ok(built.created); assert.strictEqual(JSON.stringify({ e, f, ss }), sourcesBefore); for (const key of ["executionRecordId", "executionVersion", "executionPlanId", "snapshotId", "preparationGroupId", "importPreparationIds", "gateRecordIds", "stagingIds", "dataTypes", "expectedCounts", "actualCounts"]) assert.ok(Object.prototype.hasOwnProperty.call(built.record, key), key); assert.strictEqual(core.buildAudit(execution("execution_in_progress"), f, ss, null).reason, "execution_not_eligible");
let cleanRecord = { ...built.record, issueCounts: { fatal: 0, error: 0, warning: 0, info: 0 }, verificationStatus: "verification_completed", auditStatus: "verified_clean" }; assert.ok(core.reviewProblems(cleanRecord, fullReview()).length === 0); assert.ok(core.reviewProblems({ ...cleanRecord, issueCounts: { fatal: 1, error: 0, warning: 0 } }, fullReview()).includes("clean_conditions_failed")); assert.ok(core.reviewProblems(cleanRecord, fullReview("audit_verified_clean", { auditReviewer: "" })).includes("audit_reviewer_required")); assert.ok(core.reviewProblems(cleanRecord, fullReview("audit_verified_clean", { auditReviewedAt: "2099-01-01T00:00:00+09:00" })).includes("audit_datetime_future"));
let reviewed = core.applyHumanReview(cleanRecord, fullReview(), [], new Date("2026-07-19T03:00:00Z")); assert.ok(reviewed.reviewed); assert.strictEqual(reviewed.record.auditStatus, "audit_verified_clean"); let closed = core.closeAudit(reviewed.record, {}, new Date("2026-07-19T04:00:00Z")); assert.ok(closed.closed); assert.strictEqual(core.closeAudit({ ...reviewed.record, auditStatus: "audit_error_detected" }).reason, "review_decision_not_closable"); const warningRecord = { ...cleanRecord, issueCounts: { fatal: 0, error: 0, warning: 1, info: 0 } }; assert.ok(core.reviewProblems(warningRecord, fullReview("audit_verified_with_warnings", { warningConfirmed: false })).includes("warning_confirmation_required"));
let follow = core.createFollowUp(cleanRecord, { followUpType: "manual_investigation", title: "Investigate", reason: "reference anomaly" }, new Date()); assert.ok(follow.created); assert.strictEqual(follow.record.followUps.length, 1); assert.strictEqual(core.createFollowUp(cleanRecord, { followUpType: "unknown" }).reason, "follow_up_fields_required"); assert.strictEqual(core.transition("closed", "verification_in_progress").reason, "terminal_locked");
const dangerous = core.stripDangerous({ APIKey: "x", password: "x", cookie: "x", accessToken: "x", rawRecords: [1], nested: { constructor: "x", safe: 1 } }); assert.strictEqual(dangerous.nested.safe, 1); for (const key of ["APIKey", "password", "cookie", "accessToken", "rawRecords"]) assert.ok(!Object.prototype.hasOwnProperty.call(dangerous, key)); assert.ok(!core.auditText(cleanRecord).includes(JSON.stringify(f.records)));
const sourceValues = { phase22: "22", p231: "231", p232: "232", p233: "233", p234: "234", p235: "235", p236: "236", formal: "formal", snapshots: "snapshots", pending: "pending" }, mem = memory(sourceValues); let saved = core.addAudit(core.defaultStore(), cleanRecord, mem, new Date()); assert.ok(saved.saved); for (const [key, value] of Object.entries(sourceValues)) assert.strictEqual(mem.data[key], value); assert.strictEqual(core.addAudit(saved.store, cleanRecord, mem).reason, "duplicate_audit_id"); const old = JSON.stringify(saved.store), failing = memory({ [core.STORAGE_KEY]: old }, true); assert.ok(!core.saveStore({ records: [closed.record] }, failing).saved); assert.strictEqual(failing.data[core.STORAGE_KEY], old);
const code = read("phase23-7-post-import-verification-audit-core.js") + read("phase23-7-main-dashboard-integration.js"); for (const pattern of [/\bfetch\s*\(/, /XMLHttpRequest/, /\bWebSocket\s*\(/, /\bEventSource\s*\(/, /sendBeacon/, /setInterval\s*\(/, /addEventListener\s*\(\s*["']storage/, /\.removeItem\s*\(/]) assert.ok(!pattern.test(code)); assert.ok(!/automaticRepairExecuted\s*:\s*true/.test(code)); assert.ok(!/automaticRollbackExecuted\s*:\s*true/.test(code));
const index = read("index.html"), local = read("private-local.html"); assert.ok(index.includes('id="phase23-post-import-verification-audit"')); assert.ok(local.includes('href="index.html#phase23-post-import-verification-audit"')); assert.ok(index.indexOf('id="phase23-manual-formal-import-execution"') < index.indexOf('id="phase23-post-import-verification-audit"')); assert.ok(index.indexOf("phase23-6-main-dashboard-integration.js") < index.indexOf("phase23-7-post-import-verification-audit-core.js")); assert.ok(index.indexOf("phase23-7-post-import-verification-audit-core.js") < index.indexOf("phase23-7-main-dashboard-integration.js")); assert.ok(!index.includes('id="p237-rollback-execute"'));
for (const file of ["index.html", "private-local.html", "phase22-22-private-local.html"]) { const html = read(file), ids = [...html.matchAll(/\bid="([^"]+)"/g)].map((match) => match[1]); assert.strictEqual(ids.length, new Set(ids).size); for (const match of html.matchAll(/<script[^>]+src="([^"]+)"/g)) if (!/^(?:https?:)?\/\//.test(match[1])) assert.ok(fs.existsSync(path.join(root, match[1])), match[1]); }
console.log("Phase23-7 post import verification audit core tests passed");
