"use strict";
const assert=require("assert"),fs=require("fs"),vm=require("vm"),core=require("../phase27-26-phase27-final-closure-core.js"),NOW="2027-01-01T00:00:00Z",opt={now:()=>new Date(NOW)},human={performedBy:"human",reason:"manual",explicitConfirmation:true,performedAt:NOW},snap={passed:true};
function source(p={}){const r={phase27PostStartStabilizationClosureAcceptanceStatus:"ready_for_manual_phase27_final_closure",phase27PostStartStabilizationClosureAcceptanceResult:"accept_phase27_post_start_stabilization_closure",expiresAt:"2027-12-01T00:00:00Z",phase27PostStartStabilizationClosureAcceptanceSnapshot:snap,phase27PostStartStabilizationClosureAcceptanceSnapshotHash:core.PHASE2725_REFERENCE.computeSnapshotHash(snap),phase27PostStartStabilizationClosureAcceptanceVersion:"27.25.1",recordVersion:2,verificationBeforeSnapshot:{before:true},verificationAfterSnapshot:{after:true},phase27PostStartStabilizationClosureExecutionApprovalSnapshot:{approval:true},phase27PostStartStabilizationClosureExecutionPreparationSnapshot:{preparation:true},phase27PostStartStabilizationClosureDecisionSnapshot:{closureDecision:true},phase27PostStartStabilizationClosureReviewSnapshot:{closureReview:true},phase27PostStartStabilizationFollowupSnapshot:{followup:true},phase27PostStartStabilizationDecisionSnapshot:{decision:true},phase27PostStartStabilizationReviewSnapshot:{review:true},auditTrail:[{action:"handoff"}],phase27Started:true,manualPhase27StartCompleted:true,postStartAcceptancePassed:true,stabilizationReviewPassed:true,stabilizationDecisionConfirmed:true,stabilizationFollowupPassed:true,closureReviewPassed:true,closureDecisionConfirmed:true,closureExecutionPreparationReady:true,closureExecutionApproved:true,closurePostExecutionVerificationPassed:true,closurePostExecutionVerificationDecisionConfirmed:true,stableStateConfirmed:true,workingTreeSafe:true,mainOriginMainMatch:true,requiredTestsPassed:true,stateMatch:true,requiredModulesConfirmed:true,requiredUiConfirmed:true,requiredConfigConfirmed:true,correctionRequired:false,rollbackRequired:false,recoveryRequired:false,...core.PHASE2725_REFERENCE.SAFETY};core.REFERENCE_IDS.forEach(k=>r[k]=`${k}-1`);core.ZERO_COUNTS.forEach(k=>r[k]=0);return{...r,...p}}
function input(p={}){return{closedBy:"decider",responsiblePerson:"owner",confirmedBy:"confirmer",closureReason:"decide",rollbackPoint:"before",recoveryPoint:"snapshot",gitEvidence:{safe:true},testEvidence:{passed:true},stateEvidence:{match:true},moduleEvidence:{ok:true},uiEvidence:{ok:true},configEvidence:{ok:true},safetyEvidence:{ok:true},rollbackEvidence:{ready:true},recoveryEvidence:{ready:true},expiresAt:"2027-11-01T00:00:00Z",...p}}
function create(){const x=core.createPhase27FinalClosureRecord(source(),input(),human,opt,[]);assert(x.created,x.reasons.join());return x.record}function progress(){let r=create();r=core.startPhase27FinalClosure(r,human,opt).record;return core.progressPhase27FinalClosure(r,human,opt).record}function confirm(p={}){const x={result:"confirm_phase27_final_closure",closureSummary:"confirmed",closureAfterSnapshot:{confirmed:true},closureTarget:"target",closureScope:"scope",decisionEvidence:{pass:true},verificationEvidence:{ok:true},executionEvidence:{ok:true},closureDecisionEvidence:{ok:true},closureReviewEvidence:{ok:true},followupEvidence:{ok:true},stabilizationDecisionEvidence:{ok:true},stabilizationReviewEvidence:{ok:true},acceptanceEvidence:{ok:true},postStartAcceptanceEvidence:{ok:true},phase27StartEvidence:{ok:true},executionPreparationEvidence:{ok:true},executionApprovalEvidence:{ok:true},phase27Started:true,manualPhase27StartCompleted:true,postStartAcceptancePassed:true,stabilizationReviewPassed:true,stabilizationDecisionConfirmed:true,stabilizationFollowupPassed:true,closureReviewPassed:true,closureDecisionConfirmed:true,closureExecutionPreparationReady:true,closureExecutionApproved:true,closurePostExecutionVerificationPassed:true,closurePostExecutionVerificationDecisionConfirmed:true,stableStateConfirmed:true,workingTreeSafe:true,mainOriginMainMatch:true,requiredTestsPassed:true,stateMatch:true,requiredModulesConfirmed:true,requiredUiConfirmed:true,requiredConfigConfirmed:true,correctionRequired:false,rollbackRequired:false,recoveryRequired:false};core.ZERO_COUNTS.forEach(k=>x[k]=0);return{...x,...p}}
assert(core.PHASE2725_REFERENCE,"dependency");assert.strictEqual(core.extractPhase27FinalClosureCandidates([source()],[],opt).length,1);
for(const p of [{phase27PostStartStabilizationClosureAcceptanceStatus:"bad"},{phase27PostStartStabilizationClosureAcceptanceResult:"conditionally_confirm_phase27_final_closure"},{phase27PostStartStabilizationClosureAcceptanceResult:"pass_phase27_post_start_stabilization_closure_post_execution_verification"},{invalidatedAt:NOW},{expiresAt:"2026-01-01T00:00:00Z"},{phase27PostStartStabilizationClosureAcceptanceId:""},{phase27PostStartStabilizationClosureAcceptanceSnapshot:null},{phase27PostStartStabilizationClosureAcceptanceSnapshotHash:"bad"},{phase27PostStartStabilizationClosureAcceptanceVersion:"bad"},{auditTrail:[]},{protectedMode:false},{criticalIssueCount:1},{phase27Started:false},{phase27AutomaticallyStarted:true}])assert.strictEqual(core.validatePhase27PostStartStabilizationClosureAcceptance(source(p),opt).valid,false,JSON.stringify(p));
const first=create();assert.strictEqual(core.extractPhase27FinalClosureCandidates([source()],[first],opt).length,0);assert.strictEqual(core.createPhase27FinalClosureRecord(source(),input(),{},opt,[]).created,false);const s=source(),text=JSON.stringify(s);create();assert.strictEqual(JSON.stringify(s),text);
let r=core.startPhase27FinalClosure(first,human,opt).record;r=core.progressPhase27FinalClosure(r,human,opt).record;assert(core.pausePhase27FinalClosure(r,human,opt).transitioned);assert(core.resumePhase27FinalClosure(core.pausePhase27FinalClosure(r,human,opt).record,human,opt).transitioned);assert(core.stopPhase27FinalClosure(r,human,opt).transitioned);assert(core.cancelPhase27FinalClosure(r,human,opt).transitioned);assert(core.failPhase27FinalClosure(r,human,opt).transitioned);assert(core.updatePhase27FinalClosure(r,{closureReason:"updated"},human,opt).updated);const ok=core.completePhase27FinalClosure(r,confirm(),human,opt);assert(ok.completed,ok.reasons.join());assert.strictEqual(ok.record.phase27FinalClosureStatus,"phase27_final_closure_confirmed");
const routes=[["conditionally_confirm_phase27_final_closure",{conditions:"c",conditionReason:"r",conditionOwner:"o",conditionDeadline:"2027-03-01",conditionVerificationMethod:"m",conditionReleaseCriteria:"c"}],...["reject_phase27_final_closure","final_closure_incomplete","return_for_phase27_post_start_stabilization_closure_acceptance","return_for_phase27_post_start_stabilization_closure_execution","return_for_phase27_post_start_stabilization_closure_execution_approval","return_for_phase27_post_start_stabilization_closure_execution_preparation","return_for_phase27_post_start_stabilization_closure_decision","return_for_phase27_post_start_stabilization_closure_review","return_for_phase27_post_start_stabilization_followup","return_for_phase27_post_start_stabilization_decision","return_for_phase27_post_start_stabilization_review","return_for_phase27_start_post_execution_acceptance","return_for_phase27_start_post_execution_verification_decision","return_for_phase27_start_post_execution_verification","return_for_phase27_start_execution","correction_plan_required","rollback_plan_required","recovery_plan_required","additional_evidence_required","additional_review_required","manual_investigation_required","hold","blocked"].map(x=>[x,{}])];for(const[result,p]of routes){const x=core.completePhase27FinalClosure(progress(),{result,...p},human,opt);assert(x.completed,result);assert.notStrictEqual(x.record.phase27FinalClosureStatus,"phase27_final_closure_confirmed")}
for(const k of [...core.ZERO_COUNTS,"rollbackPoint","recoveryPoint","gitEvidence","testEvidence","stateEvidence","safetyEvidence","closureDecisionEvidence","executionPreparationEvidence","phase27PostStartStabilizationClosureAcceptanceSnapshot","closureAfterSnapshot","closureTarget","closureScope","decisionEvidence","verificationEvidence","verificationEvidence","executionEvidence","stableStateConfirmed","workingTreeSafe","mainOriginMainMatch","requiredTestsPassed","requiredModulesConfirmed","requiredUiConfirmed","requiredConfigConfirmed"]){const v=core.ZERO_COUNTS.includes(k)?1:(k.startsWith("required")||["stableStateConfirmed","workingTreeSafe","mainOriginMainMatch"].includes(k)?false:null);assert.strictEqual(core.completePhase27FinalClosure(progress(),confirm({[k]:v}),human,opt).completed,false,k)}
Object.entries(core.SAFETY).forEach(([k,v])=>assert.strictEqual(first[k],v,k));assert(core.integrityIntact(first));assert(core.integrityIntact(ok.record));assert.strictEqual(core.integrityIntact({...ok.record,phase27FinalClosureSnapshot:{tampered:true}}),false);const code=fs.readFileSync(require.resolve("../phase27-26-phase27-final-closure-core.js"),"utf8");const browser={HashimotoPhase2725PostStartStabilizationClosureAcceptance:core.PHASE2725_REFERENCE};vm.runInNewContext(code,browser);assert(browser.HashimotoPhase2726FinalClosure,"browser global");assert(code.includes("phase27-25-phase27-post-start-stabilization-closure-acceptance-core.js"),"direct Phase27-25 dependency");assert(!/child_process|execSync|spawnSync|fetch\(|XMLHttpRequest|WebSocket|writeFile|mkdir|unlink|GitHub API|shell execution/.test(code));const mem={v:null,setItem(_k,v){this.v=v},getItem(){return this.v}};assert(core.savePhase27FinalClosureRecords(mem,[ok.record]).saved);assert(core.loadPhase27FinalClosureRecords(mem).loaded);mem.v="{";assert.strictEqual(core.loadPhase27FinalClosureRecords(mem).loaded,false);assert(core.invalidatePhase27FinalClosure(ok.record,human,opt).transitioned);assert.strictEqual(core.expirePhase27FinalClosure({...first,expiresAt:"2026-01-01T00:00:00Z"},{},opt).expired,false);assert(core.expirePhase27FinalClosure({...first,expiresAt:"2026-01-01T00:00:00Z"},human,opt).expired);try{first.planOnly=false}catch(_){}assert(first.planOnly);assert.strictEqual(ok.record.phase27FinalClosureStatus,"phase27_final_closure_confirmed");assert.strictEqual(ok.record.nextPhaseAutomaticallyStarted,false);assert.strictEqual(ok.record.automaticPhase27FinalCompletionAllowed,false);console.log("phase27FinalClosureCore.test.js: PASS");










