"use strict";
const assert=require("assert"),fs=require("fs"),vm=require("vm"),core=require("../phase28-4-source-candidate-registration-core.js"),p283=core.PHASE283_REFERENCE,p281=p283.PHASE282_REFERENCE.PHASE281_REFERENCE,NOW="2027-01-01T00:00:00Z",options={now:()=>new Date(NOW)},human={performedBy:"human",reason:"manual",explicitConfirmation:true,performedAt:NOW};
function source(p={}){const base={phase28ExternalDataCategoryDefinitionId:"definition-1",phase28ExternalDataCategoryDefinitionStatus:"ready_for_manual_phase28_source_candidate_registration",phase28ExternalDataCategoryDefinitionResult:"external_data_categories_defined",categories:p283.REQUIRED_CATEGORIES.map((categoryCode,i)=>({categoryId:`category-${i}`,categoryCode})),expiresAt:"2027-12-01T00:00:00Z",recordVersion:4,auditTrail:[{action:"handoff"}],correctionRequired:false,rollbackRequired:false,recoveryRequired:false,criticalIssues:[],blockingConditions:[],...p283.SAFETY};p283.REFERENCE_IDS.forEach(k=>base[k]=`${k}-1`);p283.ZERO_COUNTS.forEach(k=>base[k]=0);const snapshot={...base};return{...base,phase28ExternalDataCategoryDefinitionSnapshot:snapshot,phase28ExternalDataCategoryDefinitionSnapshotHash:p283.computeSnapshotHash(snapshot),phase28ExternalDataCategoryDefinitionVersion:p283.SCHEMA_VERSION,...p}}
function input(p={}){return{registeredBy:"registrar",responsiblePerson:"owner",confirmedBy:"confirmer",registrationReason:"candidate review",registrationScope:"Phase28",registrationTarget:"sources",rollbackPoint:"before",recoveryPoint:"snapshot",gitEvidence:{safe:true},testEvidence:{pass:true},stateEvidence:{stable:true},safetyEvidence:{intact:true},expiresAt:"2027-11-01T00:00:00Z",...p}}
function candidate(p={}){const c={};for(const key of core.SOURCE_CANDIDATE_FIELDS)c[key]=key==="targetCategories"?[...core.REQUIRED_CATEGORIES]:key.endsWith("Candidate")||key.endsWith("Required")||key.endsWith("Requirement")?true:`candidate_${key}`;return{...c,sourceCandidateId:"source-1",sourceCode:"source_one",sourceName:"Candidate Source",sourceType:"official_web",providerName:"Candidate Provider",...p}}
function create(){const x=core.createSourceCandidateRegistrationRecord(source(),input(),human,options,[]);assert(x.created,x.reasons.join());return x.record}function progress(){let r=create();r=core.startSourceCandidateRegistration(r,human,options).record;return core.progressSourceCandidateRegistration(r,human,options).record}function registered(p={}){return{result:"source_candidates_registered",sourceCandidates:[candidate()],registrationAfterSnapshot:{registered:true},correctionRequired:false,rollbackRequired:false,recoveryRequired:false,criticalIssues:[],blockingConditions:[],...p}}
assert(core.PHASE283_REFERENCE);assert.strictEqual(core.CURRENT_STAGE,"source_candidate_registration");assert.strictEqual(core.NEXT_STAGE,"source_trust_review");assert(p281.PHASE28_STAGES.includes(core.CURRENT_STAGE)&&p281.PHASE28_STAGES.includes(core.NEXT_STAGE));assert.strictEqual(core.extractSourceCandidateRegistrationCandidates([source()],[]).length,1);
for(const p of [{phase28ExternalDataCategoryDefinitionStatus:"bad"},{phase28ExternalDataCategoryDefinitionResult:"bad"},{invalidatedAt:NOW},{expiredAt:NOW},{phase28ExternalDataCategoryDefinitionSnapshot:null},{phase28ExternalDataCategoryDefinitionSnapshotHash:"bad"},{phase28ExternalDataCategoryDefinitionVersion:"bad"},{auditTrail:[]},{recordVersion:0},{protectedMode:false},{categories:[]},{criticalIssues:["x"]},{blockingConditions:["x"]},{correctionRequired:true},{rollbackRequired:true},{recoveryRequired:true}])assert.strictEqual(core.validatePhase283Eligibility(source(p)).valid,false,JSON.stringify(p));
assert.strictEqual(core.createSourceCandidateRegistrationRecord(source(),input(),{},options,[]).created,false);const src=source(),text=JSON.stringify(src);assert(core.createSourceCandidateRegistrationRecord(src,input(),human,options,[]).created);assert.strictEqual(JSON.stringify(src),text);const first=create();assert.strictEqual(core.extractSourceCandidateRegistrationCandidates([source()],[first]).length,0);assert.strictEqual(core.createSourceCandidateRegistrationRecord(source(),input(),human,options,[first]).created,false);
let r=core.startSourceCandidateRegistration(first,human,options).record;r=core.progressSourceCandidateRegistration(r,human,options).record;assert(core.pauseSourceCandidateRegistration(r,human,options).transitioned);assert(core.resumeSourceCandidateRegistration(core.pauseSourceCandidateRegistration(r,human,options).record,human,options).transitioned);assert(core.stopSourceCandidateRegistration(r,human,options).transitioned);assert(core.cancelSourceCandidateRegistration(r,human,options).transitioned);assert(core.failSourceCandidateRegistration(r,human,options).transitioned);assert.strictEqual(core.updateSourceCandidateRegistration(first,{},human,options).updated,false);assert(core.updateSourceCandidateRegistration(r,{registrationReason:"updated"},human,options).updated);
assert.strictEqual(core.completeSourceCandidateRegistration(r,registered({sourceCandidates:[]}),human,options).completed,false);assert.strictEqual(core.completeSourceCandidateRegistration(r,registered({sourceCandidates:[candidate({targetCategories:["unknown"]})]}),human,options).completed,false);assert.strictEqual(core.completeSourceCandidateRegistration(r,registered({sourceCandidates:[candidate(),candidate({sourceCode:"other"})]}),human,options).completed,false);assert.strictEqual(core.completeSourceCandidateRegistration(r,registered({sourceCandidates:[candidate(),candidate({sourceCandidateId:"other"})]}),human,options).completed,false);assert.strictEqual(core.completeSourceCandidateRegistration(r,registered({sourceCandidates:[candidate({sourceName:""})]}),human,options).completed,false);assert.strictEqual(core.completeSourceCandidateRegistration(r,registered({sourceCandidates:[candidate({targetCategories:["race_entry"]})]}),human,options).completed,false);
for(const p of [{criticalIssues:["x"]},{blockingConditions:["x"]},{correctionRequired:true},{rollbackRequired:true},{recoveryRequired:true}])assert.strictEqual(core.completeSourceCandidateRegistration(r,registered(p),human,options).completed,false);
const ok=core.completeSourceCandidateRegistration(r,registered(),human,options);assert(ok.completed,ok.reasons.join());assert.strictEqual(ok.record.phase28SourceCandidateRegistrationStatus,"source_candidates_registered");
const routes=[["source_candidates_conditionally_registered",{conditions:"c",conditionReason:"r",conditionOwner:"o",conditionDeadline:"2027-03-01",conditionVerificationMethod:"m",conditionReleaseCriteria:"c"}],...["source_candidate_registration_rejected","source_candidate_registration_incomplete","additional_source_candidate_review_required","category_mapping_review_required","source_scope_review_required","terms_review_required","security_review_required","correction_plan_required","rollback_plan_required","recovery_plan_required","manual_investigation_required","hold","blocked"].map(x=>[x,{}])];for(const[result,p]of routes)assert(core.completeSourceCandidateRegistration(progress(),{result,...p},human,options).completed,result);
assert.strictEqual(core.advanceToSourceTrustReview(ok.record,{},options).advanced,false);const hand=core.advanceToSourceTrustReview(ok.record,human,options);assert(hand.advanced);assert.strictEqual(hand.record.phase28SourceCandidateRegistrationStatus,"ready_for_manual_phase28_source_trust_review");for(const k of ["externalDataAcquired","networkCommunicationPerformed","authenticationPerformed","automaticExternalAcquisitionPerformed","bettingExecuted","purchaseExecuted","appliedToPrediction","appliedToLearning","phase28AutomaticallyAdvanced"])assert.strictEqual(hand.record[k],false,k);
assert(core.integrityIntact(first));for(const p of [{phase28SourceCandidateRegistrationSnapshot:{tampered:true}},{phase28SourceCandidateRegistrationSnapshotHash:"bad"},{phase28SourceCandidateRegistrationVersion:"bad"}])assert.strictEqual(core.integrityIntact({...first,...p}),false);Object.entries(core.SAFETY).forEach(([k,v])=>assert.strictEqual(first[k],v,k));assert(core.invalidateSourceCandidateRegistration(ok.record,human,options).transitioned);assert.strictEqual(core.expireSourceCandidateRegistration({...first,expiresAt:"2026-01-01"},{},options).expired,false);assert(core.expireSourceCandidateRegistration({...first,expiresAt:"2026-01-01"},human,options).expired);
const mem={v:null,setItem(_k,v){this.v=v},getItem(){return this.v}};assert(core.saveSourceCandidateRegistrationRecords(mem,[ok.record]).saved);assert(core.loadSourceCandidateRegistrationRecords(mem).loaded);mem.v="{";assert.strictEqual(core.loadSourceCandidateRegistrationRecords(mem).loaded,false);
const code=fs.readFileSync(require.resolve("../phase28-4-source-candidate-registration-core.js"),"utf8"),browser={HashimotoPhase283ExternalDataCategoryDefinition:p283};vm.runInNewContext(code,browser);assert(browser.HashimotoPhase284SourceCandidateRegistration);assert(code.includes('require("./phase28-3-external-data-category-definition-core.js")'));assert.throws(()=>vm.runInNewContext(code,{}),/Phase28-3/);assert(!/fetch\s*\(|XMLHttpRequest|WebSocket|EventSource|sendBeacon\s*\(|http\.request|https\.request|child_process|execSync|spawnSync|setInterval\s*\(/.test(code));console.log("phase28SourceCandidateRegistrationCore.test.js: PASS");
