"use strict";
const assert=require("assert"),fs=require("fs"),vm=require("vm"),core=require("../phase29-1-purpose-scope-safety-boundary-definition-core.js"),p2821=core.PHASE2821_REFERENCE,NOW="2027-01-01T00:00:00Z",options={now:()=>new Date(NOW)},human={performedBy:"human",reason:"manual Phase29 definition",explicitConfirmation:true,performedAt:NOW};
function closed(p={}){const b={phase28ClosedId:"closed-1",phase28ClosedStatus:"phase28_closed_confirmed",phase28ClosedResult:"phase28_closed_confirmed",unresolvedClosureIssues:[],criticalIssues:[],blockingConditions:[],recordVersion:21,auditTrail:[{action:"closed_confirmation"}],...p2821.SAFETY};p2821.REFERENCE_IDS.forEach(k=>b[k]=b[k]||`${k}-1`);const snap={...b};return{...b,phase28ClosedSnapshot:snap,phase28ClosedSnapshotHash:p2821.computeSnapshotHash(snap),phase28ClosedVersion:p2821.SCHEMA_VERSION,...p}}
function input(p={}){const r={};for(const k of core.CONTENT_FIELDS)r[k]=["phase29InScope","phase29OutOfScope","phase29Objectives","phase29NonObjectives","prohibitedActions","allowedPlanningActions","assumptions","prerequisites","dependencies","constraints","risks","notes"].includes(k)?[k]:k;for(const k of core.ISSUE_FIELDS)r[k]=[];for(const k of core.REQUIRED_TRUE)r[k]=true;return{...r,...p}}
function create(){const x=core.createDefinition(closed(),input(),human,options,[]);assert(x.created,x.reasons.join());return x.record}function review(){let r=create();r=core.startDefinition(r,human,options).record;return core.submitDefinitionForReview(r,human,options).record}
assert(core.PHASE2821_REFERENCE);assert.strictEqual(core.CURRENT_STAGE,"purpose_scope_safety_boundary_definition");assert.strictEqual(core.NEXT_STAGE,null);assert.strictEqual(core.extractDefinitionCandidates([closed()],[]).length,1);
for(const p of [{phase28ClosedStatus:"phase28_closed_conditionally_confirmed"},{phase28ClosedStatus:"phase28_rejected_confirmed"},{phase28ClosedStatus:"manual_closure_in_progress"},{phase28ClosedResult:"phase28_closed_conditionally_confirmed"},{invalidatedAt:NOW},{expiredAt:NOW},{auditTrail:[]},{recordVersion:0},{phase28ClosedSnapshot:null},{phase28ClosedSnapshotHash:"bad"},{phase28ClosedVersion:"bad"},{unresolvedClosureIssues:["x"]},{criticalIssues:["x"]},{blockingConditions:["x"]},{phase29AutomaticallyStarted:true},{nextPhaseAutomaticallyStarted:true},{closureAutomaticallyReleased:true},{networkCommunicationPerformed:true}])assert.strictEqual(core.validatePhase2821Eligibility({...closed(),...p}).valid,false,JSON.stringify(p));
assert.strictEqual(core.createDefinition(closed(),input(),{},options,[]).created,false);for(const p of [{phase29Purpose:""},{phase29Scope:""},{phase29InScope:[]},{safetyBoundary:""},{prohibitedActions:[]},{privateLocalOnly:false},{planOnly:false},{protectedMode:false},{unresolvedIssues:"bad"}])assert.strictEqual(core.createDefinition(closed(),input(p),human,options,[]).created,false,JSON.stringify(p));
const src=closed(),before=JSON.stringify(src),first=core.createDefinition(src,input(),human,options,[]);assert(first.created);assert.strictEqual(JSON.stringify(src),before);assert(Object.isFrozen(first.record));assert.strictEqual(core.createDefinition(src,input(),human,options,[first.record]).created,false);assert.strictEqual(core.extractDefinitionCandidates([src],[first.record]).length,0);
let r=core.startDefinition(first.record,human,options).record;assert.strictEqual(r.phase29DefinitionStatus,"manual_phase29_definition_in_progress");assert(core.updateDefinition(r,{notes:["updated"]},human,options).updated);r=core.submitDefinitionForReview(r,human,options).record;assert.strictEqual(r.phase29DefinitionStatus,"awaiting_manual_phase29_definition_review");for(const p of [{reviewedBy:""},{reviewedAt:"bad"},{unresolvedIssues:["x"]},{criticalIssues:["x"]},{blockingConditions:["x"]},{privateLocalOnly:false},{planOnly:false},{protectedMode:false}])assert.strictEqual(core.completeDefinition(r,{result:"phase29_purpose_scope_safety_boundary_defined",reviewedBy:"reviewer",reviewedAt:NOW,...p},human,options).completed,false,JSON.stringify(p));
const ok=core.completeDefinition(r,{result:"phase29_purpose_scope_safety_boundary_defined",reviewedBy:"reviewer",reviewedAt:NOW},human,options);assert(ok.completed,ok.reasons.join());assert.strictEqual(ok.record.phase29DefinitionStatus,"phase29_purpose_scope_safety_boundary_defined");assert(ok.record.auditTrail.length>=4);for(const result of core.RESULTS.slice(1)){const x=core.completeDefinition(review(),{result},human,options);assert(x.completed,result)}
assert.strictEqual(ok.record.privateLocalOnly,true);assert.strictEqual(ok.record.planOnly,true);assert.strictEqual(ok.record.protectedMode,true);for(const k of ["networkCommunicationPerformed","externalTransmissionPerformed","webAccessPerformed","apiRequestPerformed","authenticationPerformed","credentialsStored","credentialUsed","automationEnabled","schedulerEnabled","timerEnabled","pollingEnabled","backgroundWorkerEnabled","fileAutomaticallyGenerated","fileAutomaticallyModified","directoryAutomaticallyModified","stagingDataModified","formalDataModified","dataAutomaticallyMigrated","automaticValidationExecuted","automaticCorrectionPerformed","rollbackAutomaticallyExecuted","recoveryAutomaticallyExecuted","learningUpdated","appliedToPrediction","appliedToLearning","bettingExecuted","gitOperationPerformed","githubApiOperationPerformed","publicReleasePerformed","githubPagesPublished","phase29Started","phase29AutomaticallyStarted","nextPhaseAutomaticallyStarted","phase28ClosedAutomaticallyReleased"])assert.strictEqual(ok.record[k],false,k);
assert(core.integrityIntact(ok.record));assert(core.safetyIntact(ok.record));for(const p of [{phase29DefinitionSnapshot:{tampered:true}},{phase29DefinitionSnapshotHash:"bad"},{phase29DefinitionVersion:"bad"}])assert.strictEqual(core.integrityIntact({...ok.record,...p}),false);assert(core.invalidateDefinition(ok.record,human,options).transitioned);const view=core.render(ok.record);assert(view.privateLocalOnly&&view.planOnly&&view.protectedMode&&view.externalCommunicationDisabled&&view.automationDisabled&&view.phase29NotStarted);
const mem={v:null,setItem(_k,v){this.v=v},getItem(){return this.v}};assert(core.saveDefinitions(mem,[ok.record]).saved);assert(core.loadDefinitions(mem).loaded);mem.v="{";assert.strictEqual(core.loadDefinitions(mem).loaded,false);
assert.strictEqual(core.startPhase29,undefined);assert.strictEqual(core.handoffToNextPhase,undefined);const code=fs.readFileSync(require.resolve("../phase29-1-purpose-scope-safety-boundary-definition-core.js"),"utf8"),browser={HashimotoPhase2821Closed:p2821};vm.runInNewContext(code,browser);assert(browser.HashimotoPhase291PurposeScopeSafetyBoundaryDefinition);assert(code.includes('require("./phase28-21-closed-core.js")'));assert.throws(()=>vm.runInNewContext(code,{}),/Phase28-21/);assert(!/fetch\s*\(|XMLHttpRequest|WebSocket|EventSource|sendBeacon\s*\(|http\.request|https\.request|child_process|execSync|spawnSync|setInterval\s*\(|setTimeout\s*\(|(?:new\s+)?(?:Shared)?Worker\s*\(|fs\.writeFile|fs\.mkdir|mkdirSync|writeFileSync|eval\s*\(|new\s+Function\s*\(|Authorization\s*:|Bearer\s+[A-Za-z0-9._~-]+/.test(code));console.log("phase29PurposeScopeSafetyBoundaryDefinitionCore.test.js: PASS");
