"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),p2611=require("../phase26-11-manual-result-preview-validation-intake-decision-core.js"),core=require("../phase26-12-formal-import-candidate-pre-import-approval-core.js");
const root=path.resolve(__dirname,".."),clock={now:()=>new Date("2026-08-13T02:00:00Z")},op={performedBy:"owner",reason:"manual confirmation",explicitConfirmation:true};
const target={validationRecordId:"v1",targetPreviewDataId:"pv1",status:"ready_for_manual_formal_import_candidate_creation",phase2610Snapshot:{preview:{previewDataId:"pv1",previewStatus:"held"}},intakeDecision:{intakeDecisionId:"d1",result:"accepted",conditions:"",handoffDecision:"approved"},unresolvedIssues:[],resultDataRead:true,fileContentAccessed:true,temporaryDataHeld:true,resultDataParsed:true,fileContentParsed:true,resultPreviewCreated:true,temporaryPreviewHeld:true,resultPreviewReady:true,intakeDecisionRecorded:true,previewValidationCompleted:true,formalImportCandidatePreparationReady:true,resultDataStored:false,resultDataImported:false,resultDataApplied:false,resultDataLearned:false,intakeReady:false,formalImportCompleted:false};
const accepted={completed:true,humanResult:"accepted",confirmedBy:"owner",confirmedAt:"2026-08-13T01:00:00Z",reason:"confirmed",details:{}};
const candidate={formalImportCandidateId:"fc1",createdBy:"owner",creationDate:"2026-08-13",creationTime:"11:00",creationReason:"manual import plan",targetDescription:"accepted result rows",dataFormat:"delimited preview",targetColumns:["id","result"],targetRowRange:"1-10",targetCount:10,hasExclusions:true,excludedRowRange:"11-12",excludedCount:2,exclusionReason:"human-planned anomaly exclusion",acceptedConditions:"none",unresolvedIssues:[],knownWarnings:["reviewed"],knownAnomalies:["reviewed"],destination:"results_staging",importUnit:"batch",note:"plan only"};
const executionPlan={importExecutionPlanId:"ip1",plannedExecutor:"owner",role:"local user",plannedDate:"2026-08-14",plannedTime:"10:00",terminal:"private PC",screen:"Private Local",destination:"results_staging",method:"manual formal import",unit:"batch",expectedCount:10,expectedExclusionCount:2,precheckProcedure:"verify approval",executionProcedure:"manual Phase26-13 procedure",interruptionProcedure:"stop and record",cancellationProcedure:"cancel and record",emergencyStopProcedure:"stop safely",completionProcedure:"verify counts",note:"no execution now"};
const destination={destinationId:"dst1",name:"results staging",category:"private local",areaType:"existing",schemaName:"local",tableOrUnit:"race_results",description:"formal result area",existingDataImpact:"possible append",overwritePossible:false,appendOnly:true,updatesIncluded:false,deletesIncluded:false,confirmed:true,confirmedBy:"owner",confirmedAt:"2026-08-13T01:10:00Z"};
const rollbackPlan={completed:true,planId:"rb1",reason:"batch-id rollback plan",confirmedBy:"owner",confirmedAt:"2026-08-13T01:15:00Z",decisionCondition:"count mismatch",plannedExecutor:"owner"};
const failureResponsePlan={completed:true,planId:"fr1",reason:"stop, record, inspect, no auto retry",confirmedBy:"owner",confirmedAt:"2026-08-13T01:16:00Z"};
const approval={preImportApprovalId:"pa1",approvedBy:"owner",approvalDate:"2026-08-13",approvalTime:"11:30",decision:"approved",reason:"all plans confirmed",conditions:"",candidateId:"fc1",previewDataId:"pv1",targetCount:10,excludedCount:2,targetRowRange:"1-10",targetColumns:["id","result"],destination:"results_staging",plannedExecutor:"owner",expiresAt:"2026-08-14T12:00:00Z",recheckRequired:false,secondReviewer:"",secondReviewResult:"",note:"manual"};
const checks=core.CHECK_DEFINITIONS.map(x=>({...x,status:"passed",checkedBy:"owner",checkedAt:"2026-08-13T01:20:00Z",note:"confirmed"}));
const input={formalImportCandidateId:"fc1",candidate,exclusions:[{exclusionRecordId:"ex1",rowNumbers:[11,12],columns:["id"],reason:"anomaly",problemType:"irregular",severity:"medium",relatedCorrectionInstruction:"none",reacquisitionRequired:false,rereadRequired:false,reparseRequired:false,decidedBy:"owner",decidedAt:"2026-08-13T01:05:00Z",note:"plan only"}],scopeReview:accepted,countReview:{...accepted,result:"exact_match",totalCount:12,tolerance:"none"},structureReview:accepted,duplicateRiskReview:accepted,conditionalRequirements:[],executionPlan,destination,rollbackPlan,failureResponsePlan,approval,relationship:{candidateCreator:"owner",plannedExecutor:"owner",approver:"owner",samePersonCreatorExecutor:true,samePersonCreatorApprover:true,samePersonExecutorApprover:true,samePersonAllowed:true,separationRequired:false,separationReason:"private local only",secondReviewer:"",secondReviewResult:"",secondReviewedAt:""},checklist:checks};
assert.strictEqual(core.PHASE2611_REFERENCE,p2611);assert(core.CHECK_DEFINITIONS.length>=65);assert(core.validateTarget(target).valid);
for(const status of["intake_accepted","intake_decision_recorded","intake_cancelled"])assert(!core.validateTarget({...target,status}).valid,status);
for(const result of["on_hold","returned_for_reparse","rejected","cancelled"])assert(!core.validateTarget({...target,intakeDecision:{...target.intakeDecision,result}}).valid,result);
assert(!core.validateTarget({...target,intakeDecision:{...target.intakeDecision,result:"accepted_with_conditions",conditions:""}}).valid);
assert(!core.validateTarget({...target,targetPreviewDataId:"",phase2610Snapshot:{preview:{previewDataId:"",previewStatus:"held"}}}).valid);
assert(!core.validateTarget({...target,phase2610Snapshot:{preview:{previewDataId:"pv1",previewStatus:"discarded"}}}).valid);
for(const [name,change]of[["creator",{candidate:{...candidate,createdBy:""}}],["rows",{candidate:{...candidate,targetRowRange:""}}],["columns",{candidate:{...candidate,targetColumns:[]}}],["count",{candidate:{...candidate,targetCount:null}}],["exclusion",{candidate:{...candidate,hasExclusions:true,excludedCount:2,excludedRowRange:"",exclusionReason:""}}]])assert(!core.createCandidate(target,{...input,...change},op,clock).created,name);
for(const [name,change]of[["countReview",{countReview:{...accepted,result:"exact_match",totalCount:12,completed:false}}],["structure",{structureReview:{...accepted,completed:false}}],["duplicate",{duplicateRiskReview:{...accepted,completed:false}}]]){const created=core.createCandidate(target,{...input,...change},op,clock);assert(created.created,name)}
assert(!core.createCandidate(target,input,{...op,explicitConfirmation:false},clock).created);
const created=core.createCandidate(target,input,op,clock);assert(created.created);let r=created.record;
for(const next of["validating_candidate_scope","validating_candidate_counts","validating_duplicate_risk","preparing_import_execution_plan","awaiting_manual_pre_import_approval","pre_import_approval_recorded"]){const x=core.transition(r,next,op,target,clock);assert(x.transitioned,next);r=x.record}
const ready=core.transition(r,"ready_for_manual_formal_import_execution",op,target,clock);assert(ready.transitioned);assert(ready.record.formalImportExecutionReady&&ready.record.preImportApprovalRecorded&&ready.record.formalImportPlanPrepared);
for(const[k,v]of Object.entries(core.ALWAYS_FALSE_FLAGS))assert.strictEqual(ready.record[k],v,k);
function rejectReady(change){const x=core.updateRecord(r,change,op,clock).record;return core.transition(x,"ready_for_manual_formal_import_execution",op,target,clock)}
for(const [name,change]of[["scope",{scopeReview:{...accepted,completed:false}}],["counts",{countReview:{...accepted,result:"needs_review",totalCount:12}}],["structure",{structureReview:{...accepted,completed:false}}],["duplicate",{duplicateRiskReview:{...accepted,completed:false}}],["executor",{executionPlan:{...executionPlan,plannedExecutor:""}}],["date",{executionPlan:{...executionPlan,plannedDate:""}}],["procedure",{executionPlan:{...executionPlan,executionProcedure:""}}],["interrupt",{executionPlan:{...executionPlan,interruptionProcedure:""}}],["cancel",{executionPlan:{...executionPlan,cancellationProcedure:""}}],["stop",{executionPlan:{...executionPlan,emergencyStopProcedure:""}}],["destination",{destination:{...destination,name:""}}],["rollback",{rollbackPlan:{...rollbackPlan,completed:false}}],["approver",{approval:{...approval,approvedBy:""}}],["approvalDate",{approval:{...approval,approvalDate:""}}],["approvalReason",{approval:{...approval,reason:""}}],["candidateMismatch",{approval:{...approval,candidateId:"other"}}],["previewMismatch",{approval:{...approval,previewDataId:"other"}}],["countMismatch",{approval:{...approval,targetCount:9}}],["excludedMismatch",{approval:{...approval,excludedCount:1}}],["rangeMismatch",{approval:{...approval,targetRowRange:"2-10"}}],["destinationMismatch",{approval:{...approval,destination:"other"}}]])assert(!rejectReady(change).transitioned,name);
for(const status of["failed","unchecked","needs_review"]){const bad=checks.map((x,i)=>i?x:{...x,status});assert(!rejectReady({checklist:bad}).transitioned,status)}
assert(!rejectReady({approval:{...approval,decision:"approved_with_conditions",conditions:""}}).transitioned);
const invalidated=core.updateRecord(r,{candidate:{...candidate,targetRowRange:"1-9"}},op,clock);assert(invalidated.approvalInvalidated&&invalidated.record.approval.recheckRequired);assert(!core.transition(invalidated.record,"ready_for_manual_formal_import_execution",op,target,clock).transitioned);
for(const next of["pre_import_approval_on_hold","pre_import_approval_rejected","formal_import_candidate_cancelled"]){const base=next==="formal_import_candidate_cancelled"?created.record:core.transition(core.transition(core.transition(core.transition(core.transition(created.record,"validating_candidate_scope",op,target,clock).record,"validating_candidate_counts",op,target,clock).record,"validating_duplicate_risk",op,target,clock).record,"preparing_import_execution_plan",op,target,clock).record,"awaiting_manual_pre_import_approval",op,target,clock).record;const x=core.transition(base,next,op,target,clock);assert(x.transitioned,next);assert(!x.record.formalImportExecutionReady)}
assert(!core.transition(created.record,"ready_for_manual_formal_import_execution",op,target,clock).transitioned);
const source=fs.readFileSync(path.join(root,"phase26-12-formal-import-candidate-pre-import-approval-core.js"),"utf8"),html=fs.readFileSync(path.join(root,"private-local.html"),"utf8"),css=fs.readFileSync(path.join(root,"dashboard.css"),"utf8"),readme=fs.readFileSync(path.join(root,"README.md"),"utf8");
for(const pattern of[/localStorage\s*\.\s*setItem/,/indexedDB\s*\.\s*open/,/fetch\s*\(/,/XMLHttpRequest/,/WebSocket\s*\(/,/innerHTML\s*=/,/createObjectURL/,/executeImport\s*\(/,/rollback\s*\(/])assert(!pattern.test(source),pattern);
for(const marker of['id="phase26-12-formal-import-candidate-pre-import-approval"',"対象となるPhase26-11記録","現在状態","Phase26-11受入判定","条件付き受入条件","previewDataId","正式インポート候補ID","候補作成者","対象行範囲","対象列","対象件数","除外行範囲","除外件数","除外理由","件数比較結果","必須列最終確認","識別子最終確認","日付・時点最終確認","対象列最終確認","重複リスク確認","条件付き受入条件確認","想定取込先","正式取込実行計画","実行予定者・取込予定日時","中断・取消・失敗時対応計画","ロールバック方針","取込前チェックリスト","取込前承認記録・第二確認欄","未解決事項","状態遷移履歴","監査履歴","安全フラグ一覧","禁止処理一覧","Private Local only","PLAN_ONLY","protectedMode","正式インポート未実行","正式保存なし","適用・学習なし"])assert(html.includes(marker),marker);
assert(css.includes(".phase2612-panel"));assert(readme.includes("Phase26-12 Formal Import Candidate and Pre-Import Approval Core"));console.log("phase26FormalImportCandidatePreImportApprovalCore.test.js: PASS");
