const assert = require("assert"), fs = require("fs"), path = require("path");
const core = require("../phase23-6-manual-formal-import-execution-core.js");
const root = path.join(__dirname, ".."), read = (file) => fs.readFileSync(path.join(root, file), "utf8");
function memory(initial = {}, behavior = {}) { const data = { ...initial }; return { data, getItem(key) { const value = Object.prototype.hasOwnProperty.call(data, key) ? data[key] : null; return behavior.corruptReadKey === key && value !== null ? `${value}x` : value; }, setItem(key, value) { if (behavior.failKey === key) throw new Error("quota"); data[key] = String(value); }, removeItem() { throw new Error("physical delete forbidden"); } }; }
const records = { meeting: { meetingId: "m1", raceDate: "2026-07-19", venueCode: "TOK" }, race: { raceId: "r1", meetingId: "m1", raceNumber: 1, distance: 1600 }, runner: { runnerId: "runner1", raceId: "r1", horseNumber: 1, horseName: "A" }, oddsSnapshot: { raceId: "r1", betType: "win", combination: "1", capturedAt: "2026-07-19T11:00:00+09:00", odds: 2 }, result: { raceId: "r1", runnerId: "runner1", horseNumber: 1, finishPosition: 1 }, payout: { raceId: "r1", betType: "win", combination: "1", payoutAmount: 200 }, acquisitionRecord: { acquisitionId: "a1", dataType: "meeting", sourceValidationId: "v-meeting", fileHash: "h-meeting", stagingId: "s-meeting" } };
function prep(type, mode = "insert_only", overrides = {}) { return { importPreparationId: `p-${type}`, preparationGroupId: "group1", gateRecordId: `g-${type}`, stagingId: `s-${type}`, stagingVersion: 1, sourceValidationId: `v-${type}`, fileHash: `h-${type}`, dataType: type, providerId: "manual", candidateRecordCount: 1, importMode: mode, plannedChangesSummary: {}, dependencySummary: { confirmed: true }, impactSummary: { level: "low" }, rollbackPreparation: { confirmed: true }, verificationPlan: { planned: true }, operatorChecklist: { all: true }, reviewApprovedBy: "Reviewer", reviewApprovalReason: "ready", reviewApprovedAt: "2026-07-19T09:00:00+09:00", preparationStatus: "ready_for_formal_import_execution", readyForFormalImportExecution: true, formalImportExecuted: false, expectedConflictCount: 0, ...overrides }; }
function staged(type, overrides = {}) { return { stagingId: `s-${type}`, version: 1, sourceValidationId: `v-${type}`, sourceFileHash: `h-${type}`, dataType: type, stagingStatus: "staged", normalizedRecords: [records[type]], ...overrides }; }
function item(type, mode, overrides = {}) { return { preparation: prep(type, mode, overrides.preparation), staging: staged(type, overrides.staging) }; }
const approval = (overrides = {}) => ({ operator: "Executor", reason: "human approved formal import", approvedAt: "2026-07-19T10:00:00+09:00", confirmation: core.CONFIRM_EXECUTE, protectedMode: true, privateLocalOnly: true, noExternalCommunicationConfirmed: true, noAutomaticProcessingConfirmed: true, noAutomaticPurchaseConfirmed: true, noAutomaticBettingConfirmed: true, noIpatConnectionConfirmed: true, ...overrides });
const context = (overrides = {}) => ({ preparationsReady: true, stagingVerified: true, fatalCount: 0, errorCount: 0, unresolvedConflictCount: 0, dependenciesConfirmed: true, planConfirmed: true, snapshotCreated: true, snapshotReadBack: true, snapshotChecksumVerified: true, rollbackConfirmed: true, verificationPlanConfirmed: true, highImpactConfirmed: true, operatorChecklistComplete: true, ...overrides });

assert.strictEqual(core.FORMAL_DATA_KEY, "hashimotoKeibaAi.phase23.formalData.v1"); assert.strictEqual(core.EXECUTION_KEY, "hashimotoKeibaAi.phase23.manualFormalImportExecution.v1"); assert.strictEqual(core.SNAPSHOT_KEY, "hashimotoKeibaAi.phase23.preImportSnapshot.v1"); assert.strictEqual(core.PENDING_KEY, "hashimotoKeibaAi.phase23.formalData.pending.v1");
for (const status of ["rejected", "cancelled", "expired", "manual_review_in_progress"]) assert.strictEqual(core.eligiblePreparations({ records: [prep("meeting", "insert_only", { preparationStatus: status, readyForFormalImportExecution: false })] }).length, 0); assert.strictEqual(core.eligiblePreparations({ records: [prep("meeting"), prep("race", "insert_only", { formalImportExecuted: true })] }).length, 1);
for (const type of core.TYPES) assert.ok(core.naturalKeyValid(type, records[type]), type); assert.ok(!core.naturalKeyValid("meeting", {})); assert.deepStrictEqual(core.immutableFields("race"), ["raceId", "meetingId"]);
let check = core.validateStagingReference(prep("meeting"), { records: [staged("meeting")] }); assert.ok(check.valid); for (const [change, expected] of [[{ stagingStatus: "cancelled" }, "staging_not_staged"], [{ stagingId: "other" }, "staging_reference_missing"], [{ version: 2 }, "staging_version_mismatch"], [{ sourceValidationId: "other" }, "source_validation_id_mismatch"], [{ sourceFileHash: "other" }, "file_hash_mismatch"], [{ dataType: "race" }, "data_type_mismatch"], [{ normalizedRecords: [] }, "record_count_mismatch"]]) { const p = change.stagingId ? prep("meeting", "insert_only", { stagingId: "s-meeting" }) : prep("meeting"); const result = core.validateStagingReference(p, { records: [staged("meeting", change)] }); assert.ok(result.problems.includes(expected), expected); }

const allItems = core.TYPES.map((type) => item(type)); let formal = core.defaultFormalStore(); let generated = core.generateExecutionPlan(allItems, formal, { executionRecordId: "exec1", preparationGroupId: "group1" }, new Date("2026-07-19T01:00:00Z")); assert.ok(generated.generated, JSON.stringify(generated)); assert.deepStrictEqual(generated.plan.orderedOperations.map((op) => op.dataType), core.TYPES); assert.strictEqual(generated.plan.expectedInsertCount, 7);
assert.strictEqual(core.generateExecutionPlan([item("meeting", "manual_resolution_required")], formal).reason, "plan_validation_failed");
const existingMeeting = { recordId: "fm1", dataType: "meeting", naturalKey: "m1", payload: records.meeting, recordVersion: 1, active: true, createdAt: "2026-07-19T00:00:00Z", updatedAt: "2026-07-19T00:00:00Z", provenance: [] }, withMeeting = core.normalizeFormalStore({ records: [existingMeeting] }); assert.strictEqual(core.generateExecutionPlan([item("meeting", "insert_only")], withMeeting).reason, "plan_validation_failed"); assert.strictEqual(core.generateExecutionPlan([item("meeting", "skip_duplicate")], withMeeting).plan.expectedSkipCount, 1);
const changedMeeting = { ...records.meeting, name: "updated" }, updateItem = { preparation: prep("meeting", "update_existing"), staging: staged("meeting", { normalizedRecords: [changedMeeting] }) }; let updatePlan = core.generateExecutionPlan([updateItem], withMeeting, { executionRecordId: "update1" }); assert.ok(updatePlan.generated); let appliedUpdate = core.applyPlan(updatePlan.plan, withMeeting, { ...updateItem.preparation, operator: "Human" }, new Date("2026-07-19T02:00:00Z")); assert.strictEqual(appliedUpdate.formal.records[0].recordVersion, 2); assert.strictEqual(appliedUpdate.formal.records[0].provenance.length, 1);
assert.strictEqual(core.generateExecutionPlan([item("meeting", "update_existing")], formal).reason, "plan_validation_failed"); const ambiguous = core.normalizeFormalStore({ records: [existingMeeting, { ...existingMeeting, recordId: "fm2" }] }); assert.strictEqual(core.generateExecutionPlan([item("meeting", "update_existing")], ambiguous).reason, "plan_validation_failed"); assert.strictEqual(core.generateExecutionPlan([item("race")], formal).reason, "plan_validation_failed"); assert.strictEqual(core.generateExecutionPlan([item("race")], withMeeting, { circularDependency: true }).reason, "plan_validation_failed"); assert.strictEqual(core.generateExecutionPlan([item("race")], withMeeting, { branchDependency: true }).reason, "plan_validation_failed");

let snapshotResult = core.createSnapshot(generated.plan, formal, "Executor", new Date("2026-07-19T01:01:00Z")); assert.ok(snapshotResult.created); let mem = memory(); let snapSave = core.saveSnapshot(snapshotResult.snapshot, mem); assert.ok(snapSave.saved && snapSave.readBackVerified && snapSave.checksumVerified);
assert.ok(core.approvalProblems(context(), approval({ confirmation: "formal import execute" })).includes("confirmation_mismatch")); assert.ok(core.approvalProblems(context(), approval({ operator: "" })).includes("operator_required")); assert.ok(core.approvalProblems(context(), approval({ approvedAt: "2099-01-01T00:00:00+09:00" })).includes("approval_datetime_future")); assert.ok(core.approvalProblems(context({ snapshotCreated: false }), approval()).includes("snapshot_confirmation_required"));
const inputs = { plan: generated.plan, snapshot: snapshotResult.snapshot, items: allItems, approval: approval(), context: context() }; const beforeSources = JSON.stringify(allItems); let executed = core.executeManual(inputs, mem, new Date("2026-07-19T01:02:00Z")); assert.ok(executed.executed, executed.reason); assert.strictEqual(executed.executionRecord.status, "verified"); assert.strictEqual(executed.executionRecord.actualCounts.insert, 7); assert.strictEqual(executed.formalStore.records.length, 7); assert.strictEqual(JSON.stringify(allItems), beforeSources); assert.strictEqual(core.executeManual(inputs, mem).reason, "duplicate_execution");
core.locks.add("locked"); const lockPlan = { ...generated.plan, executionRecordId: "lock-exec", preparationGroupId: "locked" }; assert.strictEqual(core.executeManual({ ...inputs, plan: lockPlan }, mem).reason, "execution_lock"); core.locks.delete("locked");
const staleMem = memory(); core.saveSnapshot(snapshotResult.snapshot, staleMem); staleMem.setItem(core.FORMAL_DATA_KEY, JSON.stringify(core.normalizeFormalStore({ records: [existingMeeting] }))); assert.strictEqual(core.executeManual(inputs, staleMem).reason, "stale_plan");
for (const failKey of [core.PENDING_KEY, core.FORMAL_DATA_KEY, core.EXECUTION_KEY]) { const failed = memory({}, { failKey }); core.saveSnapshot(snapshotResult.snapshot, failed); const original = failed.getItem(core.FORMAL_DATA_KEY); const result = core.executeManual(inputs, failed, new Date("2026-07-19T01:02:00Z")); assert.ok(!result.executed); const after = failed.getItem(core.FORMAL_DATA_KEY); assert.ok(original === after || JSON.parse(after).records.length === 0, failKey); assert.strictEqual(result.partialApplied, false); }

const rollbackApproval = { approvedBy: "Rollback Owner", reason: "human rollback", approvedAt: "2026-07-19T12:00:00+09:00", confirmation: core.CONFIRM_ROLLBACK }; assert.ok(core.rollbackProblems(executed.executionRecord, snapshotResult.snapshot, rollbackApproval, executed.formalStore).length === 0); assert.ok(core.rollbackProblems(executed.executionRecord, snapshotResult.snapshot, { ...rollbackApproval, confirmation: "wrong" }, executed.formalStore).includes("rollback_confirmation_mismatch")); assert.ok(core.rollbackProblems(executed.executionRecord, null, rollbackApproval, executed.formalStore).includes("snapshot_missing")); let rolled = core.rollbackManual(executed.executionRecord, snapshotResult.snapshot, executed.formalStore, rollbackApproval, mem, new Date("2026-07-19T03:00:00Z")); assert.ok(rolled.rolledBack); assert.ok(rolled.formalStore.records.every((record) => record.active === false)); assert.ok(rolled.formalStore.records.every((record) => record.provenance.some((event) => event.action === "rollback_deactivate")));
assert.strictEqual(core.transition("verified", "execution_in_progress").reason, "terminal_locked"); assert.strictEqual(core.transition("awaiting_execution_plan", "snapshot_created").reason, "invalid_transition");
const dangerous = core.stripDangerous({ APIKey: "x", password: "x", cookie: "x", accessToken: "x", rawPayload: "x", nested: { constructor: "x", safe: 1 } }); assert.strictEqual(dangerous.nested.safe, 1); assert.throws(() => core.stripDangerous({ fn() {} }), /json_unsupported/); for (const key of ["APIKey", "password", "cookie", "accessToken", "rawPayload"]) assert.ok(!Object.prototype.hasOwnProperty.call(dangerous, key));

const code = read("phase23-6-manual-formal-import-execution-core.js") + read("phase23-6-main-dashboard-integration.js"); for (const pattern of [/\bfetch\s*\(/, /XMLHttpRequest/, /\bWebSocket\s*\(/, /\bEventSource\s*\(/, /sendBeacon/, /setInterval\s*\(/, /addEventListener\s*\(\s*["']storage/]) assert.ok(!pattern.test(code)); assert.ok(!/\.removeItem\s*\(/.test(code)); assert.ok(!/automaticRollback\s*:\s*true/.test(code));
const index = read("index.html"), local = read("private-local.html"); assert.ok(index.includes('id="phase23-manual-formal-import-execution"')); assert.ok(local.includes('href="index.html#phase23-manual-formal-import-execution"')); assert.ok(index.indexOf('id="phase23-formal-import-preparation-review"') < index.indexOf('id="phase23-manual-formal-import-execution"')); assert.ok(index.indexOf("phase23-5-main-dashboard-integration.js") < index.indexOf("phase23-6-manual-formal-import-execution-core.js")); assert.ok(index.indexOf("phase23-6-manual-formal-import-execution-core.js") < index.indexOf("phase23-6-main-dashboard-integration.js"));
for (const file of ["index.html", "private-local.html", "phase22-22-private-local.html"]) { const html = read(file), ids = [...html.matchAll(/\bid="([^"]+)"/g)].map((match) => match[1]); assert.strictEqual(ids.length, new Set(ids).size); for (const match of html.matchAll(/<script[^>]+src="([^"]+)"/g)) if (!/^(?:https?:)?\/\//.test(match[1])) assert.ok(fs.existsSync(path.join(root, match[1])), match[1]); }
console.log("Phase23-6 manual formal import execution core tests passed");
