"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path");
const core=require("../phase24-external-data-acquisition-foundation.js");
const root=path.resolve(__dirname,".."),now=new Date("2026-07-24T03:00:00.000Z");
let store=core.defaultStore();
const source={sourceId:"official-1",name:"公式参照元",sourceType:"official_website",officialClassification:"official",purpose:"競馬データ取得計画",referenceUrl:"https://example.invalid/reference-only",termsStatus:"confirmed",usageConditionsStatus:"confirmed",robotsStatus:"confirmed",redistributionStatus:"confirmed",storageStatus:"confirmed",createdBy:"operator"};
let r=core.registerSource(store,source,now);assert.equal(r.registered,true);store=r.store;
r=core.registerTarget(store,{targetId:"odds-1",sourceId:"official-1",targetType:"odds",method:"json",allowedScopes:["win odds"],prohibitedScopes:["credentials"],frequencyCandidate:"manual only",timing:"before race",freshnessRequirement:"record planned time",plannedAcquisitionAt:"2026-07-25T01:00:00Z",createdBy:"operator"},now);assert.equal(r.registered,true);store=r.store;assert.equal(r.target.automaticSchedule,false);
const matchingPolicy=Object.fromEntries(core.MATCH_POLICY_FIELDS.map(k=>[k,`${k} manual match`]));
r=core.registerFormat(store,{formatId:"odds-json-v1",targetId:"odds-1",formatType:"JSON",requiredFields:core.ODDS_FIELDS,optionalFields:["horseName"],fieldTypes:{value:"number"},characterEncoding:"UTF-8",timeBasis:"JST",idRules:{raceId:"manual"},matchingPolicy,createdBy:"operator"},now);assert.equal(r.registered,true);store=r.store;
r=core.addValidationRule(store,{ruleId:"odds-positive",targetId:"odds-1",field:"value",ruleType:"range",description:"オッズ値を人間が確認",severity:"error",createdBy:"operator"},now);assert.equal(r.added,true);store=r.store;
const request={requestId:"request-1",sourceId:"official-1",targetId:"odds-1",formatId:"odds-json-v1",plannedAcquisitionAt:"2026-07-25T01:00:00Z",reason:"将来取得の安全確認",requestedBy:"operator",checksumCandidate:"sha256 candidate"};
r=core.createRequest(store,request,now);assert.equal(r.created,true);store=r.store;assert.equal(r.request.acquisitionExecuted,false);assert.equal(r.request.externalCommunicationExecuted,false);
assert(core.createRequest(store,{...request,requestId:"request-2"},now).problems.includes("duplicate_active_request"));
r=core.transitionRequest(store,"request-1","awaiting_manual_review",{operator:"reviewer",reason:"review requested"},now);store=r.store;
r=core.transitionRequest(store,"request-1","manual_review_in_progress",{operator:"reviewer",reason:"manual review started"},now);store=r.store;
assert.equal(core.approveRequest(store,"request-1",{reviewer:"reviewer",reviewedAt:now.toISOString(),reason:"missing"},now).approved,false);
const approval={reviewer:"reviewer",reviewedAt:now.toISOString(),reason:"安全境界を手動確認",officialityConfirmed:true,termsConfirmed:true,robotsConfirmed:true,redistributionConfirmed:true,storageConfirmed:true,privateLocalConfirmed:true,noCommunicationConfirmed:true};
r=core.approveRequest(store,"request-1",approval,now);assert.equal(r.approved,true);store=r.store;assert.equal(r.request.status,"approved_for_future_acquisition");assert.equal(r.approval.futureAcquisitionOnly,true);assert.equal(r.approval.acquisitionExecuted,false);
assert.equal(core.transitionRequest(store,"request-1","cancelled",{operator:"reviewer",reason:"overwrite"},now).reason,"terminal_locked");
r=core.createHandoffPlan(store,"request-1",{handoffReason:"人間承認後の候補化のみ",owner:"operator",validationPlan:"preview then validate",completionCriteria:"manual Phase23 approval",requiredEvidence:"metadata only"},now);assert.equal(r.created,true);store=r.store;assert.equal(r.plan.automaticHandoff,false);assert.equal(r.plan.phase23ImportExecuted,false);assert.equal(r.plan.phase22Applied,false);
assert.deepEqual(Object.keys(core.sanitize({password:"x",apiToken:"y",rawPayload:"z",rawHtml:"h",safe:"ok"})),["safe"]);
r=core.registerSource(store,{...source,sourceId:"auth-1",authenticationRequired:true},now);let blocked=r.store;
r=core.registerTarget(blocked,{targetId:"auth-target",sourceId:"auth-1",targetType:"race_card",method:"api",createdBy:"operator"},now);blocked=r.store;
r=core.createRequest(blocked,{requestId:"auth-request",sourceId:"auth-1",targetId:"auth-target",plannedAcquisitionAt:"2026-07-26T01:00:00Z",reason:"test",requestedBy:"operator"},now);blocked=r.store;
blocked=core.transitionRequest(blocked,"auth-request","awaiting_manual_review",{operator:"reviewer",reason:"review"},now).store;
blocked=core.transitionRequest(blocked,"auth-request","manual_review_in_progress",{operator:"reviewer",reason:"review"},now).store;
assert(core.approveRequest(blocked,"auth-request",approval,now).problems.includes("authentication_required_source_forbidden"));
function memoryStorage(initial=null,bad=false){let value=initial,writes=0;return{getItem(){return bad&&writes===1?"corrupt":value},setItem(_k,v){writes++;value=v},value(){return value}}}
const storage=memoryStorage();assert.equal(core.saveStore(store,storage,now).saved,true);assert.equal(core.loadStore(storage).store.requests.length,1);
const original=JSON.stringify(core.defaultStore()),failing=memoryStorage(original,true);assert.equal(core.saveStore(store,failing,now).saved,false);assert.equal(failing.value(),original);
const coreText=fs.readFileSync(path.join(root,"phase24-external-data-acquisition-foundation.js"),"utf8"),integrationText=fs.readFileSync(path.join(root,"phase24-1-main-dashboard-integration.js"),"utf8"),html=fs.readFileSync(path.join(root,"index.html"),"utf8"),privateHtml=fs.readFileSync(path.join(root,"private-local.html"),"utf8"),css=fs.readFileSync(path.join(root,"dashboard.css"),"utf8"),readme=fs.readFileSync(path.join(root,"README.md"),"utf8"),docs=fs.readFileSync(path.join(root,"docs","phase24-1-external-data-acquisition-foundation.md"),"utf8");
for(const token of["fetch(","XMLHttpRequest","WebSocket(","EventSource(","sendBeacon(","setInterval("])assert.equal((coreText+integrationText).includes(token),false,token);
assert(html.includes('id="phase24-external-data-acquisition-foundation"'));assert(html.includes("phase24-1-main-dashboard-integration.js"));assert(privateHtml.includes("#phase24-external-data-acquisition-foundation"));assert(css.includes(".phase241-panel"));assert(readme.includes("Phase24-1"));assert(docs.includes("HTTP通信"));assert(core.auditText(store).includes("No HTTP"));
console.log("phase24ExternalDataAcquisitionFoundation.test.js: PASS");
