"use strict";
const assert=require("assert"),fs=require("fs"),vm=require("vm"),core=require("../phase28-1-purpose-scope-safety-boundary-definition.js"),p27=core.PHASE2726_REFERENCE;
function phase27(p={}){const base={phase27FinalClosureStatus:"phase27_final_closure_confirmed",phase27FinalClosureResult:"confirm_phase27_final_closure",recordVersion:3,auditTrail:[{action:"result_decision"}],stableStateConfirmed:true,workingTreeSafe:true,mainOriginMainMatch:true,requiredTestsPassed:true,requiredModulesConfirmed:true,requiredUiConfirmed:true,requiredConfigConfirmed:true,correctionRequired:false,rollbackRequired:false,recoveryRequired:false,nextPhaseAutomaticallyStarted:false,...p27.SAFETY};const snapshot={...base};return{...base,phase27FinalClosureSnapshot:snapshot,phase27FinalClosureSnapshotHash:p27.computeSnapshotHash(snapshot),phase27FinalClosureVersion:p27.SCHEMA_VERSION,...p}}
const record=phase27(),before=JSON.stringify(record),definition=core.definition();
assert(core&&core.PHASE2726_REFERENCE);assert.strictEqual(core.CURRENT_STAGE,"definition");assert(core.PURPOSE);assert(Array.isArray(core.IN_SCOPE)&&core.IN_SCOPE.length);assert(Array.isArray(core.OUT_OF_SCOPE)&&core.OUT_OF_SCOPE.length);assert.strictEqual(core.PHASE28_STAGES.length,21);
core.REQUIRED_TRUE.forEach(k=>assert.strictEqual(core.SAFETY_BOUNDARY[k],true,k));core.REQUIRED_FALSE.forEach(k=>assert.strictEqual(core.SAFETY_BOUNDARY[k],false,k));
assert(core.evaluateSafetyGate(core.SAFETY_BOUNDARY,record).available);for(const p of [{phase27FinalClosureStatus:"bad"},{phase27FinalClosureResult:"bad"},{invalidatedAt:"2027-01-01"},{expiredAt:"2027-01-01"},{phase27FinalClosureSnapshotHash:"bad"},{protectedMode:false},{stableStateConfirmed:false},{correctionRequired:true},{nextPhaseAutomaticallyStarted:true}])assert.strictEqual(core.evaluateSafetyGate({},phase27(p)).available,false,JSON.stringify(p));
for(const k of core.REQUIRED_TRUE)assert.strictEqual(core.evaluateSafetyGate({[k]:false},record).available,false,k);for(const k of core.REQUIRED_FALSE)assert.strictEqual(core.evaluateSafetyGate({[k]:true},record).available,false,k);
for(const k of ["executionImplemented","networkCommunicationImplemented","automaticAcquisitionImplemented","automaticBettingImplemented","automaticApplicationImplemented","automaticLearningImplemented"])assert.strictEqual(definition[k],false,k);
for(const value of [core.IN_SCOPE,core.OUT_OF_SCOPE,core.SAFETY_BOUNDARY,core.PHASE28_STAGES,definition])assert(Object.isFrozen(value));assert.throws(()=>core.IN_SCOPE.push("mutation"));
const elements={};for(const id of ["p281-gate-status","p281-gate-reasons","p281-current-stage"])elements[id]={textContent:"",dataset:{}};assert(core.render({getElementById:id=>elements[id]},core.SAFETY_BOUNDARY,record).available);assert.strictEqual(elements["p281-current-stage"].textContent,"definition");assert.strictEqual(core.render(null,{},record).available,true);assert.strictEqual(JSON.stringify(record),before);
const code=fs.readFileSync(require.resolve("../phase28-1-purpose-scope-safety-boundary-definition.js"),"utf8"),browser={HashimotoPhase2726FinalClosure:p27};vm.runInNewContext(code,browser);assert(browser.HashimotoPhase281PurposeScopeSafetyBoundary);assert(code.includes('require("./phase27-26-phase27-final-closure-core.js")'));assert.throws(()=>vm.runInNewContext(code,{}),/Phase27-26/);
assert(!/fetch\s*\(|XMLHttpRequest|WebSocket|EventSource|sendBeacon\s*\(|http\.request|https\.request|child_process|execSync|spawnSync|setInterval\s*\(/.test(code));console.log("phase28PurposeScopeSafetyBoundaryDefinition.test.js: PASS");
