"use strict";
const assert = require("assert"), fs = require("fs"), path = require("path");
const core = require("../phase26-23-manual-post-registration-acceptance-core.js");
const op = reason => ({ performedBy: "human-acceptor", reason, explicitConfirmation: true });
const target = (overrides = {}) => ({ phase2622DecisionRecordExists: true, decisionStatus: "ready_for_manual_post_registration_acceptance", decisionResult: "accepted", decisionRecordId: "decision-22", sourceVerificationRecordId: "verification-21", sourceExecutionRecordId: "execution-20", approvalRecordId: "approval-19", preparationRecordId: "preparation-18", acceptanceApprovalRecordId: "approval-17", acceptanceRecordId: "acceptance-16", importRecordId: "import-13", decisionMakerId: "decider", decisionMakerName: "Decider", decisionCompletedAt: "2026-08-01T01:00:00Z", decisionReason: "全件整合", stateTransitionHistory: [{ to: "manual_post_registration_verification_decision_completed" }, { to: "ready_for_manual_post_registration_acceptance" }], phase2621VerificationReferenceValid: true, phase2620ExecutionReferenceValid: true, phase2619ApprovalReferenceValid: true, phase2618PreparationReferenceValid: true, phase2617AcceptanceApprovalReferenceValid: true, phase2616AcceptanceReferenceValid: true, phase2613ImportReferenceValid: true, verificationSummary: { countConsistencyStatus: "consistent", verificationStatus: "completed", verificationResult: "completed", unverifiedItemCount: 0, unresolvedObservationCount: 0, correctionCandidateCount: 0, rollbackCandidateCount: 0, unresolvedAbnormalityCount: 0 }, countSummary: { expectedRegisteredCount: 1, successfulRegistrationCount: 1, actualRegisteredCount: 1, createdRecordCount: 1 }, registrationRecordReferences: ["registered-1"], evidenceReferences: ["evidence-22"], executionResultSnapshot: { result: "completed" }, verificationResultSnapshot: { result: "completed" }, decisionResultSnapshot: { result: "accepted" }, protectedMode: true, planOnly: true, ...overrides });
const input = (overrides = {}) => ({ acceptorId: "acceptor-1", acceptorName: "Human Acceptor", acceptanceReason: "最終受入確認", phase26_22DecisionRecordId: "decision-22", phase26_21VerificationRecordId: "verification-21", phase26_20ExecutionRecordId: "execution-20", phase26_19ApprovalRecordId: "approval-19", phase26_18PreparationRecordId: "preparation-18", previousAcceptanceApprovalRecordId: "approval-17", previousAcceptanceRecordId: "acceptance-16", importRecordId: "import-13", acceptanceScope: "registered-1", acceptedRegistrationCount: 1, acceptanceConfirmation: true, decisionResultAcknowledgement: true, verificationResultAcknowledgement: true, countConsistencyAcknowledgement: true, evidenceAcknowledgement: true, noCorrectionCandidateAcknowledgement: true, noRollbackCandidateAcknowledgement: true, protectedModeAcknowledgement: true, planOnlyAcknowledgement: true, manualAcceptanceAcknowledgement: true, ...overrides });
const item = (overrides = {}) => ({ acceptanceItemId: "accept-item-1", sourceItemId: "source-1", targetRegistrationId: "target-1", createdRecordReference: "registered-1", verificationItemId: "verification-item-1", decisionReference: "decision-22", acceptanceStatus: "accepted", accepted: true, recordFound: true, referenceMatched: true, contentVerified: true, evidenceVerified: true, countIncluded: true, beforeSnapshotReference: "before-1", afterSnapshotReference: "after-1", evidenceReferences: ["item-evidence"], ...overrides });
const started = source => { core.resetRegistry(); const made = core.createManualPostRegistrationAcceptance(source || target(), input(), op("作成")); assert(made.created, made.reasons); const result = core.startManualPostRegistrationAcceptance(made.record, op("開始")); assert(result.started); return result.record; };
core.resetRegistry(); assert(core.validatePostRegistrationAcceptanceEligibility(target()).valid);
for (const [status, result] of [["ready_for_manual_post_registration_conditional_acceptance", "conditionally_accepted"], ["ready_for_manual_post_registration_correction_planning", "correction_plan_required"], ["ready_for_manual_post_registration_rollback_planning", "rollback_plan_required"], ["post_registration_verification_decision_rejected", "rejected"], ["manual_post_registration_verification_decision_interrupted", "interrupted"], ["manual_post_registration_verification_decision_cancelled", "cancelled"], ["manual_post_registration_verification_decision_abnormality_detected", "abnormality_detected"]]) assert(!core.validatePostRegistrationAcceptanceEligibility(target({ decisionStatus: status, decisionResult: result })).valid);
assert(!core.createManualPostRegistrationAcceptance(target(), input({ acceptorName: "" }), op("作成")).created); assert(!core.createManualPostRegistrationAcceptance(target(), input({ acceptanceConfirmation: false }), op("作成")).created); assert(!core.createManualPostRegistrationAcceptance(target(), input({ automaticAcceptanceRequested: true }), op("作成")).created);
let record = started(); assert(!core.startManualPostRegistrationAcceptance(record, op("二重開始")).started); let added = core.recordPostRegistrationAcceptanceItemResult(record, item(), op("個別受入")); assert(added.recorded); assert(core.validatePostRegistrationAcceptanceConsistency(added.record).valid); assert(core.recordPostRegistrationAcceptanceProgress(added.record, op("進捗")).recorded); let completed = core.completeManualPostRegistrationAcceptance(added.record, op("完了")); assert(completed.completed); assert.strictEqual(completed.record.acceptanceResult, "accepted"); let finalization = core.transitionToPostRegistrationFinalization(completed.record, op("最終化待ちへ")); assert(finalization.transitioned); assert.strictEqual(finalization.record.acceptanceStatus, "ready_for_manual_post_registration_finalization"); assert(!core.startManualPostRegistrationAcceptance(completed.record, op("再開始")).started);
for (const bad of [{ recordFound: false }, { referenceMatched: false }, { evidenceVerified: false, evidenceReferences: [] }]) { record = started(); added = core.recordPostRegistrationAcceptanceItemResult(record, item(bad), op("異常個別")).record; assert(!core.completeManualPostRegistrationAcceptance(added, op("完了拒否")).completed); }
for (const badTarget of [{ countSummary: { ...target().countSummary, actualRegisteredCount: 2 } }, { verificationSummary: { ...target().verificationSummary, unverifiedItemCount: 1 } }, { verificationSummary: { ...target().verificationSummary, unresolvedObservationCount: 1 } }, { verificationSummary: { ...target().verificationSummary, correctionCandidateCount: 1 } }, { verificationSummary: { ...target().verificationSummary, rollbackCandidateCount: 1 } }, { verificationSummary: { ...target().verificationSummary, unresolvedAbnormalityCount: 1 } }]) assert(!core.validatePostRegistrationAcceptanceEligibility(target(badTarget)).valid);
record = started(); const rejection = core.rejectManualPostRegistrationAcceptance(record, { rejectionReason: "証跡再確認が必要", rejectionCategory: "evidence", affectedItemIds: ["target-1"], countImpactSummary: "1件", evidenceImpactSummary: "不足", unresolvedIssues: ["evidence"], recommendedHumanAction: "新規判定" }, op("拒否")); assert(rejection.rejected && rejection.record.rejectionRecord.newDecisionRequired); assert(!core.transitionToPostRegistrationFinalization(rejection.record, op("禁止遷移")).transitioned); record = started(); assert(!core.rejectManualPostRegistrationAcceptance(record, {}, op("拒否")).rejected);
record = started(); assert(core.interruptManualPostRegistrationAcceptance(record, "手動中断", op("中断")).recorded); record = started(); assert(core.cancelManualPostRegistrationAcceptance(record, "手動取消", op("取消")).recorded); record = started(); const abnormal = core.detectPostRegistrationAcceptanceAbnormality(record, ["件数矛盾"], op("異常")); assert(abnormal.detected); assert(!core.transitionToPostRegistrationFinalization(abnormal.record, op("禁止遷移")).transitioned); assert(!core.transition(record, "ready_for_manual_post_registration_finalization", op("飛越")).transitioned);
const safety = core.getManualPostRegistrationAcceptanceSafetyStatus(); assert(safety.privateLocalOnly && safety.planOnly && safety.protectedMode && safety.humanAcceptanceRequired); for (const key of Object.keys(safety).filter(key => key.startsWith("automatic") || key.endsWith("Enabled") || key === "externalTransmissionPerformed")) assert.strictEqual(safety[key], false, key);
const root = path.join(__dirname, ".."), html = fs.readFileSync(path.join(root, "private-local.html"), "utf8"), css = fs.readFileSync(path.join(root, "dashboard.css"), "utf8"), readme = fs.readFileSync(path.join(root, "README.md"), "utf8"), source = fs.readFileSync(path.join(root, "phase26-23-manual-post-registration-acceptance-core.js"), "utf8"); for (const marker of ["phase26-23-manual-post-registration-acceptance", "正式登録後受入状態", "Phase26-22判定結果", "検証結果", "件数整合性", "登録予定件数", "実登録件数", "作成レコード件数", "受入対象件数", "受入済み件数", "除外件数", "未確認件数", "未解決観察事項件数", "修正候補件数", "ロールバック候補件数", "未解決異常件数", "受入結果", "受入者", "受入日時", "人間確認必須", "自動受入禁止", "自動最終化禁止", "自動修正禁止", "自動ロールバック禁止", "protectedMode", "PLAN_ONLY", "次段階は手動正式登録後最終化"]) assert(html.includes(marker), marker); assert(css.includes(".phase2623-panel")); assert(readme.includes("Phase26-23 Manual Post-Registration Acceptance Core")); for (const pattern of [/fetch\s*\(/, /XMLHttpRequest/, /WebSocket\s*\(/, /automaticAcceptanceStartPerformed:\s*true/, /automaticFinalizationPerformed:\s*true/, /automaticCorrectionPerformed:\s*true/, /automaticRollbackPerformed:\s*true/]) assert(!pattern.test(source));
console.log("phase26ManualPostRegistrationAcceptanceCore.test.js: PASS");
