"use strict";
const assert=require("assert"),fs=require("fs"),vm=require("vm"),real=require("../phase30-12-phase30-post-start-stabilization-closure-decision-core.js"),p3011=real.PHASE3011_REFERENCE;
const NOW="2027-01-05T00:00:00Z",options={now:()=>new Date(NOW)},human={performedBy:"human",reason:"manual closure review",explicitConfirmation:true,performedAt:NOW};
const code=fs.readFileSync(require.resolve("../phase30-12-phase30-post-start-stabilization-closure-decision-core.js"),"utf8");
// Unit cases isolate the already tested Phase30-9 chain validator; integration below uses real dependencies.
const dependency={...p3011,validatePhase3010Eligibility:s=>({valid:!!(s&&s.chainValid),reasons:[]})};
const sandbox={module:{exports:{}},require:id=>{assert.strictEqual(id,"./phase30-11-phase30-post-start-stabilization-closure-review-core.js");return dependency}};vm.runInNewContext(code,sandbox);const core=sandbox.module.exports;
const sourceName="phase30PostStartStabilizationClosureReview",ownName="phase30PostStartStabilizationClosureDecision";
const copy=v=>JSON.parse(JSON.stringify(v));
function stamp(r,name=sourceName){const b={...r};delete b[name+"Snapshot"];delete b[name+"SnapshotHash"];return {...b,[name+"Snapshot"]:copy(b),[name+"SnapshotHash"]:core.computeSnapshotHash(b)}}
function fields(api,list){const r={};api[list].forEach(k=>r[k]=k);api.ARRAY_FIELDS.forEach(k=>r[k]=[]);api.REQUIRED_TRUE.forEach(k=>r[k]=true);return r}
function source(p={}){const b={...fields(p3011,"REVIEW_FIELDS"),...p3011.SAFETY,[sourceName+"Id"]:"followup-1",[sourceName+"Status"]:p3011.STATES[8],[sourceName+"Result"]:p3011.RESULTS[0],[sourceName+"Version"]:p3011.SCHEMA_VERSION,phase30Started:true,manualPhase30StartCompleted:true,reviewSummary:"complete",closureReviewAfterSnapshot:{ok:true},completedBy:"human",completedAt:NOW,recordVersion:1,auditTrail:[{...human,action:"manual_handoff",from:"",to:p3011.STATES[8]}],phase3010SourceSnapshot:{chainValid:true}};p3011.REFERENCE_IDS.concat(p3011.UPSTREAM_FIELDS).forEach(k=>b[k]=b.phase3010SourceSnapshot[k]=k+"-1");return stamp({...b,...p})}
const input=()=>fields(core,"DECISION_FIELDS"),src=source();
assert(core.validatePhase3011Eligibility(src).valid);assert.strictEqual(core.NEXT_STAGE,"manual_phase30_post_start_stabilization_closure_execution_preparation");assert.strictEqual(core.extractStabilizationClosureDecisionCandidates([src],[]).length,1);
for(const patch of [{[sourceName+"Status"]:"invalid"},{[sourceName+"Result"]:p3011.RESULTS[1]},{[sourceName+"Version"]:"bad"},{protectedMode:false},{planOnly:false},{privateLocalOnly:false},{automaticFollowupPerformed:true},{invalidatedAt:NOW},{expiredAt:NOW},{expiresAt:"2000-01-01"},{auditTrail:[{}]},{recordVersion:0},{recordVersion:2},{errors:["error"]},{errors:"bad"},{unresolvedIssues:["issue"]},{criticalIssues:["issue"]},{blockingConditions:["issue"]},{phase3010SourceSnapshot:{chainValid:false}},{phase30PostStartStabilizationDecisionId:"other"},{phase30PostStartStabilizationDecisionVersion:"other"},{stabilizationFollowupConfirmed:false}])assert.strictEqual(core.validatePhase3011Eligibility(source(patch)).valid,false,JSON.stringify(patch));
for(const patch of [{[sourceName+"SnapshotHash"]:"bad"},{reviewSummary:"tampered"},{[sourceName+"Snapshot"]:{bad:true}}])assert.strictEqual(core.validatePhase3011Eligibility({...src,...patch}).valid,false);
const created=core.createStabilizationClosureDecisionRecord(src,input(),human,options,[]);assert(created.created,created.reasons.join());const initial=created.record;assert(Object.isFrozen(initial));assert.strictEqual(core.createStabilizationClosureDecisionRecord(src,input(),human,options,[initial]).created,false);assert.strictEqual(core.extractStabilizationClosureDecisionCandidates([src],[initial]).length,0);
assert.strictEqual(core.submitStabilizationClosureDecisionReview(initial,human,options).transitioned,false);
const started=core.beginStabilizationClosureDecision(initial,human,options).record;assert.strictEqual(started[ownName+"Status"],core.STATES[1]);
for(const patch of [{phase3011SourceSnapshot:{}},{auditTrail:[]},{recordVersion:0},{protectedMode:false},{[ownName+"Status"]:core.STATES[3]},{phase30Started:false},{invalidatedAt:NOW},{phase30PostStartStabilizationClosureReviewId:"other"}]){assert.strictEqual(core.updateStabilizationClosureDecision(started,patch,human,options).updated,false);assert.strictEqual(core.createStabilizationClosureDecisionRecord(src,{...input(),...patch},human,options,[]).created,false)}
const updated=core.updateStabilizationClosureDecision(started,{closureDecisionNotes:"updated"},human,options);assert(updated.updated);const submitted=core.submitStabilizationClosureDecisionReview(updated.record,human,options).record;
const completion={result:core.RESULTS[0],decisionSummary:"ready",decisionAfterSnapshot:{ready:true},approvedBy:"reviewer",approvedAt:NOW};
for(const patch of [{decisionSummary:""},{approvedAt:"bad"},{closureReadinessConfirmed:false},{errors:["x"]},{unresolvedIssues:["x"]},{criticalIssues:["x"]},{blockingConditions:["x"]}])assert.strictEqual(core.decideStabilizationClosure(submitted,{...completion,...patch},human,options).decided,false);
const done=core.decideStabilizationClosure(submitted,completion,human,options);assert(done.decided);assert.strictEqual(done.record[ownName+"Status"],core.STATES[3]);
const hand=core.handoffToStabilizationClosureExecutionPreparation(done.record,human,options);assert(hand.handedOff);assert.strictEqual(hand.record[ownName+"Status"],core.STATES[8]);
for(const patch of [{errors:["late error"]},{closureReadinessConfirmed:false}])assert.strictEqual(core.handoffToStabilizationClosureExecutionPreparation(stamp({...done.record,...patch},ownName),human,options).handedOff,false);
const outcomes=[{conditions:"c",conditionReason:"r",conditionOwner:"o",conditionDeadline:NOW,conditionVerificationMethod:"manual",conditionReleaseCriteria:"reviewed"},{notReadyReason:"failed",notReadyImpact:"not safe",requiredActions:["manual review"]},{incompleteReason:"missing",missingItems:["evidence"]},{blockedReason:"blocked",blockedImpact:"cannot close",unblockingConditions:["manual review"]}];
outcomes.forEach((extra,i)=>{const result=core.RESULTS[i+1];assert.strictEqual(core.decideStabilizationClosure(submitted,{result},human,options).decided,false);const x=core.decideStabilizationClosure(submitted,{result,...extra},human,options);assert(x.decided,result);assert.strictEqual(core.handoffToStabilizationClosureExecutionPreparation(x.record,human,options).handedOff,false)});
for(const h of [{},{...human,performedBy:""},{...human,reason:""},{...human,performedAt:"bad"},{...human,explicitConfirmation:false}]){assert.strictEqual(core.createStabilizationClosureDecisionRecord(src,input(),h,options,[]).created,false);assert.strictEqual(core.beginStabilizationClosureDecision(initial,h,options).transitioned,false);assert.strictEqual(core.updateStabilizationClosureDecision(started,{closureDecisionNotes:"x"},h,options).updated,false);assert.strictEqual(core.submitStabilizationClosureDecisionReview(started,h,options).transitioned,false);assert.strictEqual(core.decideStabilizationClosure(submitted,completion,h,options).decided,false);assert.strictEqual(core.handoffToStabilizationClosureExecutionPreparation(done.record,h,options).handedOff,false);assert.strictEqual(core.invalidateStabilizationClosureDecision(done.record,h,options).transitioned,false)}
const invalid=core.invalidateStabilizationClosureDecision(done.record,human,options);assert(invalid.transitioned);assert.strictEqual(core.handoffToStabilizationClosureExecutionPreparation(invalid.record,human,options).handedOff,false);assert(core.createStabilizationClosureDecisionRecord(src,input(),human,options,[invalid.record]).created);
assert.strictEqual(core.beginStabilizationClosureDecision({...initial,closureDecisionNotes:"tampered"},human,options).transitioned,false);
for(const r of [initial,started,submitted,done.record,hand.record,invalid.record]){for(const [k,v] of Object.entries(core.SAFETY))assert.strictEqual(r[k],v,k);assert(core.integrityIntact(r));assert(core.safetyIntact(r))}
const mem={v:null,setItem(k,v){this.v=v},getItem(){return this.v}};assert(core.saveStabilizationClosureDecisionRecords(mem,[hand.record,invalid.record]).saved);assert(core.loadStabilizationClosureDecisionRecords(mem).loaded);mem.v=JSON.stringify({schemaVersion:core.SCHEMA_VERSION,records:[{}]});assert.strictEqual(core.loadStabilizationClosureDecisionRecords(mem).loaded,false);
const browser={HashimotoPhase3011PostStartStabilizationClosureReview:dependency};vm.runInNewContext(code,browser);assert(browser.HashimotoPhase3012PostStartStabilizationClosureDecision);assert.throws(()=>vm.runInNewContext(code,{}),/Phase30-11/);
assert(!/fetch\s*\(|XMLHttpRequest|WebSocket|EventSource|sendBeacon|child_process|execSync|spawnSync|setTimeout|setInterval|writeFile|mkdir|https?\.request/.test(code));
console.log("Phase30-12 unit cases: PASS");
const p3010=p3011.PHASE3010_REFERENCE;
function build(api){
 const version=api.SCHEMA_VERSION,terminal=version.startsWith("29."),ref=Object.keys(api).find(k=>/^PHASE\d+_REFERENCE$/.test(k));
 const up=terminal?null:build(api[ref]);
 const parentValidator=terminal?p3010.PHASE309_REFERENCE.PHASE308_REFERENCE.PHASE307_REFERENCE.PHASE306_REFERENCE.PHASE305_REFERENCE.PHASE304_REFERENCE.PHASE303_REFERENCE.PHASE302_REFERENCE.PHASE301_REFERENCE.validatePhase2919Eligibility:null;
 const files=fs.readdirSync(require("path").join(__dirname,"..")).filter(f=>f.startsWith("phase30-")&&f.endsWith("core.js"));
 let validator=parentValidator;
 if(!terminal){for(const file of files){const a=require("../"+file);const key="validatePhase"+version.split(".").slice(0,2).join("")+"Eligibility";if(a[key]){validator=a[key];break}}}
 const text=validator.toString(),status=text.match(/s\.([A-Za-z0-9]+Status)!=="([^"]+)"/),result=text.match(/s\.([A-Za-z0-9]+Result)!=="([^"]+)"/),name=status[1].slice(0,-6);
 const b={...api.SAFETY,[name+"Id"]:name+"-1",[status[1]]:status[2],[result[1]]:result[2],errors:[],unresolvedIssues:[],criticalIssues:[],blockingConditions:[],recordVersion:1,auditTrail:[{action:"manual",from:"",to:status[2],performedBy:"human",reason:"confirmed",performedAt:NOW}]};
 for(const k of api.REFERENCE_IDS.concat(api.UPSTREAM_FIELDS))b[k]=up?up[k]:k+"-1";
 if(up)b[ref.toLowerCase().replace("_reference","SourceSnapshot")]=up;
 if(!terminal&&Number(version.split(".")[1])>=4)b.phase30Started=b.manualPhase30StartCompleted=true;const snap={...b};if(name==="phase30Definition")delete snap.phase2919SourceSnapshot;
 return {...b,[name+"Snapshot"]:snap,[name+"SnapshotHash"]:api.computeSnapshotHash(snap),[name+"Version"]:version};
}

const realDecision=build(p3010.PHASE309_REFERENCE);
const f=fields(p3010,"FOLLOWUP_FIELDS");let followup=p3010.createStabilizationFollowupRecord(realDecision,f,human,options,[]);assert(followup.created,followup.reasons.join());followup=p3010.beginStabilizationFollowup(followup.record,human,options);followup=p3010.submitStabilizationFollowupReview(followup.record,human,options);followup=p3010.completeStabilizationFollowup(followup.record,{result:p3010.RESULTS[0],followupSummary:"complete",followupAfterSnapshot:{stable:true},completedBy:"human",completedAt:NOW},human,options);assert(followup.completed);followup=p3010.handoffToStabilizationClosureReview(followup.record,human,options);assert(followup.handedOff);

let review=p3011.createStabilizationClosureReviewRecord(followup.record,fields(p3011,"REVIEW_FIELDS"),human,options,[]);assert(review.created,review.reasons.join());review=p3011.beginStabilizationClosureReview(review.record,human,options);review=p3011.submitStabilizationClosureReview(review.record,human,options);review=p3011.completeStabilizationClosureReview(review.record,{result:p3011.RESULTS[0],reviewSummary:"ready",closureReviewAfterSnapshot:{ready:true},completedBy:"human",completedAt:NOW},human,options);assert(review.completed);review=p3011.handoffToStabilizationClosureDecision(review.record,human,options);assert(review.handedOff);
assert(real.validatePhase3011Eligibility(review.record).valid);
const broken=copy(review.record);broken.phase3010SourceSnapshot.phase309SourceSnapshot=null;assert.strictEqual(real.validatePhase3011Eligibility(stamp(broken)).valid,false);
console.log("phase30PostStartStabilizationClosureDecisionCore.test.js: PASS (including real Phase30-11 source chain)");
