"use strict";
const assert=require("assert"),fs=require("fs"),vm=require("vm"),core=require("../phase28-2-phase27-completion-acceptance-core.js"),p281=core.PHASE281_REFERENCE,p27=p281.PHASE2726_REFERENCE,NOW="2027-01-01T00:00:00Z",options={now:()=>new Date(NOW)},human={performedBy:"human",reason:"manual",explicitConfirmation:true,performedAt:NOW};
function source(p={}){const base={phase27FinalClosureId:"phase27-final-closure-1",phase27FinalClosureStatus:"phase27_final_closure_confirmed",phase27FinalClosureResult:"confirm_phase27_final_closure",expiresAt:"2027-12-01T00:00:00Z",recordVersion:3,auditTrail:[{action:"result_decision"}],stableStateConfirmed:true,workingTreeSafe:true,mainOriginMainMatch:true,requiredTestsPassed:true,requiredModulesConfirmed:true,requiredUiConfirmed:true,requiredConfigConfirmed:true,correctionRequired:false,rollbackRequired:false,recoveryRequired:false,nextPhaseAutomaticallyStarted:false,...p27.SAFETY};p27.REFERENCE_IDS.forEach(k=>base[k]=`${k}-1`);p27.ZERO_COUNTS.forEach(k=>base[k]=0);const snapshot={...base};return{...base,phase27FinalClosureSnapshot:snapshot,phase27FinalClosureSnapshotHash:p27.computeSnapshotHash(snapshot),phase27FinalClosureVersion:p27.SCHEMA_VERSION,...p}}
function input(p={}){return{acceptedBy:"acceptor",responsiblePerson:"owner",confirmedBy:"confirmer",acceptanceReason:"complete",rollbackPoint:"before",recoveryPoint:"snapshot",gitEvidence:{safe:true},testEvidence:{pass:true},stateEvidence:{stable:true},safetyEvidence:{intact:true},expiresAt:"2027-11-01T00:00:00Z",...p}}
function create(){const x=core.createPhase27CompletionAcceptanceRecord(source(),input(),human,options,[],p281.SAFETY_BOUNDARY);assert(x.created,x.reasons.join());return x.record}
function progress(){let r=create();r=core.startPhase27CompletionAcceptance(r,human,options).record;return core.progressPhase27CompletionAcceptance(r,human,options).record}
function accept(p={}){return{result:"accept_phase27_completion_for_phase28",acceptanceSummary:"accepted",acceptanceTarget:"Phase27",acceptanceScope:"completion",phase27CompletionEvidence:{ok:true},phase27FinalClosureEvidence:{ok:true},moduleEvidence:{ok:true},uiEvidence:{ok:true},configEvidence:{ok:true},auditEvidence:{ok:true},integrityEvidence:{ok:true},rollbackEvidence:{ok:true},recoveryEvidence:{ok:true},acceptanceAfterSnapshot:{accepted:true},phase27FinalClosureSourceSnapshot:{source:true},phase281DefinitionSnapshot:p281.definition(),correctionRequired:false,rollbackRequired:false,recoveryRequired:false,criticalIssues:[],blockingConditions:[],...p}}
assert(core.PHASE281_REFERENCE);assert.strictEqual(core.CURRENT_STAGE,"phase27_completion_acceptance");assert(p281.PHASE28_STAGES.includes(core.CURRENT_STAGE));assert.strictEqual(core.extractPhase27CompletionAcceptanceCandidates([source()],[],p281.SAFETY_BOUNDARY).length,1);
for(const p of [{phase27FinalClosureStatus:"bad"},{phase27FinalClosureResult:"bad"},{invalidatedAt:NOW},{expiredAt:NOW},{phase27FinalClosureSnapshot:null},{phase27FinalClosureSnapshotHash:"bad"},{phase27FinalClosureVersion:"bad"},{auditTrail:[]},{recordVersion:0},{protectedMode:false},{stableStateConfirmed:false},{workingTreeSafe:false},{mainOriginMainMatch:false},{requiredTestsPassed:false},{requiredModulesConfirmed:false},{requiredUiConfirmed:false},{requiredConfigConfirmed:false},{correctionRequired:true},{rollbackRequired:true},{recoveryRequired:true},{nextPhaseAutomaticallyStarted:true}])assert.strictEqual(core.validatePhase27CompletionEligibility(source(p),p281.SAFETY_BOUNDARY).valid,false,JSON.stringify(p));
for(const k of p281.REQUIRED_TRUE)assert.strictEqual(core.validatePhase281Safety({[k]:false},source()).valid,false,k);for(const k of p281.REQUIRED_FALSE)assert.strictEqual(core.validatePhase281Safety({[k]:true},source()).valid,false,k);
assert.strictEqual(core.createPhase27CompletionAcceptanceRecord(source(),input(),{},options,[],p281.SAFETY_BOUNDARY).created,false);const original=source(),text=JSON.stringify(original);assert(core.createPhase27CompletionAcceptanceRecord(original,input(),human,options,[],p281.SAFETY_BOUNDARY).created);assert.strictEqual(JSON.stringify(original),text);
const first=create();assert.strictEqual(core.extractPhase27CompletionAcceptanceCandidates([source()],[first],p281.SAFETY_BOUNDARY).length,0);assert.strictEqual(core.createPhase27CompletionAcceptanceRecord(source(),input(),human,options,[first],p281.SAFETY_BOUNDARY).created,false);
let r=core.startPhase27CompletionAcceptance(first,human,options).record;r=core.progressPhase27CompletionAcceptance(r,human,options).record;assert(core.pausePhase27CompletionAcceptance(r,human,options).transitioned);assert(core.resumePhase27CompletionAcceptance(core.pausePhase27CompletionAcceptance(r,human,options).record,human,options).transitioned);assert(core.stopPhase27CompletionAcceptance(r,human,options).transitioned);assert(core.cancelPhase27CompletionAcceptance(r,human,options).transitioned);assert(core.failPhase27CompletionAcceptance(r,human,options).transitioned);assert.strictEqual(core.updatePhase27CompletionAcceptance(first,{},human,options).updated,false);assert(core.updatePhase27CompletionAcceptance(r,{acceptanceReason:"updated"},human,options).updated);
for(const k of ["rollbackPoint","recoveryPoint","gitEvidence","testEvidence","stateEvidence","moduleEvidence","uiEvidence","configEvidence","safetyEvidence","auditEvidence","integrityEvidence","phase27CompletionEvidence","phase27FinalClosureEvidence","acceptanceAfterSnapshot","phase27FinalClosureSourceSnapshot","phase281DefinitionSnapshot"]){assert.strictEqual(core.completePhase27CompletionAcceptance(progress(),accept({[k]:null}),human,options).completed,false,k)}
for(const p of [{criticalIssues:["critical"]},{blockingConditions:["blocked"]},{correctionRequired:true},{rollbackRequired:true},{recoveryRequired:true}])assert.strictEqual(core.completePhase27CompletionAcceptance(progress(),accept(p),human,options).completed,false,JSON.stringify(p));
const ok=core.completePhase27CompletionAcceptance(r,accept(),human,options);assert(ok.completed);assert.strictEqual(ok.record.phase28Phase27CompletionAcceptanceStatus,"phase27_completion_accepted_for_phase28");
const routes=[["conditionally_accept_phase27_completion_for_phase28",{conditions:"c",conditionReason:"r",conditionOwner:"o",conditionDeadline:"2027-03-01",conditionVerificationMethod:"m",conditionReleaseCriteria:"c"}],...["reject_phase27_completion_for_phase28","phase27_completion_acceptance_incomplete","return_for_phase27_final_closure_review","correction_plan_required","rollback_plan_required","recovery_plan_required","additional_evidence_required","additional_review_required","manual_investigation_required","hold","blocked"].map(x=>[x,{}])];for(const[result,p]of routes)assert(core.completePhase27CompletionAcceptance(progress(),{result,...p},human,options).completed,result);
assert.strictEqual(core.advanceToExternalDataCategoryDefinition(ok.record,{},options).advanced,false);const handoff=core.advanceToExternalDataCategoryDefinition(ok.record,human,options);assert(handoff.advanced);assert.strictEqual(handoff.record.phase28Phase27CompletionAcceptanceStatus,"ready_for_manual_phase28_external_data_category_definition");assert.strictEqual(handoff.record.externalDataAcquired,false);assert.strictEqual(handoff.record.networkCommunicationPerformed,false);assert.strictEqual(handoff.record.phase28AutomaticallyAdvanced,false);
assert(core.integrityIntact(first));assert.strictEqual(core.integrityIntact({...first,phase28Phase27CompletionAcceptanceSnapshot:{tampered:true}}),false);Object.entries(core.SAFETY).forEach(([k,v])=>assert.strictEqual(first[k],v,k));assert(core.invalidatePhase27CompletionAcceptance(ok.record,human,options).transitioned);assert.strictEqual(core.expirePhase27CompletionAcceptance({...first,expiresAt:"2026-01-01"},{},options).expired,false);assert(core.expirePhase27CompletionAcceptance({...first,expiresAt:"2026-01-01"},human,options).expired);
const mem={v:null,setItem(_k,v){this.v=v},getItem(){return this.v}};assert(core.savePhase27CompletionAcceptanceRecords(mem,[ok.record]).saved);assert(core.loadPhase27CompletionAcceptanceRecords(mem).loaded);mem.v="{";assert.strictEqual(core.loadPhase27CompletionAcceptanceRecords(mem).loaded,false);
const code=fs.readFileSync(require.resolve("../phase28-2-phase27-completion-acceptance-core.js"),"utf8"),browser={HashimotoPhase281PurposeScopeSafetyBoundary:p281};vm.runInNewContext(code,browser);assert(browser.HashimotoPhase282Phase27CompletionAcceptance);assert(code.includes('require("./phase28-1-purpose-scope-safety-boundary-definition.js")'));assert.throws(()=>vm.runInNewContext(code,{}),/Phase28-1/);assert(!/fetch\s*\(|XMLHttpRequest|WebSocket|EventSource|sendBeacon\s*\(|http\.request|https\.request|child_process|execSync|spawnSync|setInterval\s*\(/.test(code));console.log("phase28Phase27CompletionAcceptanceCore.test.js: PASS");
