const assert=require("assert"),fs=require("fs"),path=require("path"),core=require("../phase23-audit-follow-up-manual-resolution-verification-decision-core.js");
const root=path.join(__dirname,".."),read=f=>fs.readFileSync(path.join(root,f),"utf8");
function plan(){return{resolutionPlanId:"rp-1",auditRecordId:"audit-1",followUpId:"fu-1",status:"plan_approved",plannedActions:[{actionId:"a1",sequence:1,required:true,prerequisiteActionIds:[]},{actionId:"a2",sequence:2,required:true,prerequisiteActionIds:["a1"]}]}}
function execution(status="awaiting_manual_verification",severity="error"){return{executionRecordId:"exec-1",version:4,resolutionPlanId:"rp-1",auditRecordId:"audit-1",followUpId:"fu-1",sourceSeverity:severity,status,actions:[{actionId:"a1",sequence:1,required:true,prerequisiteActionIds:[],status:"completed",history:[{resultSummary:"done"}]},{actionId:"a2",sequence:2,required:true,prerequisiteActionIds:["a1"],status:"completed",history:[{resultSummary:"done"}]}],evidence:[{evidenceId:"ev-1",evidenceType:"summary",summary:"metadata",checksum:"sha256-x",localReference:"local/ref"}],unresolvedIssues:[],residualRisks:["low"],resultSummary:"done"}}
function memory(initial={},fail=false){const data={...initial};return{data,getItem:k=>Object.prototype.hasOwnProperty.call(data,k)?data[k]:null,setItem(k,v){if(fail)throw Error("quota");data[k]=String(v)},removeItem(){throw Error("physical deletion forbidden")}}}
for(const s of core.ELIGIBLE_EXECUTION_STATUSES)assert.strictEqual(core.eligibleExecutions({records:[execution(s)]}).length,1);
for(const s of["awaiting_manual_execution","execution_in_progress","execution_paused","cancelled","expired"])assert.strictEqual(core.eligibleExecutions({records:[execution(s)]}).length,0);
assert.ok(core.referenceProblems(execution("execution_in_progress"),plan()).includes("execution_not_eligible"));assert.ok(core.referenceProblems({...execution(),terminalLocked:true},plan()).includes("execution_terminal_locked"));assert.ok(core.referenceProblems({...execution(),auditRecordId:"other"},plan()).includes("audit_record_id_mismatch"));assert.ok(core.referenceProblems({...execution(),actions:[execution().actions[1],execution().actions[0]]},plan()).length===0);
let made=core.createVerificationRecord(execution(),plan(),{createdBy:"Verifier"},new Date("2026-07-24T00:00:00Z"));assert.ok(made.created);let r=made.record;assert.deepStrictEqual(r.sourceExecution.actions.map(a=>a.actionId),["a1","a2"]);
let x=core.startVerification(r,{verifier:"Verifier",verifiedAt:"2026-07-24T00:01:00Z",reason:"manual review"},new Date("2026-07-24T01:00:00Z"));assert.ok(x.started);r=x.record;
x=core.pauseVerification(r,{verifier:"Verifier",reason:"wait"});assert.ok(x.paused);r=x.record;x=core.resumeVerification(r,{verifier:"Verifier",reason:"resume"});assert.ok(x.resumed);r=x.record;
x=core.recordCheck(r,{checkId:"c1",checkType:"evidence",result:"confirmed",summary:"checked",evidenceIds:["ev-1"],checkedBy:"Verifier",checkedAt:"2026-07-24T00:02:00Z",rawPayload:{secret:"x"},password:"x"});assert.ok(x.recorded);assert.ok(!JSON.stringify(x.check).includes("password"));r=x.record;
const base={verifier:"Verifier",verifiedAt:"2026-07-24T00:03:00Z",reason:"reviewed",evidenceReviewResult:"confirmed",unresolvedIssues:[],residualRisks:["low"],safetyConfirmed:true};
assert.ok(core.recordDecision({...r,sourceExecution:{...r.sourceExecution,actions:r.sourceExecution.actions.map((a,i)=>i?{...a,status:"blocked"}:a)}},"verification_passed",base,new Date("2026-07-24T01:00:00Z")).problems.includes("required_actions_incomplete"));
assert.ok(core.recordDecision(r,"verification_passed",{...base,unresolvedIssues:[{severity:"error",summary:"left"}]},new Date("2026-07-24T01:00:00Z")).problems.includes("fatal_or_error_unresolved"));
assert.ok(core.recordDecision(r,"verification_passed",{...base,residualRisks:["critical"]},new Date("2026-07-24T01:00:00Z")).problems.includes("high_risk_human_confirmation_required"));
let passed=core.recordDecision(r,"verification_passed",base,new Date("2026-07-24T01:00:00Z"));assert.ok(passed.recorded);assert.ok(!core.closeVerification({...passed.record,decision:{...passed.record.decision,unresolvedIssues:[{severity:"error"}]}},{verifier:"Verifier",reason:"close",closedAt:"2026-07-24"}).closed);let closed=core.closeVerification(passed.record,{verifier:"Verifier",reason:"confirmed",closedAt:"2026-07-24"});assert.ok(closed.closed);assert.strictEqual(core.cancelVerification(closed.record,{verifier:"V",reason:"x"}).reason,"terminal_locked");
let cond=core.recordDecision(r,"verification_passed_with_conditions",{...base,conditions:"monitor",conditionDueAt:"2026-08-01",conditionOwner:"Owner",recheckMethod:"manual review"},new Date("2026-07-24T01:00:00Z"));assert.ok(cond.recorded);assert.strictEqual(core.closeVerification(cond.record,{verifier:"V",reason:"x",closedAt:"2026-07-24"}).reason,"passing_decision_required");cond=core.confirmConditions(cond.record,{verifier:"V",confirmedAt:"2026-07-25",result:"met"});assert.ok(cond.confirmed);assert.ok(core.closeVerification(cond.record,{verifier:"V",reason:"met",closedAt:"2026-07-25"}).closed);
assert.ok(core.recordDecision(r,"rework_required",{...base,targetActionIds:["missing"],reworkReason:"x",requiredRework:"redo",reworkOwner:"O",reworkDueAt:"2026-08-01"}).problems.includes("valid_target_actions_required"));
assert.ok(core.recordDecision(r,"rework_required",{...base,targetActionIds:["a2"],reworkReason:"x",requiredRework:"redo",reworkOwner:"O",reworkDueAt:"2026-08-01"}).recorded);
assert.ok(core.recordDecision(r,"plan_revision_required",{...base,planRevisionScope:"action dependency"}).recorded);assert.ok(core.recordDecision(r,"manual_investigation_required",{...base,investigationTarget:"evidence",investigationReason:"unclear",requiredEvidence:"new summary",investigationOwner:"O"}).recorded);let rb=core.recordDecision(r,"rollback_review_required",{...base,nextManualAction:"human rollback assessment"});assert.ok(rb.recorded);assert.strictEqual(rb.record.decision.rollbackExecuted,false);
assert.ok(core.recordDecision(r,"verification_failed",{...base,failureReason:"failed",impactScope:"audit",unresolvedIssues:[{severity:"error",summary:"left"}],nextManualDecision:"investigate"}).recorded);assert.ok(core.recordDecision(r,"verification_rejected",{...base,rejectionReason:"invalid",rejectionConfirmedBy:"Reviewer",rejectedAt:"2026-07-24"}).recorded);
const originals={formal:"same",snapshot:"same",pending:"same",p236:"same",p237:"same",p238:"same",p239:"same",phase22:"same"},mem=memory(originals);let saved=core.addRecord(core.defaultStore(),made.record,mem);assert.ok(saved.saved);for(const[k,v]of Object.entries(originals))assert.strictEqual(mem.data[k],v);assert.strictEqual(core.addRecord(saved.store,{...made.record,verificationRecordId:"other"},mem).reason,"active_verification_exists");
const old=mem.data[core.STORAGE_KEY],fail=memory({[core.STORAGE_KEY]:old},true);assert.strictEqual(core.saveStore({records:[closed.record]},fail).saved,false);assert.strictEqual(fail.data[core.STORAGE_KEY],old);assert.strictEqual(core.replaceRecord({records:[closed.record]},{...closed.record,closedBy:"other"},mem).reason,"terminal_locked");
const index=read("index.html"),local=read("private-local.html"),code=read("phase23-audit-follow-up-manual-resolution-verification-decision-core.js")+read("phase23-10-main-dashboard-integration.js");assert.ok(index.includes('id="phase23-audit-follow-up-manual-resolution-verification-decision"'));assert.ok(local.includes('href="index.html#phase23-audit-follow-up-manual-resolution-verification-decision"'));assert.ok(index.indexOf('id="phase23-audit-follow-up-manual-resolution-execution"')<index.indexOf('id="phase23-audit-follow-up-manual-resolution-verification-decision"'));assert.ok(index.indexOf("phase23-9-main-dashboard-integration.js")<index.indexOf("phase23-audit-follow-up-manual-resolution-verification-decision-core.js"));
for(const pattern of[/\bfetch\s*\(/,/XMLHttpRequest/,/\bWebSocket\s*\(/,/\bEventSource\s*\(/,/sendBeacon/,/setInterval\s*\(/,/addEventListener\s*\(\s*["']storage/,/\.removeItem\s*\(/])assert.ok(!pattern.test(code));for(const file of["index.html","private-local.html","phase22-22-private-local.html"]){const html=read(file),ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.strictEqual(ids.length,new Set(ids).size,file);for(const m of html.matchAll(/<script[^>]+src="([^"]+)"/g))if(!/^(?:https?:)?\/\//.test(m[1]))assert.ok(fs.existsSync(path.join(root,m[1])),m[1])}
console.log("Phase23-10 manual resolution verification decision core tests passed");
