"use strict";
const assert=require("assert"),fs=require("fs"),vm=require("vm"),p308=require("../phase30-8-phase30-post-start-stabilization-review-core.js"),code=fs.readFileSync(require.resolve("../phase30-9-phase30-post-start-stabilization-decision-core.js"),"utf8"),dependency={...p308,validatePhase307Eligibility:s=>({valid:!!(s&&s.chainValid===true),reasons:[]})},sandbox={module:{exports:{}},exports:{},require:id=>{assert.strictEqual(id,"./phase30-8-phase30-post-start-stabilization-review-core.js");return dependency}};
vm.runInNewContext(code,sandbox);const core=sandbox.module.exports,NOW="2027-01-01T00:00:00Z",options={now:()=>new Date(NOW)},human={performedBy:"human",reason:"manual decision",explicitConfirmation:true,performedAt:NOW};
function source(p={}){const b={phase30PostStartStabilizationReviewId:"verification-1",phase30PostStartStabilizationReviewStatus:"ready_for_manual_phase30_post_start_stabilization_decision",phase30PostStartStabilizationReviewResult:"phase30_post_start_stabilization_stable",phase307SourceSnapshot:{chainValid:true},phase30Started:true,manualPhase30StartCompleted:true,unresolvedIssues:[],criticalIssues:[],blockingConditions:[],recordVersion:5,auditTrail:[{}],...p308.SAFETY};core.REFERENCE_IDS.forEach(k=>b[k]=b[k]||`${k}-1`);core.UPSTREAM_FIELDS.forEach(k=>b[k]=b[k]||`${k}-1`);const s={...b};return{...b,phase30PostStartStabilizationReviewSnapshot:s,phase30PostStartStabilizationReviewSnapshotHash:p308.computeSnapshotHash(s),phase30PostStartStabilizationReviewVersion:p308.SCHEMA_VERSION,...p}}
function input(p={}){const r={};core.DECISION_FIELDS.forEach(k=>r[k]=k.endsWith("Evidence")?{confirmed:true}:k);core.ARRAY_FIELDS.forEach(k=>r[k]=[]);core.REQUIRED_TRUE.forEach(k=>r[k]=true);return{...r,...p}}
function create(){const x=core.createStabilizationDecisionRecord(source(),input(),human,options,[]);assert(x.created,x.reasons.join());return x.record}function review(){let r=create();r=core.beginStabilizationDecision(r,human,options).record;return core.submitStabilizationDecisionReview(r,human,options).record}
assert.strictEqual(core.PHASE308_REFERENCE,dependency);assert.strictEqual(core.NEXT_STAGE,"manual_phase30_post_start_stabilization_followup");assert(core.STATES.includes("ready_for_manual_phase30_post_start_stabilization_followup"));assert(core.RESULTS.includes("approve_phase30_post_start_stabilization_stable"));const eligibility=core.validatePhase308Eligibility(source());assert(eligibility.valid,eligibility.reasons.join());assert.strictEqual(core.extractStabilizationDecisionCandidates([source()],[]).length,1);
for(const p of [{phase30PostStartStabilizationReviewStatus:"phase30_post_start_stabilization_unstable"},{phase30PostStartStabilizationReviewResult:"phase30_post_start_stabilization_unstable"},{phase30PostStartStabilizationReviewSnapshotHash:"bad"},{phase30PostStartStabilizationReviewVersion:"bad"},{privateLocalOnly:false},{planOnly:false},{protectedMode:false},{invalidatedAt:NOW},{expiredAt:NOW},{auditTrail:[]},{recordVersion:0},{phase307SourceSnapshot:{chainValid:false}},{phase30PostStartStabilizationReviewId:""},{unresolvedIssues:["x"]},{criticalIssues:["x"]},{blockingConditions:["x"]},{phase30AutomaticallyStarted:true},{nextPhaseAutomaticallyStarted:true},{phase30PostStartVerificationDecisionAutomaticallyExecuted:true}])assert.strictEqual(core.validatePhase308Eligibility(source(p)).valid,false,JSON.stringify(p));
assert.strictEqual(core.createStabilizationDecisionRecord(source(),input(),{},options,[]).created,false);assert.strictEqual(core.createStabilizationDecisionRecord(source(),input(),{...human,explicitConfirmation:false},options,[]).created,false);for(const p of [{decisionTarget:""},{decisionOperator:""},{runtimeStateConfirmation:null},{privateLocalOnly:false},{planOnly:false},{protectedMode:false},{unresolvedIssues:"bad"}])assert.strictEqual(core.createStabilizationDecisionRecord(source(),input(p),human,options,[]).created,false,JSON.stringify(p));
const src=source(),first=core.createStabilizationDecisionRecord(src,input(),human,options,[]);assert(first.created);assert(Object.isFrozen(core));assert(Object.isFrozen(first.record));assert.strictEqual(core.createStabilizationDecisionRecord(src,input(),human,options,[first.record]).created,false);assert.strictEqual(core.extractStabilizationDecisionCandidates([src],[first.record]).length,0);assert.strictEqual(core.submitStabilizationDecisionReview(first.record,human,options).transitioned,false);
let r=core.beginStabilizationDecision(first.record,human,options).record;assert.strictEqual(r.phase30PostStartStabilizationDecisionStatus,"manual_phase30_post_start_stabilization_decision_in_progress");for(const p of [{phase30Started:false},{phase308SourceSnapshot:{}},{privateLocalOnly:false},{auditTrail:[]}])assert.strictEqual(core.updateStabilizationDecision(r,p,human,options).updated,false,JSON.stringify(p));const updated=core.updateStabilizationDecision(r,{stabilizationDecisionNotes:"updated"},human,options);assert(updated.updated);r=core.submitStabilizationDecisionReview(updated.record,human,options).record;assert.strictEqual(r.phase30PostStartStabilizationDecisionStatus,"awaiting_manual_phase30_post_start_stabilization_decision_review");
const approve={result:"approve_phase30_post_start_stabilization_stable",decisionSummary:"approved manually",decisionAfterSnapshot:{state:"after"},approvedBy:"reviewer",approvedAt:NOW};for(const p of [{decisionSummary:""},{approvedAt:"bad"},{approvedBy:""},{decisionAfterSnapshot:null},{unresolvedIssues:["x"]},{criticalIssues:["x"]},{blockingConditions:["x"]},{protectedMode:false}])assert.strictEqual(core.decideStabilization(r,{...approve,...p},human,options).decided,false,JSON.stringify(p));const ok=core.decideStabilization(r,approve,human,options);assert(ok.decided,ok.reasons.join());assert.strictEqual(ok.record.phase30PostStartStabilizationDecisionStatus,"phase30_post_start_stabilization_stable_approved");const hand=core.handoffToStabilizationFollowup(ok.record,human,options);assert(hand.handedOff);assert.strictEqual(hand.record.phase30PostStartStabilizationDecisionStatus,"ready_for_manual_phase30_post_start_stabilization_followup");assert.strictEqual(ok.record.phase30PostStartStabilizationDecisionResult,"approve_phase30_post_start_stabilization_stable");assert.strictEqual(ok.record.phase30Started,true);assert.strictEqual(ok.record.manualPhase30StartCompleted,true);
assert.strictEqual(core.decideStabilization(review(),{result:"conditionally_approve_phase30_post_start_stabilization"},human,options).decided,false);assert(core.decideStabilization(review(),{result:"conditionally_approve_phase30_post_start_stabilization",conditions:"c",conditionReason:"r",conditionOwner:"o",conditionDeadline:"2027-02-01",conditionVerificationMethod:"manual",conditionReleaseCriteria:"verified"},human,options).decided);assert.strictEqual(core.decideStabilization(review(),{result:"decide_phase30_post_start_stabilization_unstable"},human,options).decided,false);assert(core.decideStabilization(review(),{result:"decide_phase30_post_start_stabilization_unstable",unstableReason:"unstable",unstableImpact:"impact",requiredActions:["review"]},human,options).decided);for(const result of ["phase30_post_start_stabilization_decision_incomplete","phase30_post_start_stabilization_decision_blocked"])assert(core.decideStabilization(review(),{result},human,options).decided,result);
for(const [k,v] of Object.entries(core.SAFETY))assert.strictEqual(ok.record[k],v,k);assert(core.integrityIntact(ok.record));assert(core.safetyIntact(ok.record));assert.strictEqual(core.integrityIntact({...ok.record,phase30PostStartStabilizationDecisionSnapshotHash:"bad"}),false);assert.strictEqual(core.safetyIntact({...ok.record,networkCommunicationPerformed:true}),false);assert(core.invalidateStabilizationDecision(ok.record,human,options).transitioned);
const mem={v:null,setItem(_k,v){this.v=v},getItem(){return this.v}};assert(core.saveStabilizationDecisionRecords(mem,[ok.record]).saved);assert(core.loadStabilizationDecisionRecords(mem).loaded);mem.v=JSON.stringify({schemaVersion:"bad",records:[ok.record]});assert.strictEqual(core.loadStabilizationDecisionRecords(mem).loaded,false);mem.v=JSON.stringify({schemaVersion:core.SCHEMA_VERSION,records:[{}]});assert.strictEqual(core.loadStabilizationDecisionRecords(mem).loaded,false);
for(const k of ["automaticallyDecide","automaticallyCorrect","automaticallyRollback","automaticallyRecover","startPhase30","startNextPhase"])assert.strictEqual(core[k],undefined,k);const browser={HashimotoPhase308PostStartStabilizationReview:dependency};vm.runInNewContext(code,browser);assert(browser.HashimotoPhase309PostStartStabilizationDecision);assert(code.includes('require("./phase30-8-phase30-post-start-stabilization-review-core.js")'));assert.throws(()=>vm.runInNewContext(code,{}),/Phase30-8/);assert(!/fetch\s*\(|XMLHttpRequest|WebSocket|EventSource|sendBeacon\s*\(|http\.request|https\.request|child_process|execSync|spawnSync|setInterval\s*\(|setTimeout\s*\(|(?:new\s+)?(?:Shared)?Worker\s*\(|fs\.writeFile|fs\.mkdir|mkdirSync|writeFileSync|Authorization\s*:|Bearer\s+/.test(code));console.log("phase30PostStartStabilizationDecisionCore.test.js: PASS");




