"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),core=require("../phase26-33-manual-post-registration-post-correction-acceptance-management-core.js");
const clock={now:()=>new Date("2026-08-04T06:00:00Z")},op=reason=>({performedBy:"human-manager",reason,explicitConfirmation:true});
const safety={protectedMode:true,planOnly:true,privateLocalOnly:true,automaticCorrectionAllowed:false,automaticExecutionAllowed:false,automaticVerificationAllowed:false,automaticDecisionAllowed:false,automaticApprovalAllowed:false,automaticAcceptanceAllowed:false,automaticConditionCompletionAllowed:false,automaticManagementCompletionAllowed:false,automaticApplicationAllowed:false,automaticLearningAllowed:false,publicReleaseAllowed:false,externalTransmissionAllowed:false,registeredDataMutated:false,appliedToPrediction:false,appliedToLearning:false,sentExternally:false};
const normal=(o={})=>({postCorrectionAcceptanceId:"acceptance-32",postCorrectionVerificationDecisionId:"decision-31",postCorrectionVerificationId:"verification-30",correctionExecutionId:"execution-29",correctionExecutionApprovalId:"approval-28",correctionPlanApprovalId:"approval-27",correctionPlanId:"plan-26",correctionRequestId:"request-25",correctionImpactReviewId:"impact-24",correctionTargetIdentificationId:"target-23",registrationRecordId:"registration-1",previousAcceptanceRecordId:"acceptance-old",importRecordId:"import-1",sourceRecordId:"source-1",raceId:"race-1",targetRecordType:"race_result",targetRecordKey:"race-1",acceptanceStatus:"ready_for_manual_post_correction_acceptance_management",acceptanceResult:"accept",accepted:true,conditionallyAccepted:false,rejected:false,returnedForReverification:false,returnedForCorrection:false,returnedForRedecision:false,rollbackRequired:false,abnormalityDetected:false,criticalIssueDetected:false,unresolvedIssueCount:0,warningDetected:false,auditTrail:[{event:"accepted",performedBy:"Acceptor",performedAt:"2026-08-04T05:00:00Z"}],...safety,...o});
const conditional=(o={})=>normal({acceptanceResult:"conditionally_accept",accepted:false,conditionallyAccepted:true,acceptanceConditions:["archive evidence"],outstandingItems:[{outstandingItemId:"out-1",title:"archive evidence",status:"pending",owner:"Owner",deadline:"2026-08-10T00:00:00Z"}],followUpRequired:true,nextAction:"track conditions",nextActionReason:"conditional acceptance",conditionConfirmationDueAt:"2026-08-10T00:00:00Z",conditionOwner:"Owner",...o});
const context=(id="acceptance-32",o={})=>({postCorrectionAcceptanceId:id,phase2631DecisionValid:true,phase2630VerificationValid:true,phase2629ExecutionValid:true,registrationRecordId:"registration-1",targetRecordKey:"race-1",acceptanceSnapshotHash:"acceptance-hash",acceptanceVersion:"5",...o});
const input=(o={})=>({recordedBy:"recorder",managementEnvironment:"Private Local",managementDevice:"local-pc",managementLocation:"local",managementMethod:"manual monitoring",managementReference:"management-sheet",acceptanceSnapshot:{acceptanceResult:"accept"},decisionSnapshot:{decisionResult:"approve_for_manual_post_correction_acceptance"},verificationSnapshot:{verificationResult:"verified"},executionSnapshot:{executionResult:"completed"},registrationSnapshot:{registrationRecordId:"registration-1"},currentTargetSnapshot:{finishTime:"1:34.8"},acceptanceSnapshotHash:"acceptance-hash",decisionSnapshotHash:"decision-hash",verificationSnapshotHash:"verification-hash",executionSnapshotHash:"execution-hash",registrationSnapshotHash:"registration-hash",currentTargetHash:"current-hash",acceptanceVersion:"5",decisionVersion:"4",verificationVersion:"3",executionVersion:"2",registrationVersion:"1",currentTargetVersion:"v2",...o});
const conditionItem={conditionItemId:"condition-1",conditionTitle:"Archive evidence",conditionDescription:"Store evidence",conditionOwner:"Owner",conditionReviewer:"Reviewer",conditionDeadline:"2026-08-10T00:00:00Z",conditionPriority:"high",conditionSeverity:"medium",requiredEvidence:["archive"]};
function create(a=normal(),i=input()){core.resetRegistry();const x=core.createAcceptanceManagement(a,context(),i,op("create"),clock);assert(x.created,x.reasons);return x.record}
function monitoring(a=normal(),i=input()){let r=create(a,i),x=core.startManualManagement(r,{manualStartConfirmation:true,managedBy:"Manager"},op("start"),clock);assert(x.transitioned,x.reasons);x=core.recordManagementProgress(x.record,{managementNote:"monitoring"},op("progress"),clock);assert(x.transitioned,x.reasons);x=core.beginMonitoring(x.record,op("begin monitoring"),clock);assert(x.transitioned,x.reasons);return x.record}
let n=normal(),c=conditional(),g=core.validateManagementEligibility(n,context(),[]);assert(g.eligible&&g.normal,g.reasons);g=core.validateManagementEligibility(c,context(),[]);assert(g.eligible&&g.conditional,g.reasons);assert.strictEqual(core.extractEligibleManagementCandidates([n,c],[context(),context()],[]).length,2);
for(const bad of[normal({acceptanceStatus:"acceptance_accepted"}),normal({acceptanceResult:"reject"}),normal({abnormalityDetected:true}),normal({automaticConditionCompletionAllowed:true}),normal({automaticManagementCompletionAllowed:true}),normal({automaticApplicationAllowed:true}),normal({automaticLearningAllowed:true}),normal({publicReleaseAllowed:true}),normal({externalTransmissionAllowed:true}),conditional({acceptanceConditions:[]})])assert(!core.validateManagementEligibility(bad,context(),[]).eligible);
assert(!core.validateManagementEligibility(n,context("acceptance-32",{targetRecordKey:"other"}),[]).eligible);assert(!core.validateManagementEligibility(n,context(),[{postCorrectionAcceptanceId:"acceptance-32",invalidatedAt:""}]).eligible);
let r=monitoring();assert.strictEqual(r.managementStatus,"monitoring_normal_acceptance");let x=core.confirmManagementEvidence(r,{evidence:["screen"],auditTrailConfirmed:true,warningsReviewed:true},op("evidence"),clock);assert(x.updated);r=x.record;x=core.completeManagement(r,{currentTargetHash:"current-hash",acceptanceSnapshotHash:"acceptance-hash",currentTargetVersion:"v2",acceptanceVersion:"5",managementCompletedAt:"2026-08-04T06:00:00Z",managementReason:"stable",managementSummary:"confirmed"},op("complete"),clock);assert(x.completed,x.reasons);assert.strictEqual(x.record.managementStatus,"management_completed");let candidate=core.createClosureCandidate(x.record,op("closure"),clock);assert(candidate.created);assert(candidate.candidate.readyForManualPostCorrectionClosure);assert(!core.transition(candidate.record,"manual_management_in_progress",op("overwrite"),clock).transitioned);
const conditionalInput=input({acceptanceSnapshot:{acceptanceResult:"conditionally_accept"},conditionItems:[conditionItem],outstandingItems:c.outstandingItems,conditionReviewer:"Reviewer",conditionPriority:"high",conditionSeverity:"medium",outstandingItemOwner:"Owner",outstandingItemDeadline:"2026-08-10T00:00:00Z",followUpOwner:"Owner",followUpDeadline:"2026-08-10T00:00:00Z",followUpType:"condition review"});r=monitoring(c,conditionalInput);assert.strictEqual(r.managementStatus,"monitoring_conditional_acceptance");
x=core.addConditionItem(r,{...conditionItem,conditionItemId:"condition-2",conditionTitle:"Second check"},op("add condition"),clock);assert(x.updated);r=x.record;x=core.updateConditionItem(r,"condition-2",{conditionStatus:"in_progress"},op("update condition"),clock);assert(x.updated);r=x.record;x=core.addConditionEvidence(r,"condition-2",{id:"e2"},op("add evidence"),clock);assert(x.updated);r=x.record;x=core.verifyConditionEvidence(r,"condition-2",op("verify evidence"),clock);assert(x.updated);r=x.record;x=core.completeConditionItem(r,"condition-2","done",op("complete condition"),clock);assert(x.updated);r=x.record;
x=core.addConditionEvidence(r,"condition-1",{id:"e1"},op("add evidence"),clock);r=x.record;x=core.verifyConditionEvidence(r,"condition-1",op("verify evidence"),clock);r=x.record;x=core.completeConditionItem(r,"condition-1","done",op("complete condition"),clock);assert(x.updated);r=x.record;
x=core.addOutstandingItem(r,{outstandingItemId:"out-2",title:"second item",owner:"Owner",deadline:"2026-08-10T00:00:00Z"},op("add outstanding"),clock);assert(x.updated);r=x.record;for(const id of["out-1","out-2"]){x=core.resolveOutstandingItem(r,id,"resolved",op("resolve outstanding"),clock);assert(x.updated);r=x.record}
x=core.startFollowUp(r,{followUpOwner:"Owner",followUpDeadline:"2026-08-10T00:00:00Z",followUpType:"review"},op("follow-up start"),clock);assert(x.updated);r=x.record;x=core.completeFollowUp(r,{followUpResult:"completed",followUpEvidence:["follow-up-evidence"]},op("follow-up complete"),clock);assert(x.updated);r=x.record;
x=core.completeConditions(r,{reviewedBy:"Reviewer",completedAt:"2026-08-04T06:00:00Z",summary:"all done",clock},op("conditions complete"),clock);assert(x.completed,x.reasons);r=x.record;x=core.confirmManagementEvidence(r,{evidence:["management-evidence"],auditTrailConfirmed:true,warningsReviewed:true},op("evidence"),clock);r=x.record;x=core.completeManagement(r,{currentTargetHash:"current-hash",acceptanceSnapshotHash:"acceptance-hash",currentTargetVersion:"v2",acceptanceVersion:"5",managementCompletedAt:"2026-08-04T06:00:00Z",managementReason:"conditions complete"},op("management complete"),clock);assert(x.completed,x.reasons);assert(core.createClosureCandidate(x.record,op("closure"),clock).created);
r=monitoring(c,conditionalInput);x=core.requestDeadlineExtension(r,{reason:"more time",requestedBy:"Manager",newDeadline:"2026-08-20T00:00:00Z"},op("extension request"),clock);assert(x.updated);r=x.record;x=core.approveDeadlineExtension(r,{approvedBy:"Reviewer",newDeadline:"2026-08-20T00:00:00Z"},op("extension approve"),clock);assert(x.updated);assert.strictEqual(x.record.conditionDeadline,"2026-08-20T00:00:00Z");
const request={reason:"review needed",target:"condition-1",owner:"Owner",deadline:"2026-08-10T00:00:00Z",requiredEvidence:["evidence"],nextAction:"manual review"};for(const fn of["requestReverification","requestRedecision","requestRecorrection","requestRollback","requestAdditionalEvidence","requestAdditionalReview"]){r=monitoring();x=core[fn](r,request,op(fn),clock);assert(x.updated,x.reasons)}
r=monitoring();x=core.confirmManagementEvidence(r,{evidence:["screen"],auditTrailConfirmed:true,warningsReviewed:true},op("evidence"),clock);r=x.record;assert(!core.completeManagement(r,{currentTargetHash:"wrong",acceptanceSnapshotHash:"acceptance-hash",currentTargetVersion:"v2",acceptanceVersion:"5",managementCompletedAt:"2026-08-04T06:00:00Z"},op("bad hash"),clock).completed);
const overdue=core.detectOverdue({...r,conditionItems:[{conditionStatus:"pending",conditionDeadline:"2026-08-01T00:00:00Z"}],outstandingItems:[]},clock);assert(overdue.conditionOverdue);
const memory={value:null,setItem(k,val){this.value=val},getItem(){return this.value}};r=create();assert(core.saveRecords(memory,[r]).saved);assert(core.loadRecords(memory).loaded);memory.value=JSON.stringify({schemaVersion:"old",records:[]});assert(!core.loadRecords(memory).loaded);
assert(core.SAFETY.privateLocalOnly&&core.SAFETY.planOnly&&core.SAFETY.protectedMode);for(const k of["automaticConditionCompletionAllowed","automaticManagementCompletionAllowed","automaticApplicationAllowed","automaticLearningAllowed","publicReleaseAllowed","externalTransmissionAllowed","registeredDataMutated","sentExternally","nextPhaseAutomaticallyStarted"])assert.strictEqual(core.SAFETY[k],false,k);
const root=path.join(__dirname,".."),html=fs.readFileSync(path.join(root,"private-local.html"),"utf8"),css=fs.readFileSync(path.join(root,"dashboard.css"),"utf8"),readme=fs.readFileSync(path.join(root,"README.md"),"utf8"),source=fs.readFileSync(path.join(root,"phase26-33-manual-post-registration-post-correction-acceptance-management-core.js"),"utf8");for(const text of["phase26-33-manual-post-registration-post-correction-acceptance-management","対象受入記録","対象判定記録","対象検証記録","対象修正実行記録","対象正式登録記録","管理状態","管理者","受入条件","条件一覧","条件完了率","条件担当者","条件期限","未完了項目","フォローアップ状態","次回確認日","hash結果","version結果","証跡","監査証跡","異常・警告","再検証・再判定・再修正要否","ロールバック要否","追加証跡・追加レビュー要否","次工程移行可否","Private Local only","PLAN_ONLY","protectedMode","自動条件完了なし","自動管理完了なし","自動適用なし","自動学習更新なし","Public公開なし","外部送信なし"])assert(html.includes(text),text);assert(css.includes(".phase2633-panel")&&readme.includes("Phase26-33 Manual Post-Correction Acceptance Management Core"));for(const p of[/fetch\s*\(/,/XMLHttpRequest/,/WebSocket\s*\(/,/automaticConditionCompletionAllowed:\s*true/,/automaticManagementCompletionAllowed:\s*true/,/registeredDataMutated:\s*true/])assert(!p.test(source));
console.log("phase26ManualPostRegistrationPostCorrectionAcceptanceManagementCore.test.js: PASS");
