"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),p266=require("../phase26-6-manual-execution-record-intake-preparation-core.js"),core=require("../phase26-7-manual-result-preview-pre-intake-validation-core.js");
const root=path.resolve(__dirname,".."),clock={now:()=>new Date("2026-08-08T02:00:00Z")},op={performedBy:"owner",reason:"manual confirmation",explicitConfirmation:true};
const target={executionRecordId:"er1",executionRequestRecordId:"eq1",requestId:"r1",executionRecordStatus:"ready_for_manual_result_preview",actualOperator:"owner",actualExecutionDate:"2026-08-08",actualExecutionStartTime:"10:00",actualExecutionEndTime:"10:10",executionMethodObserved:"manual_entry",sourceObserved:"Official",sourceTrustObserved:"official_source",targetObserved:"Tokyo 11R",dataTimepointObserved:"final",expectedRecordCount:18,observedRecordCount:18,countDifference:0,executionOutcome:"completed_as_claimed",abnormalityDetected:false,interruptionOccurred:false,stopConditionTriggered:false,cancellationConditionTriggered:false,intakePreparationChecklist:Object.fromEntries(p266.INTAKE_PREPARATION_CHECKS.map(k=>[k,true])),...p266.SAFE_FLAGS};
const comparison={matchResult:"matched",difference:"none",differenceReason:"none",humanResult:"accepted",confirmedBy:"owner",confirmedAt:"2026-08-08T01:30:00Z",decisionReason:"matched"};
const checklist=core.CHECK_DEFINITIONS.map(d=>({...d,status:"passed",checkedBy:"owner",checkedAt:"2026-08-08T01:40:00Z",note:"confirmed"}));
const input={previewRequestId:"pr1",requestedBy:"owner",requestDate:"2026-08-08",requestTime:"11:00",requestReason:"manual preview preparation",expectedResultFormat:"csv_declared",expectedFileType:"csv",expectedEncoding:"utf-8",expectedDelimiter:"comma",expectedHeaderPresent:true,expectedRecordUnit:"one result per row",expectedTargetPeriod:"2026-08-08",expectedReferenceTimepoint:"final",expectedSource:"Official",expectedMethod:"manual_entry",expectedSourceTrust:"official_source",expectedTarget:"Tokyo 11R",expectedCount:18,note:"metadata only",expectedRequiredColumns:["raceId","placing"],expectedUniqueIdentifier:"raceId+horseNumber",expectedDateTimeColumn:"raceDate",expectedTargetIdentifierColumn:"raceId",countComparison:{judgment:"exact_match",judgmentReason:"counts match",confirmedBy:"owner",confirmedAt:"2026-08-08T01:30:00Z"},sourceComparison:comparison,methodComparison:comparison,trustComparison:{...comparison,additionalReviewRequired:false,intakeAccepted:true},targetComparison:{...comparison,targetScope:"Tokyo 11R",identificationCondition:"raceId",exclusions:"none"},timepointComparison:{...comparison,timeDifference:"none"},checklist,unresolvedIssues:[],exceptionResolution:{abnormalityResolved:true,interruptionResolved:true,stopResolved:true,cancellationResolved:true},finalConfirmedBy:"owner",finalConfirmedAt:"2026-08-08T01:50:00Z",finalDecisionReason:"all metadata confirmed"};
assert.strictEqual(core.PHASE266_REFERENCE,p266);assert(core.CHECK_DEFINITIONS.length>=40);assert(core.validatePhase266Target(target).valid);
for(const status of["execution_recorded","intake_preparation_blocked","cancelled","expired"])assert(!core.validatePhase266Target({...target,executionRecordStatus:status}).valid,status);
assert(!core.createPreviewRequest(target,{...input,requestReason:""},op,clock).created);
const created=core.createPreviewRequest(target,input,op,clock);assert(created.created);assert.equal(created.record.status,"result_preview_request_recorded");assert.equal(created.record.auditHistory.length,1);
function startValidation(record=created.record){return core.transition(record,"validating_pre_intake_conditions",op,target,clock)}
const validating=startValidation();assert(validating.transitioned);
function rejectChange(changes){const updated=core.updateRecord(validating.record,changes,op,clock).record;return core.transition(updated,"pre_intake_validation_passed",op,target,clock)}
assert(!rejectChange({expectedResultFormat:""}).transitioned);
assert(!rejectChange({countComparison:{...input.countComparison,judgment:"needs_review"}}).transitioned);
assert(!rejectChange({sourceComparison:{...comparison,matchResult:"different",humanResult:"needs_review"}}).transitioned);
assert(!rejectChange({methodComparison:{...comparison,matchResult:"different",humanResult:"needs_review"}}).transitioned);
assert(!rejectChange({expectedSourceTrust:"user_pasted_text",trustComparison:{...comparison,additionalReviewRequired:false,intakeAccepted:false}}).transitioned);
assert(!rejectChange({targetComparison:{...input.targetComparison,matchResult:"different",humanResult:"needs_review"}}).transitioned);
assert(!rejectChange({timepointComparison:{...input.timepointComparison,matchResult:"different",humanResult:"needs_review"}}).transitioned);
for(const status of["failed","unchecked","needs_review"]){const bad=checklist.map((c,i)=>i===0?{...c,status}:c);assert(!rejectChange({checklist:bad}).transitioned,status)}
const cancelled=core.transition(validating.record,"pre_intake_validation_cancelled",op,target,clock);assert(cancelled.transitioned);assert(!core.transition(cancelled.record,"validating_pre_intake_conditions",op,target,clock).transitioned);
assert(!core.transition(created.record,"ready_for_manual_result_preview_creation",op,target,clock).transitioned);
const passed=core.transition(validating.record,"pre_intake_validation_passed",op,target,clock);assert(passed.transitioned);const ready=core.transition(passed.record,"ready_for_manual_result_preview_creation",op,target,clock);assert(ready.transitioned);assert.equal(ready.record.status,"ready_for_manual_result_preview_creation");
for(const[k,v]of Object.entries(core.SAFE_FLAGS))assert.strictEqual(ready.record[k],v,k);
const tampered=core.updateRecord(created.record,{resultDataRead:true,resultPreviewCreated:true},op,clock).record;assert.equal(tampered.resultDataRead,false);assert.equal(tampered.resultPreviewCreated,false);
const polluted=core.makePhase266Snapshot({...target,apiKey:"x",Cookie:"x",password:"x",fileContent:"x",resultData:[1],parsedRecords:[1]});for(const k of["apiKey","Cookie","password","fileContent","resultData","parsedRecords"])assert(!Object.prototype.hasOwnProperty.call(polluted,k),k);
const source=fs.readFileSync(path.join(root,"phase26-7-manual-result-preview-pre-intake-validation-core.js"),"utf8"),html=fs.readFileSync(path.join(root,"private-local.html"),"utf8"),css=fs.readFileSync(path.join(root,"dashboard.css"),"utf8"),readme=fs.readFileSync(path.join(root,"README.md"),"utf8");
for(const token of["fetch(","XMLHttpRequest","WebSocket(","EventSource(","FileReader","readAsText(","JSON.parse(","setInterval(","Worker("])assert(!source.includes(token),token);for(const name of["selectResultFile","readResultFile","parseCsv","parseJson","createResultPreview","saveResultData","importResultData","applyResultData","updateLearning","connectExternalApi","scrapeWeb","autoTransition"])assert.equal(core[name],undefined);
for(const marker of['id="phase26-7-manual-result-preview-pre-intake-validation"','id="phase267-preview-request-form"',"対象となるPhase26-6記録","現在状態","形式確認結果","件数比較結果","取得元比較結果","取得方式比較結果","信頼区分比較結果","対象比較結果","時点比較結果","受入前検証チェックリスト","未解決事項","人間による最終確認欄","状態遷移ボタン","安全フラグ一覧","禁止処理一覧","Private Local only","PLAN_ONLY","protectedMode","ファイル読込なし","保存・取込・適用・学習なし"])assert(html.includes(marker),marker);
assert(!/type="file"/i.test(html.slice(html.indexOf('id="phase26-7-manual-result-preview-pre-intake-validation"'))));assert(html.includes("phase26-7-manual-result-preview-pre-intake-validation-core.js"));assert(css.includes(".phase267-panel"));assert(readme.includes("Phase26-7 Manual Result Preview Request and Pre-Intake Validation Core"));
console.log("phase26ManualResultPreviewPreIntakeValidationCore.test.js: PASS");
