const assert = require("assert");
const { COURSE_DB_FILE_NAME, DISTANCE_DB_FILE_NAME, HISTORY_DB_FILE_NAME, RACE_DATA_FILE_NAME, accumulateIntegratedDatabases, buildRaceDataRecord, courseLabels, createEmptyCourseDb, createEmptyDistanceDb, createEmptyHistoryDb, createEmptyRaceData, distanceCategories, historyCategories, normalizeRaceNumber, serializeCourseDb, serializeDistanceDb, serializeHistoryDb, serializeRaceData, upsertRaceDataRecord } = require("../race-page.js");
assert.strictEqual(RACE_DATA_FILE_NAME, "race-data.json");
assert.strictEqual(HISTORY_DB_FILE_NAME, "history-db.json");
assert.strictEqual(COURSE_DB_FILE_NAME, "course-db.json");
assert.strictEqual(DISTANCE_DB_FILE_NAME, "distance-db.json");
assert.strictEqual(historyCategories.tokyo, "東京");
assert.strictEqual(courseLabels.win5, "WIN5");
assert.ok(distanceCategories.includes("芝1600"));
assert.strictEqual(normalizeRaceNumber(13), 12);
const record = buildRaceDataRecord({ courseKey: "tokyo", raceNumber: 11, values: { date: "2026-06-15", distance: "芝1600", prediction: "東京R11 事前予想", result: "東京R11 結果", review: "東京R11 検証", update: "東京R11 アップデート", hitRate: "42%", returnRate: "118%", trifectaReturnRate: "164%", win5Result: "対象外", aiUpdateLog: "展開評価を更新" }, now: new Date("2026-06-15T09:00:00.000Z") });
let raceData = upsertRaceDataRecord(createEmptyRaceData(), record);
assert.strictEqual(raceData.version, "1.6");
assert.strictEqual(raceData.releaseStatus, "Official Release v1.6");
assert.ok(serializeRaceData(raceData).includes("東京R11 事前予想"));
const integrated = accumulateIntegratedDatabases({ historyDb: createEmptyHistoryDb(), courseDb: createEmptyCourseDb(), distanceDb: createEmptyDistanceDb(), record });
assert.strictEqual(integrated.historyDb.categories["東京"].length, 1);
assert.strictEqual(integrated.courseDb.courses["東京"].learningCount, 1);
assert.strictEqual(integrated.distanceDb.distances["芝1600"].learningCount, 1);
assert.ok(serializeHistoryDb(integrated.historyDb).includes("展開評価を更新"));
assert.ok(serializeCourseDb(integrated.courseDb).includes("東京"));
assert.ok(serializeDistanceDb(integrated.distanceDb).includes("芝1600"));
console.log("raceDataStorage tests passed");
