const assert = require("assert");
const { PROFIT_DB_FILE_NAME, RETURN_AI_DB_FILE_NAME, accumulateIntegratedDatabases, buildProfitEntry, buildRaceDataRecord, createEmptyCourseDb, createEmptyDistanceDb, createEmptyHistoryDb, createEmptyProfitDb, createEmptyReturnAiDb, favoriteZoneFromPopularity, serializeProfitDb, serializeReturnAiDb } = require("../race-page.js");
assert.strictEqual(PROFIT_DB_FILE_NAME, "profit-db.json");
assert.strictEqual(RETURN_AI_DB_FILE_NAME, "return-ai-db.json");
assert.strictEqual(favoriteZoneFromPopularity(2), "A");
assert.strictEqual(favoriteZoneFromPopularity(5), "B");
assert.strictEqual(favoriteZoneFromPopularity(8), "C");
assert.strictEqual(favoriteZoneFromPopularity(12), "D");
const record = buildRaceDataRecord({ courseKey: "tokyo", raceNumber: 11, values: { date: "2026-06-15", distance: "芝1600", favorite: "5", jockey: "橋本騎手", trainer: "橋本厩舎", prediction: "東京R11 事前予想", result: "東京R11 結果", review: "東京R11 検証", update: "東京R11 アップデート", betAmount: "1000", payout: "2500", odds: "25.0", trifecta: "的中", win5: "" }, now: new Date("2026-06-15T09:00:00.000Z") });
assert.strictEqual(record.profit, 1500);
assert.strictEqual(record.hit, true);
assert.strictEqual(record.favoriteZone, "B");
assert.deepStrictEqual(buildProfitEntry(record), { date: "2026-06-15", course: "東京", race: "R11", betAmount: 1000, payout: 2500, profit: 1500, hit: true, odds: "25.0", trifecta: "的中", win5: "" });
const integrated = accumulateIntegratedDatabases({ historyDb: createEmptyHistoryDb(), courseDb: createEmptyCourseDb(), distanceDb: createEmptyDistanceDb(), profitDb: createEmptyProfitDb(), returnAiDb: createEmptyReturnAiDb(), record });
assert.strictEqual(integrated.profitDb.version, "1.7");
assert.strictEqual(integrated.profitDb.annualProfit, 1500);
assert.strictEqual(integrated.profitDb.totalBetAmount, 1000);
assert.strictEqual(integrated.profitDb.totalPayout, 2500);
assert.strictEqual(integrated.returnAiDb.returnRate, "250.0%");
assert.strictEqual(integrated.returnAiDb.hitRate, "100.0%");
assert.strictEqual(integrated.returnAiDb.favoriteZoneRate.B.count, 1);
assert.strictEqual(integrated.returnAiDb.favoriteZoneRate.B.returnRate, "250.0%");
assert.ok(serializeProfitDb(integrated.profitDb).includes("\"profit\": 1500"));
assert.ok(serializeReturnAiDb(integrated.returnAiDb).includes("\"returnRate\": \"250.0%\""));
console.log("raceDataStorage tests passed");
